/**
 * Manager feature — catalog CRUD (manager-only).
 *
 * Internal: api/, components/, hooks/, schemas/
 */
export {
  createCategory,
  createCombo,
  createDiscountCode,
  createProduct,
  deleteCategory,
  deleteCombo,
  deleteDiscountCode,
  deleteProduct,
  getCategoryById,
  getComboById,
  getDiscountCodeById,
  getProductById,
  listCategories,
  listCombos,
  listDiscountCodes,
  listProducts,
  updateCategory,
  updateCombo,
  updateDiscountCode,
  updateProduct,
} from "./api";
export {
  CategoryForm,
  ComboForm,
  DiscountCodeForm,
  ManagerCategoriesTable,
  ManagerCombosTable,
  ManagerDiscountCodesTable,
  ManagerProductsTable,
  ProductForm,
} from "./components";
export {
  managerQueryKeys,
  useCategories,
  useCategory,
  useCombo,
  useCombos,
  useCreateCategory,
  useCreateCombo,
  useCreateDiscountCode,
  useCreateProduct,
  useDeleteCategory,
  useDeleteCombo,
  useDeleteDiscountCode,
  useDeleteProduct,
  useDiscountCode,
  useDiscountCodes,
  useProduct,
  useProducts,
  useUpdateCategory,
  useUpdateCombo,
  useUpdateDiscountCode,
  useUpdateProduct,
} from "./hooks";
export {
  categoryFormSchema,
  categoryListFilterSchema,
  comboFormSchema,
  comboListFilterSchema,
  discountCodeFormSchema,
  discountCodeListFilterSchema,
  DISCOUNT_TYPE,
  managerCategorySchema,
  managerComboSchema,
  managerDiscountCodeSchema,
  managerProductSchema,
  productFormSchema,
  productListFilterSchema,
} from "./schemas";
export type {
  CategoriesListResult,
  CategoryFormInput,
  CategoryListFilterInput,
  ComboFormInput,
  ComboListFilterInput,
  CombosListResult,
  DiscountCodeFormInput,
  DiscountCodeListFilterInput,
  DiscountCodesListResult,
  ManagerCategory,
  ManagerCombo,
  ManagerDiscountCode,
  ManagerProduct,
  ProductFormInput,
  ProductListFilterInput,
  ProductsListResult,
} from "./schemas";
