// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countAuditLogsByTargetID = `-- name: CountAuditLogsByTargetID :one
SELECT COUNT(*)::bigint AS total
FROM audit_logs
WHERE target_id = $1
`

// CountAuditLogsByTargetID
//
//	SELECT COUNT(*)::bigint AS total
//	FROM audit_logs
//	WHERE target_id = $1
func (q *Queries) CountAuditLogsByTargetID(ctx context.Context, targetID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByTargetID, targetID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    actor_id,
    actor_role,
    action,
    target_id,
    target_type,
    before_jsonb,
    after_jsonb,
    ip,
    user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8, '')::inet, $9)
`

type CreateAuditLogParams struct {
	ActorID     uuid.UUID       `json:"actorId"`
	ActorRole   UserRole        `json:"actorRole"`
	Action      string          `json:"action"`
	TargetID    *uuid.UUID      `json:"targetId"`
	TargetType  string          `json:"targetType"`
	BeforeJsonb json.RawMessage `json:"beforeJsonb"`
	AfterJsonb  json.RawMessage `json:"afterJsonb"`
	Column8     interface{}     `json:"column8"`
	UserAgent   *string         `json:"userAgent"`
}

// CreateAuditLog
//
//	INSERT INTO audit_logs (
//	    actor_id,
//	    actor_role,
//	    action,
//	    target_id,
//	    target_type,
//	    before_jsonb,
//	    after_jsonb,
//	    ip,
//	    user_agent
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8, '')::inet, $9)
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.TargetID,
		arg.TargetType,
		arg.BeforeJsonb,
		arg.AfterJsonb,
		arg.Column8,
		arg.UserAgent,
	)
	return err
}

const listAuditLogsByTargetID = `-- name: ListAuditLogsByTargetID :many
SELECT
    al.id,
    al.actor_id,
    al.actor_role,
    u.email AS actor_email,
    al.action,
    al.before_jsonb,
    al.after_jsonb,
    al.created_at
FROM audit_logs al
INNER JOIN users u ON u.id = al.actor_id
WHERE al.target_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByTargetIDParams struct {
	TargetID *uuid.UUID `json:"targetId"`
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
}

type ListAuditLogsByTargetIDRow struct {
	ID          uuid.UUID       `json:"id"`
	ActorID     uuid.UUID       `json:"actorId"`
	ActorRole   UserRole        `json:"actorRole"`
	ActorEmail  string          `json:"actorEmail"`
	Action      string          `json:"action"`
	BeforeJsonb json.RawMessage `json:"beforeJsonb"`
	AfterJsonb  json.RawMessage `json:"afterJsonb"`
	CreatedAt   time.Time       `json:"createdAt"`
}

// ListAuditLogsByTargetID
//
//	SELECT
//	    al.id,
//	    al.actor_id,
//	    al.actor_role,
//	    u.email AS actor_email,
//	    al.action,
//	    al.before_jsonb,
//	    al.after_jsonb,
//	    al.created_at
//	FROM audit_logs al
//	INNER JOIN users u ON u.id = al.actor_id
//	WHERE al.target_id = $1
//	ORDER BY al.created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListAuditLogsByTargetID(ctx context.Context, arg ListAuditLogsByTargetIDParams) ([]ListAuditLogsByTargetIDRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTargetID, arg.TargetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByTargetIDRow{}
	for rows.Next() {
		var i ListAuditLogsByTargetIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.ActorEmail,
			&i.Action,
			&i.BeforeJsonb,
			&i.AfterJsonb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForSubjectBefore = `-- name: ListAuditLogsForSubjectBefore :many
SELECT
    id,
    actor_id,
    actor_role,
    action,
    before_jsonb,
    after_jsonb,
    COALESCE(host(ip), '')::text AS ip,
    user_agent,
    created_at
FROM audit_logs
WHERE target_type IN ('user', 'user_profile')
  AND target_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditLogsForSubjectBeforeParams struct {
	SubjectID *uuid.UUID `json:"subjectId"`
	BeforeAt  *time.Time `json:"beforeAt"`
	BeforeID  *uuid.UUID `json:"beforeId"`
	Limit     int32      `json:"limit"`
}

type ListAuditLogsForSubjectBeforeRow struct {
	ID          uuid.UUID       `json:"id"`
	ActorID     uuid.UUID       `json:"actorId"`
	ActorRole   UserRole        `json:"actorRole"`
	Action      string          `json:"action"`
	BeforeJsonb json.RawMessage `json:"beforeJsonb"`
	AfterJsonb  json.RawMessage `json:"afterJsonb"`
	Ip          string          `json:"ip"`
	UserAgent   *string         `json:"userAgent"`
	CreatedAt   time.Time       `json:"createdAt"`
}

// What was recorded about one account — the account itself and its profile —
// newest first, a page at a time by keyset, as the account holder's data
// export reads it.
//
//	SELECT
//	    id,
//	    actor_id,
//	    actor_role,
//	    action,
//	    before_jsonb,
//	    after_jsonb,
//	    COALESCE(host(ip), '')::text AS ip,
//	    user_agent,
//	    created_at
//	FROM audit_logs
//	WHERE target_type IN ('user', 'user_profile')
//	  AND target_id = $1
//	  AND (
//	    $2::timestamptz IS NULL
//	    OR (created_at, id) < ($2::timestamptz, $3::uuid)
//	  )
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4
func (q *Queries) ListAuditLogsForSubjectBefore(ctx context.Context, arg ListAuditLogsForSubjectBeforeParams) ([]ListAuditLogsForSubjectBeforeRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForSubjectBefore,
		arg.SubjectID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsForSubjectBeforeRow{}
	for rows.Next() {
		var i ListAuditLogsForSubjectBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.BeforeJsonb,
			&i.AfterJsonb,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scrubAuditLogsForSubject = `-- name: ScrubAuditLogsForSubject :exec
UPDATE audit_logs
SET before_jsonb = CASE
      WHEN target_type IN ('user', 'user_profile') AND target_id = $1 THEN '{}'::jsonb
      ELSE before_jsonb
    END,
    after_jsonb = CASE
      WHEN target_type IN ('user', 'user_profile') AND target_id = $1 THEN '{}'::jsonb
      ELSE after_jsonb
    END,
    ip = CASE WHEN actor_id = $1 THEN NULL ELSE ip END,
    user_agent = CASE WHEN actor_id = $1 THEN NULL ELSE user_agent END
WHERE actor_id = $1
   OR (target_type IN ('user', 'user_profile') AND target_id = $1)
`

// Removes an erased account's personal data from the audit trail and keeps
// the trail: changes to the account and its profile lose their before and
// after values (a profile change holds a name or phone number), and the
// account's own actions lose the network and browser they came from. What
// happened, when, and by which role stays on record.
//
//	UPDATE audit_logs
//	SET before_jsonb = CASE
//	      WHEN target_type IN ('user', 'user_profile') AND target_id = $1 THEN '{}'::jsonb
//	      ELSE before_jsonb
//	    END,
//	    after_jsonb = CASE
//	      WHEN target_type IN ('user', 'user_profile') AND target_id = $1 THEN '{}'::jsonb
//	      ELSE after_jsonb
//	    END,
//	    ip = CASE WHEN actor_id = $1 THEN NULL ELSE ip END,
//	    user_agent = CASE WHEN actor_id = $1 THEN NULL ELSE user_agent END
//	WHERE actor_id = $1
//	   OR (target_type IN ('user', 'user_profile') AND target_id = $1)
func (q *Queries) ScrubAuditLogsForSubject(ctx context.Context, subjectID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, scrubAuditLogsForSubject, subjectID)
	return err
}
