// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const clearCartDiscountCode = `-- name: ClearCartDiscountCode :exec
UPDATE carts
SET discount_code_id = NULL, updated_at = now()
WHERE id = $1
`

// ClearCartDiscountCode
//
//	UPDATE carts
//	SET discount_code_id = NULL, updated_at = now()
//	WHERE id = $1
func (q *Queries) ClearCartDiscountCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearCartDiscountCode, id)
	return err
}

const countCartItems = `-- name: CountCartItems :one
SELECT COUNT(*)::bigint AS count
FROM cart_items
WHERE cart_id = $1
`

// CountCartItems
//
//	SELECT COUNT(*)::bigint AS count
//	FROM cart_items
//	WHERE cart_id = $1
func (q *Queries) CountCartItems(ctx context.Context, cartID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCartItems, cartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
RETURNING id, user_id, discount_code_id, created_at, updated_at
`

// CreateCart
//
//	INSERT INTO carts (user_id)
//	VALUES ($1)
//	RETURNING id, user_id, discount_code_id, created_at, updated_at
func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscountCodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, line_type, product_id, combo_id, quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
`

type CreateCartItemParams struct {
	CartID    uuid.UUID     `db:"cart_id" json:"cartId"`
	LineType  CartLineType  `db:"line_type" json:"lineType"`
	ProductID uuid.NullUUID `db:"product_id" json:"productId"`
	ComboID   uuid.NullUUID `db:"combo_id" json:"comboId"`
	Quantity  int32         `db:"quantity" json:"quantity"`
}

// CreateCartItem
//
//	INSERT INTO cart_items (cart_id, line_type, product_id, combo_id, quantity)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, createCartItem,
		arg.CartID,
		arg.LineType,
		arg.ProductID,
		arg.ComboID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllCartItems = `-- name: DeleteAllCartItems :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

// DeleteAllCartItems
//
//	DELETE FROM cart_items
//	WHERE cart_id = $1
func (q *Queries) DeleteAllCartItems(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllCartItems, cartID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items
WHERE cart_id = $1 AND id = $2
`

type DeleteCartItemParams struct {
	CartID uuid.UUID `db:"cart_id" json:"cartId"`
	ID     uuid.UUID `db:"id" json:"id"`
}

// DeleteCartItem
//
//	DELETE FROM cart_items
//	WHERE cart_id = $1 AND id = $2
func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCartItem, arg.CartID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, discount_code_id, created_at, updated_at
FROM carts
WHERE user_id = $1
`

// GetCartByUserID
//
//	SELECT id, user_id, discount_code_id, created_at, updated_at
//	FROM carts
//	WHERE user_id = $1
func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscountCodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByCombo = `-- name: GetCartItemByCombo :one
SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1 AND line_type = 'combo' AND combo_id = $2
`

type GetCartItemByComboParams struct {
	CartID  uuid.UUID     `db:"cart_id" json:"cartId"`
	ComboID uuid.NullUUID `db:"combo_id" json:"comboId"`
}

// GetCartItemByCombo
//
//	SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
//	FROM cart_items
//	WHERE cart_id = $1 AND line_type = 'combo' AND combo_id = $2
func (q *Queries) GetCartItemByCombo(ctx context.Context, arg GetCartItemByComboParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByCombo, arg.CartID, arg.ComboID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1 AND id = $2
`

type GetCartItemByIDParams struct {
	CartID uuid.UUID `db:"cart_id" json:"cartId"`
	ID     uuid.UUID `db:"id" json:"id"`
}

// GetCartItemByID
//
//	SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
//	FROM cart_items
//	WHERE cart_id = $1 AND id = $2
func (q *Queries) GetCartItemByID(ctx context.Context, arg GetCartItemByIDParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByID, arg.CartID, arg.ID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1 AND line_type = 'product' AND product_id = $2
`

type GetCartItemByProductParams struct {
	CartID    uuid.UUID     `db:"cart_id" json:"cartId"`
	ProductID uuid.NullUUID `db:"product_id" json:"productId"`
}

// GetCartItemByProduct
//
//	SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
//	FROM cart_items
//	WHERE cart_id = $1 AND line_type = 'product' AND product_id = $2
func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

// ListCartItemsByCartID
//
//	SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
//	FROM cart_items
//	WHERE cart_id = $1
//	ORDER BY created_at ASC
func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.LineType,
			&i.ProductID,
			&i.ComboID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCartDiscountCodeID = `-- name: SetCartDiscountCodeID :exec
UPDATE carts
SET discount_code_id = $2, updated_at = now()
WHERE id = $1
`

type SetCartDiscountCodeIDParams struct {
	ID             uuid.UUID     `db:"id" json:"id"`
	DiscountCodeID uuid.NullUUID `db:"discount_code_id" json:"discountCodeId"`
}

// SetCartDiscountCodeID
//
//	UPDATE carts
//	SET discount_code_id = $2, updated_at = now()
//	WHERE id = $1
func (q *Queries) SetCartDiscountCodeID(ctx context.Context, arg SetCartDiscountCodeIDParams) error {
	_, err := q.db.ExecContext(ctx, setCartDiscountCodeID, arg.ID, arg.DiscountCodeID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $3, updated_at = now()
WHERE cart_id = $1 AND id = $2
RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	CartID   uuid.UUID `db:"cart_id" json:"cartId"`
	ID       uuid.UUID `db:"id" json:"id"`
	Quantity int32     `db:"quantity" json:"quantity"`
}

// UpdateCartItemQuantity
//
//	UPDATE cart_items
//	SET quantity = $3, updated_at = now()
//	WHERE cart_id = $1 AND id = $2
//	RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, updateCartItemQuantity, arg.CartID, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
