// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const catalogListCategories = `-- name: CatalogListCategories :many
SELECT id, name, slug, sort_order
FROM categories
WHERE deleted_at IS NULL
  AND is_active = true
ORDER BY sort_order ASC, name ASC
LIMIT $1 OFFSET $2
`

type CatalogListCategoriesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type CatalogListCategoriesRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	SortOrder int32     `db:"sort_order" json:"sortOrder"`
}

// CatalogListCategories
//
//	SELECT id, name, slug, sort_order
//	FROM categories
//	WHERE deleted_at IS NULL
//	  AND is_active = true
//	ORDER BY sort_order ASC, name ASC
//	LIMIT $1 OFFSET $2
func (q *Queries) CatalogListCategories(ctx context.Context, arg CatalogListCategoriesParams) ([]CatalogListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, catalogListCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListCategoriesRow{}
	for rows.Next() {
		var i CatalogListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListCategoriesCount = `-- name: CatalogListCategoriesCount :one
SELECT count(*)::bigint AS count
FROM categories
WHERE deleted_at IS NULL
  AND is_active = true
`

// CatalogListCategoriesCount
//
//	SELECT count(*)::bigint AS count
//	FROM categories
//	WHERE deleted_at IS NULL
//	  AND is_active = true
func (q *Queries) CatalogListCategoriesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, catalogListCategoriesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	Name      string `db:"name" json:"name"`
	Slug      string `db:"slug" json:"slug"`
	SortOrder int32  `db:"sort_order" json:"sortOrder"`
	IsActive  bool   `db:"is_active" json:"isActive"`
}

// CreateCategory
//
//	INSERT INTO categories (name, slug, sort_order, is_active)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE id = $1
  AND deleted_at IS NULL
`

// GetCategoryByID
//
//	SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
//	FROM categories
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const managerListCategories = `-- name: ManagerListCategories :many
SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
FROM categories
WHERE deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3::text || '%'
    OR slug ILIKE '%' || $3::text || '%'
  )
ORDER BY sort_order ASC, name ASC
LIMIT $1 OFFSET $2
`

type ManagerListCategoriesParams struct {
	Limit  int32          `db:"limit" json:"limit"`
	Offset int32          `db:"offset" json:"offset"`
	Search sql.NullString `db:"search" json:"search"`
}

// ManagerListCategories
//
//	SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
//	FROM categories
//	WHERE deleted_at IS NULL
//	  AND (
//	    $3::text IS NULL
//	    OR name ILIKE '%' || $3::text || '%'
//	    OR slug ILIKE '%' || $3::text || '%'
//	  )
//	ORDER BY sort_order ASC, name ASC
//	LIMIT $1 OFFSET $2
func (q *Queries) ManagerListCategories(ctx context.Context, arg ManagerListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, managerListCategories, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListCategoriesCount = `-- name: ManagerListCategoriesCount :one
SELECT count(*)::bigint AS count
FROM categories
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR name ILIKE '%' || $1::text || '%'
    OR slug ILIKE '%' || $1::text || '%'
  )
`

// ManagerListCategoriesCount
//
//	SELECT count(*)::bigint AS count
//	FROM categories
//	WHERE deleted_at IS NULL
//	  AND (
//	    $1::text IS NULL
//	    OR name ILIKE '%' || $1::text || '%'
//	    OR slug ILIKE '%' || $1::text || '%'
//	  )
func (q *Queries) ManagerListCategoriesCount(ctx context.Context, search sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, managerListCategoriesCount, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteCategoryIfNoProducts = `-- name: SoftDeleteCategoryIfNoProducts :execrows
UPDATE categories
SET deleted_at = now(),
    updated_at = now()
WHERE categories.id = $1
  AND categories.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM products
    WHERE products.category_id = categories.id
      AND products.deleted_at IS NULL
  )
`

// SoftDeleteCategoryIfNoProducts
//
//	UPDATE categories
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE categories.id = $1
//	  AND categories.deleted_at IS NULL
//	  AND NOT EXISTS (
//	    SELECT 1
//	    FROM products
//	    WHERE products.category_id = categories.id
//	      AND products.deleted_at IS NULL
//	  )
func (q *Queries) SoftDeleteCategoryIfNoProducts(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteCategoryIfNoProducts, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name       = $2,
    slug       = $3,
    sort_order = $4,
    is_active  = $5,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	SortOrder int32     `db:"sort_order" json:"sortOrder"`
	IsActive  bool      `db:"is_active" json:"isActive"`
}

// UpdateCategory
//
//	UPDATE categories
//	SET name       = $2,
//	    slug       = $3,
//	    sort_order = $4,
//	    is_active  = $5,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
