// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: combo.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const catalogGetComboByID = `-- name: CatalogGetComboByID :one
SELECT id, name, slug, price_cents, image_url, starts_at, ends_at
FROM combos
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = true
  AND starts_at <= now()
  AND ends_at > now()
`

type CatalogGetComboByIDRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	PriceCents int64     `json:"priceCents"`
	ImageUrl   *string   `json:"imageUrl"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
}

// CatalogGetComboByID
//
//	SELECT id, name, slug, price_cents, image_url, starts_at, ends_at
//	FROM combos
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	  AND is_active = true
//	  AND starts_at <= now()
//	  AND ends_at > now()
func (q *Queries) CatalogGetComboByID(ctx context.Context, id uuid.UUID) (CatalogGetComboByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogGetComboByID, id)
	var i CatalogGetComboByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const catalogGetCombosByIDs = `-- name: CatalogGetCombosByIDs :many
SELECT c.id, c.name, c.slug, c.price_cents, c.image_url, c.starts_at, c.ends_at
FROM combos c
WHERE c.id = ANY($1::uuid[])
  AND c.deleted_at IS NULL
  AND c.is_active = true
  AND c.starts_at <= now()
  AND c.ends_at > now()
  AND EXISTS (
    SELECT 1
    FROM combo_items ci
    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
    WHERE ci.combo_id = c.id
  )
`

type CatalogGetCombosByIDsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	PriceCents int64     `json:"priceCents"`
	ImageUrl   *string   `json:"imageUrl"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
}

// CatalogGetCombosByIDs
//
//	SELECT c.id, c.name, c.slug, c.price_cents, c.image_url, c.starts_at, c.ends_at
//	FROM combos c
//	WHERE c.id = ANY($1::uuid[])
//	  AND c.deleted_at IS NULL
//	  AND c.is_active = true
//	  AND c.starts_at <= now()
//	  AND c.ends_at > now()
//	  AND EXISTS (
//	    SELECT 1
//	    FROM combo_items ci
//	    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
//	    WHERE ci.combo_id = c.id
//	  )
func (q *Queries) CatalogGetCombosByIDs(ctx context.Context, comboIds []uuid.UUID) ([]CatalogGetCombosByIDsRow, error) {
	rows, err := q.db.Query(ctx, catalogGetCombosByIDs, comboIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogGetCombosByIDsRow{}
	for rows.Next() {
		var i CatalogGetCombosByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PriceCents,
			&i.ImageUrl,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListCombos = `-- name: CatalogListCombos :many
SELECT c.id, c.name, c.slug, c.price_cents, c.image_url, c.starts_at, c.ends_at
FROM combos c
WHERE c.deleted_at IS NULL
  AND c.is_active = true
  AND c.starts_at <= now()
  AND c.ends_at > now()
  AND EXISTS (
    SELECT 1
    FROM combo_items ci
    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
    WHERE ci.combo_id = c.id
  )
ORDER BY c.starts_at ASC, c.name ASC
LIMIT $1 OFFSET $2
`

type CatalogListCombosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type CatalogListCombosRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	PriceCents int64     `json:"priceCents"`
	ImageUrl   *string   `json:"imageUrl"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
}

// CatalogListCombos
//
//	SELECT c.id, c.name, c.slug, c.price_cents, c.image_url, c.starts_at, c.ends_at
//	FROM combos c
//	WHERE c.deleted_at IS NULL
//	  AND c.is_active = true
//	  AND c.starts_at <= now()
//	  AND c.ends_at > now()
//	  AND EXISTS (
//	    SELECT 1
//	    FROM combo_items ci
//	    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
//	    WHERE ci.combo_id = c.id
//	  )
//	ORDER BY c.starts_at ASC, c.name ASC
//	LIMIT $1 OFFSET $2
func (q *Queries) CatalogListCombos(ctx context.Context, arg CatalogListCombosParams) ([]CatalogListCombosRow, error) {
	rows, err := q.db.Query(ctx, catalogListCombos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListCombosRow{}
	for rows.Next() {
		var i CatalogListCombosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PriceCents,
			&i.ImageUrl,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListCombosCount = `-- name: CatalogListCombosCount :one
SELECT COUNT(*)::bigint AS count
FROM combos c
WHERE c.deleted_at IS NULL
  AND c.is_active = true
  AND c.starts_at <= now()
  AND c.ends_at > now()
  AND EXISTS (
    SELECT 1
    FROM combo_items ci
    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
    WHERE ci.combo_id = c.id
  )
`

// CatalogListCombosCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM combos c
//	WHERE c.deleted_at IS NULL
//	  AND c.is_active = true
//	  AND c.starts_at <= now()
//	  AND c.ends_at > now()
//	  AND EXISTS (
//	    SELECT 1
//	    FROM combo_items ci
//	    INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	    INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
//	    WHERE ci.combo_id = c.id
//	  )
func (q *Queries) CatalogListCombosCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, catalogListCombosCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAvailableProductsForCombo = `-- name: CountAvailableProductsForCombo :one
SELECT COUNT(DISTINCT p.id)::bigint AS count
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE p.id = ANY($1::uuid[])
  AND p.deleted_at IS NULL
  AND p.is_active = true
`

// CountAvailableProductsForCombo
//
//	SELECT COUNT(DISTINCT p.id)::bigint AS count
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE p.id = ANY($1::uuid[])
//	  AND p.deleted_at IS NULL
//	  AND p.is_active = true
func (q *Queries) CountAvailableProductsForCombo(ctx context.Context, productIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAvailableProductsForCombo, productIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCombo = `-- name: CreateCombo :one
INSERT INTO combos (name, slug, price_cents, image_url, starts_at, ends_at, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
`

type CreateComboParams struct {
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	PriceCents int64     `json:"priceCents"`
	ImageUrl   *string   `json:"imageUrl"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
	IsActive   bool      `json:"isActive"`
}

// CreateCombo
//
//	INSERT INTO combos (name, slug, price_cents, image_url, starts_at, ends_at, is_active)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
func (q *Queries) CreateCombo(ctx context.Context, arg CreateComboParams) (Combo, error) {
	row := q.db.QueryRow(ctx, createCombo,
		arg.Name,
		arg.Slug,
		arg.PriceCents,
		arg.ImageUrl,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComboItemsByComboID = `-- name: DeleteComboItemsByComboID :exec
DELETE FROM combo_items
WHERE combo_id = $1
`

// DeleteComboItemsByComboID
//
//	DELETE FROM combo_items
//	WHERE combo_id = $1
func (q *Queries) DeleteComboItemsByComboID(ctx context.Context, comboID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComboItemsByComboID, comboID)
	return err
}

const getComboByID = `-- name: GetComboByID :one
SELECT id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
FROM combos
WHERE id = $1
  AND deleted_at IS NULL
`

// GetComboByID
//
//	SELECT id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
//	FROM combos
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetComboByID(ctx context.Context, id uuid.UUID) (Combo, error) {
	row := q.db.QueryRow(ctx, getComboByID, id)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertComboItem = `-- name: InsertComboItem :exec
INSERT INTO combo_items (combo_id, product_id, quantity)
VALUES ($1, $2, $3)
`

type InsertComboItemParams struct {
	ComboID   uuid.UUID `json:"comboId"`
	ProductID uuid.UUID `json:"productId"`
	Quantity  int32     `json:"quantity"`
}

// InsertComboItem
//
//	INSERT INTO combo_items (combo_id, product_id, quantity)
//	VALUES ($1, $2, $3)
func (q *Queries) InsertComboItem(ctx context.Context, arg InsertComboItemParams) error {
	_, err := q.db.Exec(ctx, insertComboItem, arg.ComboID, arg.ProductID, arg.Quantity)
	return err
}

const listCatalogComboItemsByComboIDs = `-- name: ListCatalogComboItemsByComboIDs :many
SELECT
    ci.id,
    ci.combo_id,
    ci.product_id,
    ci.quantity,
    p.name AS product_name,
    p.slug AS product_slug,
    p.price_cents
FROM combo_items ci
INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
WHERE ci.combo_id = ANY($1::uuid[])
ORDER BY ci.combo_id ASC, p.name ASC
`

type ListCatalogComboItemsByComboIDsRow struct {
	ID          uuid.UUID `json:"id"`
	ComboID     uuid.UUID `json:"comboId"`
	ProductID   uuid.UUID `json:"productId"`
	Quantity    int32     `json:"quantity"`
	ProductName string    `json:"productName"`
	ProductSlug string    `json:"productSlug"`
	PriceCents  int64     `json:"priceCents"`
}

// ListCatalogComboItemsByComboIDs
//
//	SELECT
//	    ci.id,
//	    ci.combo_id,
//	    ci.product_id,
//	    ci.quantity,
//	    p.name AS product_name,
//	    p.slug AS product_slug,
//	    p.price_cents
//	FROM combo_items ci
//	INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
//	WHERE ci.combo_id = ANY($1::uuid[])
//	ORDER BY ci.combo_id ASC, p.name ASC
func (q *Queries) ListCatalogComboItemsByComboIDs(ctx context.Context, comboIds []uuid.UUID) ([]ListCatalogComboItemsByComboIDsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogComboItemsByComboIDs, comboIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogComboItemsByComboIDsRow{}
	for rows.Next() {
		var i ListCatalogComboItemsByComboIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ComboID,
			&i.ProductID,
			&i.Quantity,
			&i.ProductName,
			&i.ProductSlug,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComboItemsByComboID = `-- name: ListComboItemsByComboID :many
SELECT
    ci.id,
    ci.combo_id,
    ci.product_id,
    ci.quantity,
    p.name AS product_name,
    p.slug AS product_slug,
    p.price_cents
FROM combo_items ci
INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
WHERE ci.combo_id = $1
ORDER BY p.name ASC
`

type ListComboItemsByComboIDRow struct {
	ID          uuid.UUID `json:"id"`
	ComboID     uuid.UUID `json:"comboId"`
	ProductID   uuid.UUID `json:"productId"`
	Quantity    int32     `json:"quantity"`
	ProductName string    `json:"productName"`
	ProductSlug string    `json:"productSlug"`
	PriceCents  int64     `json:"priceCents"`
}

// ListComboItemsByComboID
//
//	SELECT
//	    ci.id,
//	    ci.combo_id,
//	    ci.product_id,
//	    ci.quantity,
//	    p.name AS product_name,
//	    p.slug AS product_slug,
//	    p.price_cents
//	FROM combo_items ci
//	INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
//	WHERE ci.combo_id = $1
//	ORDER BY p.name ASC
func (q *Queries) ListComboItemsByComboID(ctx context.Context, comboID uuid.UUID) ([]ListComboItemsByComboIDRow, error) {
	rows, err := q.db.Query(ctx, listComboItemsByComboID, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComboItemsByComboIDRow{}
	for rows.Next() {
		var i ListComboItemsByComboIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ComboID,
			&i.ProductID,
			&i.Quantity,
			&i.ProductName,
			&i.ProductSlug,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComboItemsByComboIDs = `-- name: ListComboItemsByComboIDs :many
SELECT
    ci.id,
    ci.combo_id,
    ci.product_id,
    ci.quantity,
    p.name AS product_name,
    p.slug AS product_slug,
    p.price_cents
FROM combo_items ci
INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
WHERE ci.combo_id = ANY($1::uuid[])
ORDER BY ci.combo_id ASC, p.name ASC
`

type ListComboItemsByComboIDsRow struct {
	ID          uuid.UUID `json:"id"`
	ComboID     uuid.UUID `json:"comboId"`
	ProductID   uuid.UUID `json:"productId"`
	Quantity    int32     `json:"quantity"`
	ProductName string    `json:"productName"`
	ProductSlug string    `json:"productSlug"`
	PriceCents  int64     `json:"priceCents"`
}

// ListComboItemsByComboIDs
//
//	SELECT
//	    ci.id,
//	    ci.combo_id,
//	    ci.product_id,
//	    ci.quantity,
//	    p.name AS product_name,
//	    p.slug AS product_slug,
//	    p.price_cents
//	FROM combo_items ci
//	INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
//	WHERE ci.combo_id = ANY($1::uuid[])
//	ORDER BY ci.combo_id ASC, p.name ASC
func (q *Queries) ListComboItemsByComboIDs(ctx context.Context, comboIds []uuid.UUID) ([]ListComboItemsByComboIDsRow, error) {
	rows, err := q.db.Query(ctx, listComboItemsByComboIDs, comboIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComboItemsByComboIDsRow{}
	for rows.Next() {
		var i ListComboItemsByComboIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ComboID,
			&i.ProductID,
			&i.Quantity,
			&i.ProductName,
			&i.ProductSlug,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListCombos = `-- name: ManagerListCombos :many
SELECT id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
FROM combos
WHERE deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3::text || '%'
    OR slug ILIKE '%' || $3::text || '%'
  )
ORDER BY starts_at DESC, name ASC
LIMIT $1 OFFSET $2
`

type ManagerListCombosParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

// ManagerListCombos
//
//	SELECT id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
//	FROM combos
//	WHERE deleted_at IS NULL
//	  AND (
//	    $3::text IS NULL
//	    OR name ILIKE '%' || $3::text || '%'
//	    OR slug ILIKE '%' || $3::text || '%'
//	  )
//	ORDER BY starts_at DESC, name ASC
//	LIMIT $1 OFFSET $2
func (q *Queries) ManagerListCombos(ctx context.Context, arg ManagerListCombosParams) ([]Combo, error) {
	rows, err := q.db.Query(ctx, managerListCombos, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Combo{}
	for rows.Next() {
		var i Combo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PriceCents,
			&i.ImageUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListCombosCount = `-- name: ManagerListCombosCount :one
SELECT COUNT(*)::bigint AS count
FROM combos
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR name ILIKE '%' || $1::text || '%'
    OR slug ILIKE '%' || $1::text || '%'
  )
`

// ManagerListCombosCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM combos
//	WHERE deleted_at IS NULL
//	  AND (
//	    $1::text IS NULL
//	    OR name ILIKE '%' || $1::text || '%'
//	    OR slug ILIKE '%' || $1::text || '%'
//	  )
func (q *Queries) ManagerListCombosCount(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, managerListCombosCount, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteCombo = `-- name: SoftDeleteCombo :execrows
UPDATE combos
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SoftDeleteCombo
//
//	UPDATE combos
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteCombo(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCombo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCombo = `-- name: UpdateCombo :one
UPDATE combos
SET name        = $2,
    slug        = $3,
    price_cents = $4,
    image_url   = $5,
    starts_at   = $6,
    ends_at     = $7,
    is_active   = $8,
    updated_at  = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
`

type UpdateComboParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Slug       string    `json:"slug"`
	PriceCents int64     `json:"priceCents"`
	ImageUrl   *string   `json:"imageUrl"`
	StartsAt   time.Time `json:"startsAt"`
	EndsAt     time.Time `json:"endsAt"`
	IsActive   bool      `json:"isActive"`
}

// UpdateCombo
//
//	UPDATE combos
//	SET name        = $2,
//	    slug        = $3,
//	    price_cents = $4,
//	    image_url   = $5,
//	    starts_at   = $6,
//	    ends_at     = $7,
//	    is_active   = $8,
//	    updated_at  = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	RETURNING id, name, slug, price_cents, image_url, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
func (q *Queries) UpdateCombo(ctx context.Context, arg UpdateComboParams) (Combo, error) {
	row := q.db.QueryRow(ctx, updateCombo,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.PriceCents,
		arg.ImageUrl,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i Combo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PriceCents,
		&i.ImageUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
