// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeCustomerConversations = `-- name: CloseCustomerConversations :exec
UPDATE conversations c
SET status = 'closed',
    unread_by_customer = 0,
    unread_by_staff = 0,
    updated_at = now()
FROM orders o
WHERE o.id = c.order_id
  AND o.user_id = $1::uuid
`

// Closes the customer's conversations as their account is erased: nothing in
// them is left to read.
//
//	UPDATE conversations c
//	SET status = 'closed',
//	    unread_by_customer = 0,
//	    unread_by_staff = 0,
//	    updated_at = now()
//	FROM orders o
//	WHERE o.id = c.order_id
//	  AND o.user_id = $1::uuid
func (q *Queries) CloseCustomerConversations(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeCustomerConversations, userID)
	return err
}

const createMessage = `-- name: CreateMessage :one
WITH created AS (
  INSERT INTO messages (conversation_id, author_id, author_role, body)
  VALUES ($1, $2, $3, $4)
  RETURNING id, author_id, author_role, body, created_at
)
SELECT
  created.id,
  created.author_role,
  created.body,
  created.created_at,
  sp.full_name AS author_name
FROM created
LEFT JOIN staff_profiles sp ON sp.user_id = created.author_id AND created.author_role = 'staff'::user_role
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversationId"`
	AuthorID       uuid.UUID `json:"authorId"`
	AuthorRole     UserRole  `json:"authorRole"`
	Body           string    `json:"body"`
}

type CreateMessageRow struct {
	ID         uuid.UUID `json:"id"`
	AuthorRole UserRole  `json:"authorRole"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"createdAt"`
	AuthorName *string   `json:"authorName"`
}

// Writes a message and returns it as a thread lists it.
//
//	WITH created AS (
//	  INSERT INTO messages (conversation_id, author_id, author_role, body)
//	  VALUES ($1, $2, $3, $4)
//	  RETURNING id, author_id, author_role, body, created_at
//	)
//	SELECT
//	  created.id,
//	  created.author_role,
//	  created.body,
//	  created.created_at,
//	  sp.full_name AS author_name
//	FROM created
//	LEFT JOIN staff_profiles sp ON sp.user_id = created.author_id AND created.author_role = 'staff'::user_role
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.AuthorID,
		arg.AuthorRole,
		arg.Body,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.AuthorRole,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const eraseCustomerMessages = `-- name: EraseCustomerMessages :exec
UPDATE messages m
SET body = '',
    deleted_at = now()
FROM conversations c
JOIN orders o ON o.id = c.order_id
WHERE m.conversation_id = c.id
  AND o.user_id = $1::uuid
  AND m.deleted_at IS NULL
`

// Erases the text of every message on the customer's orders, theirs and the
// counter's: what was said is about them.
//
//	UPDATE messages m
//	SET body = '',
//	    deleted_at = now()
//	FROM conversations c
//	JOIN orders o ON o.id = c.order_id
//	WHERE m.conversation_id = c.id
//	  AND o.user_id = $1::uuid
//	  AND m.deleted_at IS NULL
func (q *Queries) EraseCustomerMessages(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseCustomerMessages, userID)
	return err
}

const getConversationByOrderID = `-- name: GetConversationByOrderID :one
SELECT
  c.status,
  c.unread_by_customer,
  c.unread_by_staff,
  sp.full_name AS assigned_staff_name
FROM conversations c
LEFT JOIN staff_profiles sp ON sp.user_id = c.assigned_staff_id
WHERE c.order_id = $1
`

type GetConversationByOrderIDRow struct {
	Status            ConversationStatus `json:"status"`
	UnreadByCustomer  int32              `json:"unreadByCustomer"`
	UnreadByStaff     int32              `json:"unreadByStaff"`
	AssignedStaffName *string            `json:"assignedStaffName"`
}

// GetConversationByOrderID
//
//	SELECT
//	  c.status,
//	  c.unread_by_customer,
//	  c.unread_by_staff,
//	  sp.full_name AS assigned_staff_name
//	FROM conversations c
//	LEFT JOIN staff_profiles sp ON sp.user_id = c.assigned_staff_id
//	WHERE c.order_id = $1
func (q *Queries) GetConversationByOrderID(ctx context.Context, orderID uuid.UUID) (GetConversationByOrderIDRow, error) {
	row := q.db.QueryRow(ctx, getConversationByOrderID, orderID)
	var i GetConversationByOrderIDRow
	err := row.Scan(
		&i.Status,
		&i.UnreadByCustomer,
		&i.UnreadByStaff,
		&i.AssignedStaffName,
	)
	return i, err
}

const listMessagesByOrderID = `-- name: ListMessagesByOrderID :many
SELECT
  m.id,
  m.author_role,
  m.body,
  m.created_at,
  sp.full_name AS author_name
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN staff_profiles sp ON sp.user_id = m.author_id AND m.author_role = 'staff'::user_role
WHERE c.order_id = $1
  AND m.deleted_at IS NULL
  AND (
    $2::uuid IS NULL
    OR (m.created_at, m.id) < (
      SELECT b.created_at, b.id FROM messages b
      WHERE b.id = $2::uuid AND b.conversation_id = c.id
    )
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListMessagesByOrderIDParams struct {
	OrderID  uuid.UUID  `json:"orderId"`
	BeforeID *uuid.UUID `json:"beforeId"`
	Limit    int32      `json:"limit"`
}

type ListMessagesByOrderIDRow struct {
	ID         uuid.UUID `json:"id"`
	AuthorRole UserRole  `json:"authorRole"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"createdAt"`
	AuthorName *string   `json:"authorName"`
}

// A page of an order's messages, newest first: the latest, or those before
// the message before_id names. A staff message carries its writer's name.
//
//	SELECT
//	  m.id,
//	  m.author_role,
//	  m.body,
//	  m.created_at,
//	  sp.full_name AS author_name
//	FROM messages m
//	JOIN conversations c ON c.id = m.conversation_id
//	LEFT JOIN staff_profiles sp ON sp.user_id = m.author_id AND m.author_role = 'staff'::user_role
//	WHERE c.order_id = $1
//	  AND m.deleted_at IS NULL
//	  AND (
//	    $2::uuid IS NULL
//	    OR (m.created_at, m.id) < (
//	      SELECT b.created_at, b.id FROM messages b
//	      WHERE b.id = $2::uuid AND b.conversation_id = c.id
//	    )
//	  )
//	ORDER BY m.created_at DESC, m.id DESC
//	LIMIT $3
func (q *Queries) ListMessagesByOrderID(ctx context.Context, arg ListMessagesByOrderIDParams) ([]ListMessagesByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByOrderID, arg.OrderID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByOrderIDRow{}
	for rows.Next() {
		var i ListMessagesByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorRole,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByOrderIDs = `-- name: ListMessagesByOrderIDs :many
SELECT
  c.order_id,
  m.id,
  m.author_role,
  m.body,
  m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.order_id = ANY($1::uuid[])
  AND m.deleted_at IS NULL
ORDER BY c.order_id, m.created_at, m.id
`

type ListMessagesByOrderIDsRow struct {
	OrderID    uuid.UUID `json:"orderId"`
	ID         uuid.UUID `json:"id"`
	AuthorRole UserRole  `json:"authorRole"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"createdAt"`
}

// Every message on the orders given, oldest first, for a personal data export.
//
//	SELECT
//	  c.order_id,
//	  m.id,
//	  m.author_role,
//	  m.body,
//	  m.created_at
//	FROM messages m
//	JOIN conversations c ON c.id = m.conversation_id
//	WHERE c.order_id = ANY($1::uuid[])
//	  AND m.deleted_at IS NULL
//	ORDER BY c.order_id, m.created_at, m.id
func (q *Queries) ListMessagesByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]ListMessagesByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByOrderIDsRow{}
	for rows.Next() {
		var i ListMessagesByOrderIDsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.ID,
			&i.AuthorRole,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadByCustomer = `-- name: ListUnreadByCustomer :many
SELECT order_id, unread_by_customer
FROM conversations
WHERE order_id = ANY($1::uuid[])
  AND unread_by_customer > 0
`

type ListUnreadByCustomerRow struct {
	OrderID          uuid.UUID `json:"orderId"`
	UnreadByCustomer int32     `json:"unreadByCustomer"`
}

// What the customer has not read yet on each of the orders given.
//
//	SELECT order_id, unread_by_customer
//	FROM conversations
//	WHERE order_id = ANY($1::uuid[])
//	  AND unread_by_customer > 0
func (q *Queries) ListUnreadByCustomer(ctx context.Context, orderIds []uuid.UUID) ([]ListUnreadByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listUnreadByCustomer, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnreadByCustomerRow{}
	for rows.Next() {
		var i ListUnreadByCustomerRow
		if err := rows.Scan(&i.OrderID, &i.UnreadByCustomer); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationReadByCustomer = `-- name: MarkConversationReadByCustomer :execrows
UPDATE conversations
SET unread_by_customer = 0,
    updated_at = now()
WHERE order_id = $1
  AND unread_by_customer > 0
`

// MarkConversationReadByCustomer
//
//	UPDATE conversations
//	SET unread_by_customer = 0,
//	    updated_at = now()
//	WHERE order_id = $1
//	  AND unread_by_customer > 0
func (q *Queries) MarkConversationReadByCustomer(ctx context.Context, orderID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationReadByCustomer, orderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConversationReadByStaff = `-- name: MarkConversationReadByStaff :execrows
UPDATE conversations
SET unread_by_staff = 0,
    updated_at = now()
WHERE order_id = $1
  AND unread_by_staff > 0
`

// MarkConversationReadByStaff
//
//	UPDATE conversations
//	SET unread_by_staff = 0,
//	    updated_at = now()
//	WHERE order_id = $1
//	  AND unread_by_staff > 0
func (q *Queries) MarkConversationReadByStaff(ctx context.Context, orderID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markConversationReadByStaff, orderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openConversationForCustomerMessage = `-- name: OpenConversationForCustomerMessage :one
INSERT INTO conversations (order_id, unread_by_staff, last_message_at)
VALUES ($1, 1, now())
ON CONFLICT (order_id) DO UPDATE
SET status = 'open',
    unread_by_staff = conversations.unread_by_staff + 1,
    unread_by_customer = 0,
    last_message_at = GREATEST(conversations.last_message_at, now()),
    updated_at = now()
RETURNING id
`

// Records that the customer wrote about the order: the conversation starts,
// or opens again, the counter has one more message to read, and the customer
// has read everything before their own.
//
//	INSERT INTO conversations (order_id, unread_by_staff, last_message_at)
//	VALUES ($1, 1, now())
//	ON CONFLICT (order_id) DO UPDATE
//	SET status = 'open',
//	    unread_by_staff = conversations.unread_by_staff + 1,
//	    unread_by_customer = 0,
//	    last_message_at = GREATEST(conversations.last_message_at, now()),
//	    updated_at = now()
//	RETURNING id
func (q *Queries) OpenConversationForCustomerMessage(ctx context.Context, orderID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, openConversationForCustomerMessage, orderID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const openConversationForStaffMessage = `-- name: OpenConversationForStaffMessage :one
INSERT INTO conversations (order_id, assigned_staff_id, unread_by_customer, last_message_at)
VALUES ($1, $2, 1, now())
ON CONFLICT (order_id) DO UPDATE
SET status = 'open',
    assigned_staff_id = EXCLUDED.assigned_staff_id,
    unread_by_customer = conversations.unread_by_customer + 1,
    unread_by_staff = 0,
    last_message_at = GREATEST(conversations.last_message_at, now()),
    updated_at = now()
RETURNING id
`

type OpenConversationForStaffMessageParams struct {
	OrderID uuid.UUID  `json:"orderId"`
	StaffID *uuid.UUID `json:"staffId"`
}

// Records that staff wrote about the order: the conversation starts, or opens
// again, and passes to the writer; the customer has one more message to read,
// and the counter has read everything before it.
//
//	INSERT INTO conversations (order_id, assigned_staff_id, unread_by_customer, last_message_at)
//	VALUES ($1, $2, 1, now())
//	ON CONFLICT (order_id) DO UPDATE
//	SET status = 'open',
//	    assigned_staff_id = EXCLUDED.assigned_staff_id,
//	    unread_by_customer = conversations.unread_by_customer + 1,
//	    unread_by_staff = 0,
//	    last_message_at = GREATEST(conversations.last_message_at, now()),
//	    updated_at = now()
//	RETURNING id
func (q *Queries) OpenConversationForStaffMessage(ctx context.Context, arg OpenConversationForStaffMessageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, openConversationForStaffMessage, arg.OrderID, arg.StaffID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setConversationStatus = `-- name: SetConversationStatus :execrows
UPDATE conversations
SET status = $1,
    unread_by_staff = CASE WHEN $1 = 'closed'::conversation_status THEN 0 ELSE unread_by_staff END,
    updated_at = now()
WHERE order_id = $2
  AND status <> $1
`

type SetConversationStatusParams struct {
	Status  ConversationStatus `json:"status"`
	OrderID uuid.UUID          `json:"orderId"`
}

// Resolving a conversation reads it for the counter: nothing in it waits on them.
//
//	UPDATE conversations
//	SET status = $1,
//	    unread_by_staff = CASE WHEN $1 = 'closed'::conversation_status THEN 0 ELSE unread_by_staff END,
//	    updated_at = now()
//	WHERE order_id = $2
//	  AND status <> $1
func (q *Queries) SetConversationStatus(ctx context.Context, arg SetConversationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setConversationStatus, arg.Status, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staffConversationCounts = `-- name: StaffConversationCounts :one
SELECT
  count(*) FILTER (WHERE c.status = 'open'::conversation_status)::bigint AS open_count,
  count(*) FILTER (WHERE c.unread_by_staff > 0)::bigint AS unread_count
FROM conversations c
JOIN orders o ON o.id = c.order_id
JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
`

type StaffConversationCountsRow struct {
	OpenCount   int64 `json:"openCount"`
	UnreadCount int64 `json:"unreadCount"`
}

// How many conversations wait on the counter: open ones, and those holding
// messages nobody at the counter has read.
//
//	SELECT
//	  count(*) FILTER (WHERE c.status = 'open'::conversation_status)::bigint AS open_count,
//	  count(*) FILTER (WHERE c.unread_by_staff > 0)::bigint AS unread_count
//	FROM conversations c
//	JOIN orders o ON o.id = c.order_id
//	JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
func (q *Queries) StaffConversationCounts(ctx context.Context) (StaffConversationCountsRow, error) {
	row := q.db.QueryRow(ctx, staffConversationCounts)
	var i StaffConversationCountsRow
	err := row.Scan(&i.OpenCount, &i.UnreadCount)
	return i, err
}

const staffListConversations = `-- name: StaffListConversations :many
SELECT
  c.order_id,
  o.code AS order_code,
  c.status,
  c.unread_by_staff,
  c.last_message_at,
  cp.display_name AS customer_name,
  u.email AS customer_email,
  left(last.body, 200)::text AS last_body
FROM conversations c
JOIN orders o ON o.id = c.order_id
JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
JOIN LATERAL (
  SELECT m.body
  FROM messages m
  WHERE m.conversation_id = c.id AND m.deleted_at IS NULL
  ORDER BY m.created_at DESC, m.id DESC
  LIMIT 1
) last ON true
WHERE (
    $1::conversation_status IS NULL
    OR c.status = $1::conversation_status
  )
ORDER BY c.last_message_at DESC, c.id DESC
LIMIT $3 OFFSET $2
`

type StaffListConversationsParams struct {
	Status *ConversationStatus `json:"status"`
	Offset int32               `json:"offset"`
	Limit  int32               `json:"limit"`
}

type StaffListConversationsRow struct {
	OrderID       uuid.UUID          `json:"orderId"`
	OrderCode     string             `json:"orderCode"`
	Status        ConversationStatus `json:"status"`
	UnreadByStaff int32              `json:"unreadByStaff"`
	LastMessageAt time.Time          `json:"lastMessageAt"`
	CustomerName  *string            `json:"customerName"`
	CustomerEmail string             `json:"customerEmail"`
	LastBody      string             `json:"lastBody"`
}

// The counter's inbox, latest message first: each conversation with its
// order, its customer and a preview of its last message. A customer whose
// account is closed is not shown.
//
//	SELECT
//	  c.order_id,
//	  o.code AS order_code,
//	  c.status,
//	  c.unread_by_staff,
//	  c.last_message_at,
//	  cp.display_name AS customer_name,
//	  u.email AS customer_email,
//	  left(last.body, 200)::text AS last_body
//	FROM conversations c
//	JOIN orders o ON o.id = c.order_id
//	JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	JOIN LATERAL (
//	  SELECT m.body
//	  FROM messages m
//	  WHERE m.conversation_id = c.id AND m.deleted_at IS NULL
//	  ORDER BY m.created_at DESC, m.id DESC
//	  LIMIT 1
//	) last ON true
//	WHERE (
//	    $1::conversation_status IS NULL
//	    OR c.status = $1::conversation_status
//	  )
//	ORDER BY c.last_message_at DESC, c.id DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) StaffListConversations(ctx context.Context, arg StaffListConversationsParams) ([]StaffListConversationsRow, error) {
	rows, err := q.db.Query(ctx, staffListConversations, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffListConversationsRow{}
	for rows.Next() {
		var i StaffListConversationsRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderCode,
			&i.Status,
			&i.UnreadByStaff,
			&i.LastMessageAt,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.LastBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffListConversationsCount = `-- name: StaffListConversationsCount :one
SELECT count(*)::bigint
FROM conversations c
JOIN orders o ON o.id = c.order_id
JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (
    $1::conversation_status IS NULL
    OR c.status = $1::conversation_status
  )
`

// StaffListConversationsCount
//
//	SELECT count(*)::bigint
//	FROM conversations c
//	JOIN orders o ON o.id = c.order_id
//	JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (
//	    $1::conversation_status IS NULL
//	    OR c.status = $1::conversation_status
//	  )
func (q *Queries) StaffListConversationsCount(ctx context.Context, status *ConversationStatus) (int64, error) {
	row := q.db.QueryRow(ctx, staffListConversationsCount, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
