// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_profile.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO customer_profiles (user_id, display_name, phone)
VALUES ($1, $2, $3)
RETURNING user_id, display_name, phone, created_at, updated_at
`

type CreateCustomerProfileParams struct {
	UserID      uuid.UUID      `db:"user_id" json:"userId"`
	DisplayName sql.NullString `db:"display_name" json:"displayName"`
	Phone       sql.NullString `db:"phone" json:"phone"`
}

// CreateCustomerProfile
//
//	INSERT INTO customer_profiles (user_id, display_name, phone)
//	VALUES ($1, $2, $3)
//	RETURNING user_id, display_name, phone, created_at, updated_at
func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, createCustomerProfile, arg.UserID, arg.DisplayName, arg.Phone)
	var i CustomerProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerProfileByUserID = `-- name: DeleteCustomerProfileByUserID :execrows
DELETE FROM customer_profiles
WHERE user_id = $1
`

// DeleteCustomerProfileByUserID
//
//	DELETE FROM customer_profiles
//	WHERE user_id = $1
func (q *Queries) DeleteCustomerProfileByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCustomerProfileByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCustomerProfileByUserID = `-- name: GetCustomerProfileByUserID :one
SELECT user_id, display_name, phone, created_at, updated_at
FROM customer_profiles
WHERE user_id = $1
`

// GetCustomerProfileByUserID
//
//	SELECT user_id, display_name, phone, created_at, updated_at
//	FROM customer_profiles
//	WHERE user_id = $1
func (q *Queries) GetCustomerProfileByUserID(ctx context.Context, userID uuid.UUID) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, getCustomerProfileByUserID, userID)
	var i CustomerProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerProfileByUserID = `-- name: UpdateCustomerProfileByUserID :one
UPDATE customer_profiles
SET display_name = $2,
    phone = $3,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, display_name, phone, created_at, updated_at
`

type UpdateCustomerProfileByUserIDParams struct {
	UserID      uuid.UUID      `db:"user_id" json:"userId"`
	DisplayName sql.NullString `db:"display_name" json:"displayName"`
	Phone       sql.NullString `db:"phone" json:"phone"`
}

// UpdateCustomerProfileByUserID
//
//	UPDATE customer_profiles
//	SET display_name = $2,
//	    phone = $3,
//	    updated_at = now()
//	WHERE user_id = $1
//	RETURNING user_id, display_name, phone, created_at, updated_at
func (q *Queries) UpdateCustomerProfileByUserID(ctx context.Context, arg UpdateCustomerProfileByUserIDParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateCustomerProfileByUserID, arg.UserID, arg.DisplayName, arg.Phone)
	var i CustomerProfile
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
