// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discount_code.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDiscountCode = `-- name: CreateDiscountCode :one
INSERT INTO discount_codes (
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    starts_at,
    ends_at,
    is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type CreateDiscountCodeParams struct {
	Code          string        `db:"code" json:"code"`
	DiscountType  DiscountType  `db:"discount_type" json:"discountType"`
	Value         int64         `db:"value" json:"value"`
	MinOrderCents sql.NullInt64 `db:"min_order_cents" json:"minOrderCents"`
	MaxUses       sql.NullInt32 `db:"max_uses" json:"maxUses"`
	StartsAt      time.Time     `db:"starts_at" json:"startsAt"`
	EndsAt        time.Time     `db:"ends_at" json:"endsAt"`
	IsActive      bool          `db:"is_active" json:"isActive"`
}

// CreateDiscountCode
//
//	INSERT INTO discount_codes (
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    starts_at,
//	    ends_at,
//	    is_active
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
func (q *Queries) CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, createDiscountCode,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MinOrderCents,
		arg.MaxUses,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDiscountCodeByCode = `-- name: GetDiscountCodeByCode :one
SELECT
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM discount_codes
WHERE code = $1
  AND deleted_at IS NULL
`

// GetDiscountCodeByCode
//
//	SELECT
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
//	FROM discount_codes
//	WHERE code = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetDiscountCodeByCode(ctx context.Context, code string) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByCode, code)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDiscountCodeByID = `-- name: GetDiscountCodeByID :one
SELECT
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM discount_codes
WHERE id = $1
  AND deleted_at IS NULL
`

// GetDiscountCodeByID
//
//	SELECT
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
//	FROM discount_codes
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetDiscountCodeByID(ctx context.Context, id uuid.UUID) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, getDiscountCodeByID, id)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementDiscountCodeUsedCount = `-- name: IncrementDiscountCodeUsedCount :one
UPDATE discount_codes
SET used_count = used_count + 1,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
  AND (max_uses IS NULL OR used_count < max_uses)
RETURNING
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

// IncrementDiscountCodeUsedCount
//
//	UPDATE discount_codes
//	SET used_count = used_count + 1,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	  AND (max_uses IS NULL OR used_count < max_uses)
//	RETURNING
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
func (q *Queries) IncrementDiscountCodeUsedCount(ctx context.Context, id uuid.UUID) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, incrementDiscountCodeUsedCount, id)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const managerListDiscountCodes = `-- name: ManagerListDiscountCodes :many
SELECT
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM discount_codes
WHERE deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR code ILIKE '%' || $3::text || '%'
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ManagerListDiscountCodesParams struct {
	Limit  int32          `db:"limit" json:"limit"`
	Offset int32          `db:"offset" json:"offset"`
	Search sql.NullString `db:"search" json:"search"`
}

// ManagerListDiscountCodes
//
//	SELECT
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
//	FROM discount_codes
//	WHERE deleted_at IS NULL
//	  AND (
//	    $3::text IS NULL
//	    OR code ILIKE '%' || $3::text || '%'
//	  )
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ManagerListDiscountCodes(ctx context.Context, arg ManagerListDiscountCodesParams) ([]DiscountCode, error) {
	rows, err := q.db.QueryContext(ctx, managerListDiscountCodes, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiscountCode{}
	for rows.Next() {
		var i DiscountCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountType,
			&i.Value,
			&i.MinOrderCents,
			&i.MaxUses,
			&i.UsedCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListDiscountCodesCount = `-- name: ManagerListDiscountCodesCount :one
SELECT COUNT(*)::bigint AS count
FROM discount_codes
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR code ILIKE '%' || $1::text || '%'
  )
`

// ManagerListDiscountCodesCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM discount_codes
//	WHERE deleted_at IS NULL
//	  AND (
//	    $1::text IS NULL
//	    OR code ILIKE '%' || $1::text || '%'
//	  )
func (q *Queries) ManagerListDiscountCodesCount(ctx context.Context, search sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, managerListDiscountCodesCount, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteDiscountCode = `-- name: SoftDeleteDiscountCode :execrows
UPDATE discount_codes
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SoftDeleteDiscountCode
//
//	UPDATE discount_codes
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteDiscountCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteDiscountCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDiscountCode = `-- name: UpdateDiscountCode :one
UPDATE discount_codes
SET code            = $2,
    discount_type   = $3,
    value           = $4,
    min_order_cents = $5,
    max_uses        = $6,
    starts_at       = $7,
    ends_at         = $8,
    is_active       = $9,
    updated_at      = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    discount_type,
    value,
    min_order_cents,
    max_uses,
    used_count,
    starts_at,
    ends_at,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type UpdateDiscountCodeParams struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	Code          string        `db:"code" json:"code"`
	DiscountType  DiscountType  `db:"discount_type" json:"discountType"`
	Value         int64         `db:"value" json:"value"`
	MinOrderCents sql.NullInt64 `db:"min_order_cents" json:"minOrderCents"`
	MaxUses       sql.NullInt32 `db:"max_uses" json:"maxUses"`
	StartsAt      time.Time     `db:"starts_at" json:"startsAt"`
	EndsAt        time.Time     `db:"ends_at" json:"endsAt"`
	IsActive      bool          `db:"is_active" json:"isActive"`
}

// UpdateDiscountCode
//
//	UPDATE discount_codes
//	SET code            = $2,
//	    discount_type   = $3,
//	    value           = $4,
//	    min_order_cents = $5,
//	    max_uses        = $6,
//	    starts_at       = $7,
//	    ends_at         = $8,
//	    is_active       = $9,
//	    updated_at      = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	RETURNING
//	    id,
//	    code,
//	    discount_type,
//	    value,
//	    min_order_cents,
//	    max_uses,
//	    used_count,
//	    starts_at,
//	    ends_at,
//	    is_active,
//	    created_at,
//	    updated_at,
//	    deleted_at
func (q *Queries) UpdateDiscountCode(ctx context.Context, arg UpdateDiscountCodeParams) (DiscountCode, error) {
	row := q.db.QueryRowContext(ctx, updateDiscountCode,
		arg.ID,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MinOrderCents,
		arg.MaxUses,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i DiscountCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MinOrderCents,
		&i.MaxUses,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
