// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DiscountType string

const (
	DiscountTypePercent    DiscountType = "percent"
	DiscountTypeFixedCents DiscountType = "fixed_cents"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discountType"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type LineType string

const (
	LineTypeProduct LineType = "product"
	LineTypeCombo   LineType = "combo"
)

func (e *LineType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LineType(s)
	case string:
		*e = LineType(s)
	default:
		return fmt.Errorf("unsupported scan type for LineType: %T", src)
	}
	return nil
}

type NullLineType struct {
	LineType LineType `json:"lineType"`
	Valid    bool     `json:"valid"` // Valid is true if LineType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLineType) Scan(value interface{}) error {
	if value == nil {
		ns.LineType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LineType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLineType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LineType), nil
}

type OrderStatus string

const (
	OrderStatusPending         OrderStatus = "pending"
	OrderStatusConfirmed       OrderStatus = "confirmed"
	OrderStatusInProduction    OrderStatus = "in_production"
	OrderStatusReady           OrderStatus = "ready"
	OrderStatusFulfilled       OrderStatus = "fulfilled"
	OrderStatusCancelled       OrderStatus = "cancelled"
	OrderStatusAwaitingPayment OrderStatus = "awaiting_payment"
	OrderStatusExpired         OrderStatus = "expired"
	OrderStatusNoShow          OrderStatus = "no_show"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"orderStatus"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type OrderType string

const (
	OrderTypeInstant  OrderType = "instant"
	OrderTypePreOrder OrderType = "pre_order"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType `json:"orderType"`
	Valid     bool      `json:"valid"` // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

type PaymentProvider string

const (
	PaymentProviderPaypal PaymentProvider = "paypal"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider `json:"paymentProvider"`
	Valid           bool            `json:"valid"` // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type PaymentStatus string

const (
	PaymentStatusCreated  PaymentStatus = "created"
	PaymentStatusPending  PaymentStatus = "pending"
	PaymentStatusCaptured PaymentStatus = "captured"
	PaymentStatusDenied   PaymentStatus = "denied"
	PaymentStatusRefunded PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"paymentStatus"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Station string

const (
	StationKitchen Station = "kitchen"
	StationCounter Station = "counter"
)

func (e *Station) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Station(s)
	case string:
		*e = Station(s)
	default:
		return fmt.Errorf("unsupported scan type for Station: %T", src)
	}
	return nil
}

type NullStation struct {
	Station Station `json:"station"`
	Valid   bool    `json:"valid"` // Valid is true if Station is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStation) Scan(value interface{}) error {
	if value == nil {
		ns.Station, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Station.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Station), nil
}

type TicketStatus string

const (
	TicketStatusQueued     TicketStatus = "queued"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusReady      TicketStatus = "ready"
	TicketStatusCancelled  TicketStatus = "cancelled"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticketStatus"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleCustomer UserRole = "customer"
	UserRoleStaff    UserRole = "staff"
	UserRoleBaker    UserRole = "baker"
	UserRoleManager  UserRole = "manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserTokenPurpose string

const (
	UserTokenPurposeVerifyEmail   UserTokenPurpose = "verify_email"
	UserTokenPurposeResetPassword UserTokenPurpose = "reset_password"
)

func (e *UserTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserTokenPurpose(s)
	case string:
		*e = UserTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for UserTokenPurpose: %T", src)
	}
	return nil
}

type NullUserTokenPurpose struct {
	UserTokenPurpose UserTokenPurpose `json:"userTokenPurpose"`
	Valid            bool             `json:"valid"` // Valid is true if UserTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.UserTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserTokenPurpose), nil
}

type AdminProfile struct {
	UserID    uuid.UUID `json:"userId"`
	FullName  string    `json:"fullName"`
	Phone     *string   `json:"phone"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Cart struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"userId"`
	DiscountCodeID *uuid.UUID `json:"discountCodeId"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
}

type CartItem struct {
	ID            uuid.UUID       `json:"id"`
	CartID        uuid.UUID       `json:"cartId"`
	LineType      LineType        `json:"lineType"`
	ProductID     *uuid.UUID      `json:"productId"`
	ComboID       *uuid.UUID      `json:"comboId"`
	Quantity      int32           `json:"quantity"`
	Configuration json.RawMessage `json:"configuration"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type Category struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	SortOrder int32      `json:"sortOrder"`
	IsActive  bool       `json:"isActive"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
	Station   Station    `json:"station"`
}

type Combo struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Slug       string     `json:"slug"`
	PriceCents int64      `json:"priceCents"`
	ImageUrl   *string    `json:"imageUrl"`
	StartsAt   time.Time  `json:"startsAt"`
	EndsAt     time.Time  `json:"endsAt"`
	IsActive   bool       `json:"isActive"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	DeletedAt  *time.Time `json:"deletedAt"`
}

type CustomerProfile struct {
	UserID      uuid.UUID `json:"userId"`
	DisplayName *string   `json:"displayName"`
	Phone       *string   `json:"phone"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type DiscountCode struct {
	ID                 uuid.UUID    `json:"id"`
	Code               string       `json:"code"`
	DiscountType       DiscountType `json:"discountType"`
	Value              int64        `json:"value"`
	MinOrderCents      *int64       `json:"minOrderCents"`
	MaxUses            *int32       `json:"maxUses"`
	MaxUsesPerCustomer *int32       `json:"maxUsesPerCustomer"`
	MaxDiscountCents   *int64       `json:"maxDiscountCents"`
	UsedCount          int32        `json:"usedCount"`
	StartsAt           time.Time    `json:"startsAt"`
	EndsAt             time.Time    `json:"endsAt"`
	IsActive           bool         `json:"isActive"`
	CreatedAt          time.Time    `json:"createdAt"`
	UpdatedAt          time.Time    `json:"updatedAt"`
	DeletedAt          *time.Time   `json:"deletedAt"`
}

type Order struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"userId"`
	Status               OrderStatus `json:"status"`
	SubtotalCents        int64       `json:"subtotalCents"`
	DiscountCents        int64       `json:"discountCents"`
	TotalCents           int64       `json:"totalCents"`
	DiscountCodeID       *uuid.UUID  `json:"discountCodeId"`
	DiscountCodeSnapshot *string     `json:"discountCodeSnapshot"`
	PickupAt             *time.Time  `json:"pickupAt"`
	CreatedAt            time.Time   `json:"createdAt"`
	UpdatedAt            time.Time   `json:"updatedAt"`
	Code                 string      `json:"code"`
	OrderType            OrderType   `json:"orderType"`
	TermsAcceptedAt      *time.Time  `json:"termsAcceptedAt"`
	TermsVersion         *string     `json:"termsVersion"`
	CheckoutKey          *uuid.UUID  `json:"checkoutKey"`
	PaymentDueAt         *time.Time  `json:"paymentDueAt"`
}

type OrderDayCounter struct {
	Day        time.Time `json:"day"`
	LastNumber int32     `json:"lastNumber"`
}

type OrderItem struct {
	ID             uuid.UUID       `json:"id"`
	OrderID        uuid.UUID       `json:"orderId"`
	LineType       LineType        `json:"lineType"`
	ProductID      *uuid.UUID      `json:"productId"`
	ComboID        *uuid.UUID      `json:"comboId"`
	Configuration  json.RawMessage `json:"configuration"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	Quantity       int32           `json:"quantity"`
	UnitPriceCents int64           `json:"unitPriceCents"`
	LineTotalCents int64           `json:"lineTotalCents"`
	CreatedAt      time.Time       `json:"createdAt"`
}

type OrderTicket struct {
	ID        uuid.UUID    `json:"id"`
	OrderID   uuid.UUID    `json:"orderId"`
	Station   Station      `json:"station"`
	Status    TicketStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type Payment struct {
	ID                uuid.UUID       `json:"id"`
	OrderID           uuid.UUID       `json:"orderId"`
	Provider          PaymentProvider `json:"provider"`
	ProviderOrderID   string          `json:"providerOrderId"`
	ApproveUrl        string          `json:"approveUrl"`
	Status            PaymentStatus   `json:"status"`
	CaptureID         *string         `json:"captureId"`
	AmountCents       int64           `json:"amountCents"`
	Currency          string          `json:"currency"`
	CapturedAt        *time.Time      `json:"capturedAt"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
	RefundRequestedAt *time.Time      `json:"refundRequestedAt"`
	RefundID          *string         `json:"refundId"`
	RefundedAt        *time.Time      `json:"refundedAt"`
}

type Product struct {
	ID              uuid.UUID  `json:"id"`
	CategoryID      uuid.UUID  `json:"categoryId"`
	Name            string     `json:"name"`
	Slug            string     `json:"slug"`
	Description     *string    `json:"description"`
	PriceCents      int64      `json:"priceCents"`
	IsActive        bool       `json:"isActive"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	DeletedAt       *time.Time `json:"deletedAt"`
	LeadTimeMinutes int32      `json:"leadTimeMinutes"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
	SortOrder int16     `json:"sortOrder"`
	ImageUrl  string    `json:"imageUrl"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type StaffProfile struct {
	UserID       uuid.UUID `json:"userId"`
	FullName     string    `json:"fullName"`
	Phone        *string   `json:"phone"`
	EmployeeCode string    `json:"employeeCode"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}
