// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleCustomer UserRole = "customer"
	UserRoleStaff    UserRole = "staff"
	UserRoleBaker    UserRole = "baker"
	UserRoleManager  UserRole = "manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AdminProfile struct {
	UserID    uuid.UUID      `db:"user_id" json:"userId"`
	FullName  string         `db:"full_name" json:"fullName"`
	Phone     sql.NullString `db:"phone" json:"phone"`
	CreatedAt time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time      `db:"updated_at" json:"updatedAt"`
}

type CustomerProfile struct {
	UserID      uuid.UUID      `db:"user_id" json:"userId"`
	DisplayName sql.NullString `db:"display_name" json:"displayName"`
	Phone       sql.NullString `db:"phone" json:"phone"`
	CreatedAt   time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updatedAt"`
}

type StaffProfile struct {
	UserID       uuid.UUID      `db:"user_id" json:"userId"`
	FullName     string         `db:"full_name" json:"fullName"`
	Phone        sql.NullString `db:"phone" json:"phone"`
	EmployeeCode string         `db:"employee_code" json:"employeeCode"`
	HireDate     time.Time      `db:"hire_date" json:"hireDate"`
	Shift        string         `db:"shift" json:"shift"`
	CreatedAt    time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID                 uuid.UUID    `db:"id" json:"id"`
	Email              string       `db:"email" json:"email"`
	PasswordHash       string       `db:"password_hash" json:"passwordHash"`
	Role               UserRole     `db:"role" json:"role"`
	EmailVerifiedAt    sql.NullTime `db:"email_verified_at" json:"emailVerifiedAt"`
	MustChangePassword bool         `db:"must_change_password" json:"mustChangePassword"`
	CreatedAt          time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt          time.Time    `db:"updated_at" json:"updatedAt"`
	DeletedAt          sql.NullTime `db:"deleted_at" json:"deletedAt"`
}
