// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DiscountType string

const (
	DiscountTypePercent    DiscountType = "percent"
	DiscountTypeFixedCents DiscountType = "fixed_cents"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discountType"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleCustomer UserRole = "customer"
	UserRoleStaff    UserRole = "staff"
	UserRoleBaker    UserRole = "baker"
	UserRoleManager  UserRole = "manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"userRole"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AdminProfile struct {
	UserID    uuid.UUID      `db:"user_id" json:"userId"`
	FullName  string         `db:"full_name" json:"fullName"`
	Phone     sql.NullString `db:"phone" json:"phone"`
	CreatedAt time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time      `db:"updated_at" json:"updatedAt"`
}

type Category struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Slug      string       `db:"slug" json:"slug"`
	SortOrder int32        `db:"sort_order" json:"sortOrder"`
	IsActive  bool         `db:"is_active" json:"isActive"`
	CreatedAt time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time    `db:"updated_at" json:"updatedAt"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deletedAt"`
}

type Combo struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	Slug       string       `db:"slug" json:"slug"`
	PriceCents int64        `db:"price_cents" json:"priceCents"`
	StartsAt   time.Time    `db:"starts_at" json:"startsAt"`
	EndsAt     time.Time    `db:"ends_at" json:"endsAt"`
	IsActive   bool         `db:"is_active" json:"isActive"`
	CreatedAt  time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt  time.Time    `db:"updated_at" json:"updatedAt"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deletedAt"`
}

type CustomerProfile struct {
	UserID      uuid.UUID      `db:"user_id" json:"userId"`
	DisplayName sql.NullString `db:"display_name" json:"displayName"`
	Phone       sql.NullString `db:"phone" json:"phone"`
	CreatedAt   time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updatedAt"`
}

type DiscountCode struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	Code          string        `db:"code" json:"code"`
	DiscountType  DiscountType  `db:"discount_type" json:"discountType"`
	Value         int64         `db:"value" json:"value"`
	MinOrderCents sql.NullInt64 `db:"min_order_cents" json:"minOrderCents"`
	MaxUses       sql.NullInt32 `db:"max_uses" json:"maxUses"`
	UsedCount     int32         `db:"used_count" json:"usedCount"`
	StartsAt      time.Time     `db:"starts_at" json:"startsAt"`
	EndsAt        time.Time     `db:"ends_at" json:"endsAt"`
	IsActive      bool          `db:"is_active" json:"isActive"`
	CreatedAt     time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time     `db:"updated_at" json:"updatedAt"`
	DeletedAt     sql.NullTime  `db:"deleted_at" json:"deletedAt"`
}

type Product struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CategoryID  uuid.UUID      `db:"category_id" json:"categoryId"`
	Name        string         `db:"name" json:"name"`
	Slug        string         `db:"slug" json:"slug"`
	Description sql.NullString `db:"description" json:"description"`
	PriceCents  int64          `db:"price_cents" json:"priceCents"`
	IsAvailable bool           `db:"is_available" json:"isAvailable"`
	ImageUrl    sql.NullString `db:"image_url" json:"imageUrl"`
	CreatedAt   time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updatedAt"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deletedAt"`
}

type StaffProfile struct {
	UserID       uuid.UUID      `db:"user_id" json:"userId"`
	FullName     string         `db:"full_name" json:"fullName"`
	Phone        sql.NullString `db:"phone" json:"phone"`
	EmployeeCode string         `db:"employee_code" json:"employeeCode"`
	CreatedAt    time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID                 uuid.UUID    `db:"id" json:"id"`
	Email              string       `db:"email" json:"email"`
	PasswordHash       string       `db:"password_hash" json:"passwordHash"`
	Role               UserRole     `db:"role" json:"role"`
	EmailVerifiedAt    sql.NullTime `db:"email_verified_at" json:"emailVerifiedAt"`
	MustChangePassword bool         `db:"must_change_password" json:"mustChangePassword"`
	CreatedAt          time.Time    `db:"created_at" json:"createdAt"`
	UpdatedAt          time.Time    `db:"updated_at" json:"updatedAt"`
	DeletedAt          sql.NullTime `db:"deleted_at" json:"deletedAt"`
}
