// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlcgen

import (
	"context"
	"time"
)

const operationsActiveOrders = `-- name: OperationsActiveOrders :one
SELECT
  count(*) FILTER (WHERE o.status = 'pending'::order_status)::bigint AS pending,
  count(*) FILTER (WHERE o.status = 'confirmed'::order_status)::bigint AS confirmed,
  count(*) FILTER (WHERE o.status = 'in_production'::order_status)::bigint AS in_production,
  count(*) FILTER (WHERE o.status = 'ready'::order_status)::bigint AS ready
FROM orders o
LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
  AND o.status IN ('pending', 'confirmed', 'in_production', 'ready')
`

type OperationsActiveOrdersRow struct {
	Pending      int64 `json:"pending"`
	Confirmed    int64 `json:"confirmed"`
	InProduction int64 `json:"inProduction"`
	Ready        int64 `json:"ready"`
}

// The orders the bakery still has to make or hand over, by status; like the
// counter's and the kitchen's lists, none of a closed account.
//
//	SELECT
//	  count(*) FILTER (WHERE o.status = 'pending'::order_status)::bigint AS pending,
//	  count(*) FILTER (WHERE o.status = 'confirmed'::order_status)::bigint AS confirmed,
//	  count(*) FILTER (WHERE o.status = 'in_production'::order_status)::bigint AS in_production,
//	  count(*) FILTER (WHERE o.status = 'ready'::order_status)::bigint AS ready
//	FROM orders o
//	LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
//	  AND o.status IN ('pending', 'confirmed', 'in_production', 'ready')
func (q *Queries) OperationsActiveOrders(ctx context.Context) (OperationsActiveOrdersRow, error) {
	row := q.db.QueryRow(ctx, operationsActiveOrders)
	var i OperationsActiveOrdersRow
	err := row.Scan(
		&i.Pending,
		&i.Confirmed,
		&i.InProduction,
		&i.Ready,
	)
	return i, err
}

const operationsDayPickups = `-- name: OperationsDayPickups :one
SELECT
  count(*)::bigint AS due,
  count(*) FILTER (WHERE o.status = 'fulfilled'::order_status)::bigint AS collected,
  count(*) FILTER (WHERE o.status IN ('pending', 'confirmed', 'in_production', 'ready'))::bigint AS to_collect,
  count(*) FILTER (WHERE o.status = 'no_show'::order_status)::bigint AS missed
FROM orders o
LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
  AND o.pickup_at >= $1::timestamptz
  AND o.pickup_at < $2::timestamptz
  AND o.status NOT IN ('awaiting_payment', 'expired', 'cancelled')
`

type OperationsDayPickupsParams struct {
	FromAt time.Time `json:"fromAt"`
	ToAt   time.Time `json:"toAt"`
}

type OperationsDayPickupsRow struct {
	Due       int64 `json:"due"`
	Collected int64 `json:"collected"`
	ToCollect int64 `json:"toCollect"`
	Missed    int64 `json:"missed"`
}

// The orders the bakery took with a pickup in [from_at, to_at): how many,
// collected, still to collect, and not collected.
//
//	SELECT
//	  count(*)::bigint AS due,
//	  count(*) FILTER (WHERE o.status = 'fulfilled'::order_status)::bigint AS collected,
//	  count(*) FILTER (WHERE o.status IN ('pending', 'confirmed', 'in_production', 'ready'))::bigint AS to_collect,
//	  count(*) FILTER (WHERE o.status = 'no_show'::order_status)::bigint AS missed
//	FROM orders o
//	LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
//	  AND o.pickup_at >= $1::timestamptz
//	  AND o.pickup_at < $2::timestamptz
//	  AND o.status NOT IN ('awaiting_payment', 'expired', 'cancelled')
func (q *Queries) OperationsDayPickups(ctx context.Context, arg OperationsDayPickupsParams) (OperationsDayPickupsRow, error) {
	row := q.db.QueryRow(ctx, operationsDayPickups, arg.FromAt, arg.ToAt)
	var i OperationsDayPickupsRow
	err := row.Scan(
		&i.Due,
		&i.Collected,
		&i.ToCollect,
		&i.Missed,
	)
	return i, err
}

const operationsLateOrders = `-- name: OperationsLateOrders :many
SELECT
  o.code,
  o.status,
  o.pickup_at::timestamptz AS pickup_at,
  count(*) OVER ()::bigint AS total
FROM orders o
CROSS JOIN store_settings s
LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE s.id = 1
  AND (o.user_id IS NULL OR u.id IS NOT NULL)
  AND o.status IN ('pending', 'confirmed', 'in_production', 'ready')
  AND o.pickup_at <= $1::timestamptz - make_interval(mins => s.slot_minutes)
ORDER BY o.pickup_at, o.id
LIMIT $2::int
`

type OperationsLateOrdersParams struct {
	Now     time.Time `json:"now"`
	MaxRows int32     `json:"maxRows"`
}

type OperationsLateOrdersRow struct {
	Code     string      `json:"code"`
	Status   OrderStatus `json:"status"`
	PickupAt time.Time   `json:"pickupAt"`
	Total    int64       `json:"total"`
}

// The orders still to collect whose pickup slot has ended by now, as the
// counter marks them late, the longest waiting first, with how many there are.
//
//	SELECT
//	  o.code,
//	  o.status,
//	  o.pickup_at::timestamptz AS pickup_at,
//	  count(*) OVER ()::bigint AS total
//	FROM orders o
//	CROSS JOIN store_settings s
//	LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE s.id = 1
//	  AND (o.user_id IS NULL OR u.id IS NOT NULL)
//	  AND o.status IN ('pending', 'confirmed', 'in_production', 'ready')
//	  AND o.pickup_at <= $1::timestamptz - make_interval(mins => s.slot_minutes)
//	ORDER BY o.pickup_at, o.id
//	LIMIT $2::int
func (q *Queries) OperationsLateOrders(ctx context.Context, arg OperationsLateOrdersParams) ([]OperationsLateOrdersRow, error) {
	rows, err := q.db.Query(ctx, operationsLateOrders, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationsLateOrdersRow{}
	for rows.Next() {
		var i OperationsLateOrdersRow
		if err := rows.Scan(
			&i.Code,
			&i.Status,
			&i.PickupAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const operationsStationLoads = `-- name: OperationsStationLoads :many
SELECT
  t.station,
  count(*) FILTER (WHERE t.status = 'queued'::ticket_status)::bigint AS queued,
  count(*) FILTER (WHERE t.status = 'in_progress'::ticket_status)::bigint AS in_progress,
  count(*) FILTER (WHERE t.status = 'ready'::ticket_status)::bigint AS ready
FROM order_tickets t
JOIN orders o ON o.id = t.order_id
LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
  AND o.status IN ('confirmed', 'in_production', 'ready')
  AND t.status <> 'cancelled'::ticket_status
GROUP BY t.station
ORDER BY t.station
`

type OperationsStationLoadsRow struct {
	Station    Station `json:"station"`
	Queued     int64   `json:"queued"`
	InProgress int64   `json:"inProgress"`
	Ready      int64   `json:"ready"`
}

// The tickets of the orders being made or waiting at the counter, at each
// station, by status; a station with none is left out.
//
//	SELECT
//	  t.station,
//	  count(*) FILTER (WHERE t.status = 'queued'::ticket_status)::bigint AS queued,
//	  count(*) FILTER (WHERE t.status = 'in_progress'::ticket_status)::bigint AS in_progress,
//	  count(*) FILTER (WHERE t.status = 'ready'::ticket_status)::bigint AS ready
//	FROM order_tickets t
//	JOIN orders o ON o.id = t.order_id
//	LEFT JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (o.user_id IS NULL OR u.id IS NOT NULL)
//	  AND o.status IN ('confirmed', 'in_production', 'ready')
//	  AND t.status <> 'cancelled'::ticket_status
//	GROUP BY t.station
//	ORDER BY t.station
func (q *Queries) OperationsStationLoads(ctx context.Context) ([]OperationsStationLoadsRow, error) {
	rows, err := q.db.Query(ctx, operationsStationLoads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationsStationLoadsRow{}
	for rows.Next() {
		var i OperationsStationLoadsRow
		if err := rows.Scan(
			&i.Station,
			&i.Queued,
			&i.InProgress,
			&i.Ready,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
