// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  created_at,
  updated_at
`

type CreateOrderParams struct {
	UserID               uuid.UUID      `db:"user_id" json:"userId"`
	Status               OrderStatus    `db:"status" json:"status"`
	SubtotalCents        int64          `db:"subtotal_cents" json:"subtotalCents"`
	DiscountCents        int64          `db:"discount_cents" json:"discountCents"`
	TotalCents           int64          `db:"total_cents" json:"totalCents"`
	DiscountCodeID       uuid.NullUUID  `db:"discount_code_id" json:"discountCodeId"`
	DiscountCodeSnapshot sql.NullString `db:"discount_code_snapshot" json:"discountCodeSnapshot"`
}

// CreateOrder
//
//	INSERT INTO orders (
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  created_at,
//	  updated_at
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.DiscountCodeID,
		arg.DiscountCodeSnapshot,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  order_id,
  line_type,
  product_id,
  combo_id,
  name,
  slug,
  quantity,
  unit_price_cents,
  line_total_cents
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id,
  order_id,
  line_type,
  product_id,
  combo_id,
  name,
  slug,
  quantity,
  unit_price_cents,
  line_total_cents,
  created_at
`

type CreateOrderItemParams struct {
	OrderID        uuid.UUID     `db:"order_id" json:"orderId"`
	LineType       CartLineType  `db:"line_type" json:"lineType"`
	ProductID      uuid.NullUUID `db:"product_id" json:"productId"`
	ComboID        uuid.NullUUID `db:"combo_id" json:"comboId"`
	Name           string        `db:"name" json:"name"`
	Slug           string        `db:"slug" json:"slug"`
	Quantity       int32         `db:"quantity" json:"quantity"`
	UnitPriceCents int64         `db:"unit_price_cents" json:"unitPriceCents"`
	LineTotalCents int64         `db:"line_total_cents" json:"lineTotalCents"`
}

// CreateOrderItem
//
//	INSERT INTO order_items (
//	  order_id,
//	  line_type,
//	  product_id,
//	  combo_id,
//	  name,
//	  slug,
//	  quantity,
//	  unit_price_cents,
//	  line_total_cents
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
//	RETURNING
//	  id,
//	  order_id,
//	  line_type,
//	  product_id,
//	  combo_id,
//	  name,
//	  slug,
//	  quantity,
//	  unit_price_cents,
//	  line_total_cents,
//	  created_at
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.LineType,
		arg.ProductID,
		arg.ComboID,
		arg.Name,
		arg.Slug,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.LineTotalCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.LineType,
		&i.ProductID,
		&i.ComboID,
		&i.Name,
		&i.Slug,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.LineTotalCents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByIDForUser = `-- name: GetOrderByIDForUser :one
SELECT
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  created_at,
  updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByIDForUserParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

// GetOrderByIDForUser
//
//	SELECT
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  created_at,
//	  updated_at
//	FROM orders
//	WHERE id = $1 AND user_id = $2
func (q *Queries) GetOrderByIDForUser(ctx context.Context, arg GetOrderByIDForUserParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByIDForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
  id,
  order_id,
  line_type,
  product_id,
  combo_id,
  name,
  slug,
  quantity,
  unit_price_cents,
  line_total_cents,
  created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

// ListOrderItemsByOrderID
//
//	SELECT
//	  id,
//	  order_id,
//	  line_type,
//	  product_id,
//	  combo_id,
//	  name,
//	  slug,
//	  quantity,
//	  unit_price_cents,
//	  line_total_cents,
//	  created_at
//	FROM order_items
//	WHERE order_id = $1
//	ORDER BY created_at ASC
func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.LineType,
			&i.ProductID,
			&i.ComboID,
			&i.Name,
			&i.Slug,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.LineTotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  created_at,
  updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"userId"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

// ListOrdersByUser
//
//	SELECT
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  created_at,
//	  updated_at
//	FROM orders
//	WHERE user_id = $1
//	ORDER BY created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.DiscountCodeID,
			&i.DiscountCodeSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserCount = `-- name: ListOrdersByUserCount :one
SELECT COUNT(*)::bigint AS count
FROM orders
WHERE user_id = $1
`

// ListOrdersByUserCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM orders
//	WHERE user_id = $1
func (q *Queries) ListOrdersByUserCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, listOrdersByUserCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const staffGetOrderByID = `-- name: StaffGetOrderByID :one
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_cents,
  o.discount_cents,
  o.total_cents,
  o.discount_code_id,
  o.discount_code_snapshot,
  o.created_at,
  o.updated_at,
  u.email AS customer_email,
  cp.display_name AS customer_display_name
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
WHERE o.id = $1
`

type StaffGetOrderByIDRow struct {
	ID                   uuid.UUID      `db:"id" json:"id"`
	UserID               uuid.UUID      `db:"user_id" json:"userId"`
	Status               OrderStatus    `db:"status" json:"status"`
	SubtotalCents        int64          `db:"subtotal_cents" json:"subtotalCents"`
	DiscountCents        int64          `db:"discount_cents" json:"discountCents"`
	TotalCents           int64          `db:"total_cents" json:"totalCents"`
	DiscountCodeID       uuid.NullUUID  `db:"discount_code_id" json:"discountCodeId"`
	DiscountCodeSnapshot sql.NullString `db:"discount_code_snapshot" json:"discountCodeSnapshot"`
	CreatedAt            time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updatedAt"`
	CustomerEmail        string         `db:"customer_email" json:"customerEmail"`
	CustomerDisplayName  sql.NullString `db:"customer_display_name" json:"customerDisplayName"`
}

// StaffGetOrderByID
//
//	SELECT
//	  o.id,
//	  o.user_id,
//	  o.status,
//	  o.subtotal_cents,
//	  o.discount_cents,
//	  o.total_cents,
//	  o.discount_code_id,
//	  o.discount_code_snapshot,
//	  o.created_at,
//	  o.updated_at,
//	  u.email AS customer_email,
//	  cp.display_name AS customer_display_name
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	WHERE o.id = $1
func (q *Queries) StaffGetOrderByID(ctx context.Context, id uuid.UUID) (StaffGetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, staffGetOrderByID, id)
	var i StaffGetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.CustomerDisplayName,
	)
	return i, err
}

const staffListOrders = `-- name: StaffListOrders :many
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_cents,
  o.discount_cents,
  o.total_cents,
  o.discount_code_id,
  o.discount_code_snapshot,
  o.created_at,
  o.updated_at,
  u.email AS customer_email,
  cp.display_name AS customer_display_name
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
WHERE (
    $1::order_status IS NULL
    OR o.status = $1::order_status
)
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type StaffListOrdersParams struct {
	Status NullOrderStatus `db:"status" json:"status"`
	Offset int32           `db:"offset" json:"offset"`
	Limit  int32           `db:"limit" json:"limit"`
}

type StaffListOrdersRow struct {
	ID                   uuid.UUID      `db:"id" json:"id"`
	UserID               uuid.UUID      `db:"user_id" json:"userId"`
	Status               OrderStatus    `db:"status" json:"status"`
	SubtotalCents        int64          `db:"subtotal_cents" json:"subtotalCents"`
	DiscountCents        int64          `db:"discount_cents" json:"discountCents"`
	TotalCents           int64          `db:"total_cents" json:"totalCents"`
	DiscountCodeID       uuid.NullUUID  `db:"discount_code_id" json:"discountCodeId"`
	DiscountCodeSnapshot sql.NullString `db:"discount_code_snapshot" json:"discountCodeSnapshot"`
	CreatedAt            time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt            time.Time      `db:"updated_at" json:"updatedAt"`
	CustomerEmail        string         `db:"customer_email" json:"customerEmail"`
	CustomerDisplayName  sql.NullString `db:"customer_display_name" json:"customerDisplayName"`
}

// StaffListOrders
//
//	SELECT
//	  o.id,
//	  o.user_id,
//	  o.status,
//	  o.subtotal_cents,
//	  o.discount_cents,
//	  o.total_cents,
//	  o.discount_code_id,
//	  o.discount_code_snapshot,
//	  o.created_at,
//	  o.updated_at,
//	  u.email AS customer_email,
//	  cp.display_name AS customer_display_name
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	WHERE (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	)
//	ORDER BY o.created_at DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) StaffListOrders(ctx context.Context, arg StaffListOrdersParams) ([]StaffListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, staffListOrders, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffListOrdersRow{}
	for rows.Next() {
		var i StaffListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.DiscountCodeID,
			&i.DiscountCodeSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.CustomerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffListOrdersCount = `-- name: StaffListOrdersCount :one
SELECT COUNT(*)::bigint AS count
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (
    $1::order_status IS NULL
    OR o.status = $1::order_status
)
`

// StaffListOrdersCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	)
func (q *Queries) StaffListOrdersCount(ctx context.Context, status NullOrderStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, staffListOrdersCount, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumOrderItemQuantitiesByOrderIDs = `-- name: SumOrderItemQuantitiesByOrderIDs :many
SELECT order_id, COALESCE(SUM(quantity), 0)::bigint AS item_count
FROM order_items
WHERE order_id = ANY($1::uuid[])
GROUP BY order_id
`

type SumOrderItemQuantitiesByOrderIDsRow struct {
	OrderID   uuid.UUID `db:"order_id" json:"orderId"`
	ItemCount int64     `db:"item_count" json:"itemCount"`
}

// SumOrderItemQuantitiesByOrderIDs
//
//	SELECT order_id, COALESCE(SUM(quantity), 0)::bigint AS item_count
//	FROM order_items
//	WHERE order_id = ANY($1::uuid[])
//	GROUP BY order_id
func (q *Queries) SumOrderItemQuantitiesByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]SumOrderItemQuantitiesByOrderIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, sumOrderItemQuantitiesByOrderIDs, pq.Array(orderIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumOrderItemQuantitiesByOrderIDsRow{}
	for rows.Next() {
		var i SumOrderItemQuantitiesByOrderIDsRow
		if err := rows.Scan(&i.OrderID, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1::order_status,
    updated_at = now()
WHERE id = $2
  AND status = $3::order_status
RETURNING
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  created_at,
  updated_at
`

type UpdateOrderStatusParams struct {
	ToStatus   OrderStatus `db:"to_status" json:"toStatus"`
	ID         uuid.UUID   `db:"id" json:"id"`
	FromStatus OrderStatus `db:"from_status" json:"fromStatus"`
}

// UpdateOrderStatus
//
//	UPDATE orders
//	SET status = $1::order_status,
//	    updated_at = now()
//	WHERE id = $2
//	  AND status = $3::order_status
//	RETURNING
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  created_at,
//	  updated_at
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
