// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_incident.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrderIncidents = `-- name: CountOrderIncidents :one
SELECT count(*)::bigint
FROM order_incidents
WHERE created_at >= $1
  AND created_at < $2
  AND ($3::order_incident_type IS NULL OR type = $3::order_incident_type)
`

type CountOrderIncidentsParams struct {
	FromAt time.Time          `json:"fromAt"`
	ToAt   time.Time          `json:"toAt"`
	Type   *OrderIncidentType `json:"type"`
}

// CountOrderIncidents
//
//	SELECT count(*)::bigint
//	FROM order_incidents
//	WHERE created_at >= $1
//	  AND created_at < $2
//	  AND ($3::order_incident_type IS NULL OR type = $3::order_incident_type)
func (q *Queries) CountOrderIncidents(ctx context.Context, arg CountOrderIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderIncidents, arg.FromAt, arg.ToAt, arg.Type)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrderIncidentsByType = `-- name: CountOrderIncidentsByType :many
SELECT type, count(*)::bigint AS count
FROM order_incidents
WHERE created_at >= $1
  AND created_at < $2
GROUP BY type
ORDER BY type
`

type CountOrderIncidentsByTypeParams struct {
	FromAt time.Time `json:"fromAt"`
	ToAt   time.Time `json:"toAt"`
}

type CountOrderIncidentsByTypeRow struct {
	Type  OrderIncidentType `json:"type"`
	Count int64             `json:"count"`
}

// CountOrderIncidentsByType
//
//	SELECT type, count(*)::bigint AS count
//	FROM order_incidents
//	WHERE created_at >= $1
//	  AND created_at < $2
//	GROUP BY type
//	ORDER BY type
func (q *Queries) CountOrderIncidentsByType(ctx context.Context, arg CountOrderIncidentsByTypeParams) ([]CountOrderIncidentsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countOrderIncidentsByType, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOrderIncidentsByTypeRow{}
	for rows.Next() {
		var i CountOrderIncidentsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrderIncident = `-- name: CreateOrderIncident :one
INSERT INTO order_incidents (order_id, type, note, actor_id, actor_role)
VALUES (
  $1,
  $2::order_incident_type,
  $3,
  $4,
  $5::user_role
)
RETURNING id, order_id, type, note, actor_id, actor_role, created_at
`

type CreateOrderIncidentParams struct {
	OrderID   uuid.UUID         `json:"orderId"`
	Type      OrderIncidentType `json:"type"`
	Note      *string           `json:"note"`
	ActorID   *uuid.UUID        `json:"actorId"`
	ActorRole *UserRole         `json:"actorRole"`
}

// CreateOrderIncident
//
//	INSERT INTO order_incidents (order_id, type, note, actor_id, actor_role)
//	VALUES (
//	  $1,
//	  $2::order_incident_type,
//	  $3,
//	  $4,
//	  $5::user_role
//	)
//	RETURNING id, order_id, type, note, actor_id, actor_role, created_at
func (q *Queries) CreateOrderIncident(ctx context.Context, arg CreateOrderIncidentParams) (OrderIncident, error) {
	row := q.db.QueryRow(ctx, createOrderIncident,
		arg.OrderID,
		arg.Type,
		arg.Note,
		arg.ActorID,
		arg.ActorRole,
	)
	var i OrderIncident
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Type,
		&i.Note,
		&i.ActorID,
		&i.ActorRole,
		&i.CreatedAt,
	)
	return i, err
}

const eraseOrderIncidentNotes = `-- name: EraseOrderIncidentNotes :exec
UPDATE order_incidents
SET note = NULL
WHERE note IS NOT NULL
  AND order_id IN (SELECT id FROM orders WHERE user_id = $1::uuid)
`

// EraseOrderIncidentNotes
//
//	UPDATE order_incidents
//	SET note = NULL
//	WHERE note IS NOT NULL
//	  AND order_id IN (SELECT id FROM orders WHERE user_id = $1::uuid)
func (q *Queries) EraseOrderIncidentNotes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseOrderIncidentNotes, userID)
	return err
}

const flagPaymentAnomaly = `-- name: FlagPaymentAnomaly :one
WITH recent AS (
  SELECT i.type
  FROM order_incidents i
  JOIN orders o ON o.id = i.order_id
  JOIN orders flagged ON flagged.user_id = o.user_id
  WHERE flagged.id = $1
    AND i.type IN ('payment_failed', 'payment_expired', 'payment_anomaly')
    AND i.created_at > now() - make_interval(secs => $3::double precision)
)
INSERT INTO order_incidents (order_id, type)
SELECT $1, 'payment_anomaly'::order_incident_type
WHERE (SELECT count(*) FROM recent WHERE type <> 'payment_anomaly') >= $2::int
  AND NOT EXISTS (SELECT 1 FROM recent WHERE type = 'payment_anomaly')
RETURNING id, order_id, type, note, actor_id, actor_role, created_at
`

type FlagPaymentAnomalyParams struct {
	OrderID       uuid.UUID `json:"orderId"`
	Threshold     int32     `json:"threshold"`
	WindowSeconds float64   `json:"windowSeconds"`
}

// Flags the customer of an order when their orders' payments failed or expired
// threshold times within the window, unless a flag within it already covers
// them; no row when it records none. An order without a customer flags nobody.
//
//	WITH recent AS (
//	  SELECT i.type
//	  FROM order_incidents i
//	  JOIN orders o ON o.id = i.order_id
//	  JOIN orders flagged ON flagged.user_id = o.user_id
//	  WHERE flagged.id = $1
//	    AND i.type IN ('payment_failed', 'payment_expired', 'payment_anomaly')
//	    AND i.created_at > now() - make_interval(secs => $3::double precision)
//	)
//	INSERT INTO order_incidents (order_id, type)
//	SELECT $1, 'payment_anomaly'::order_incident_type
//	WHERE (SELECT count(*) FROM recent WHERE type <> 'payment_anomaly') >= $2::int
//	  AND NOT EXISTS (SELECT 1 FROM recent WHERE type = 'payment_anomaly')
//	RETURNING id, order_id, type, note, actor_id, actor_role, created_at
func (q *Queries) FlagPaymentAnomaly(ctx context.Context, arg FlagPaymentAnomalyParams) (OrderIncident, error) {
	row := q.db.QueryRow(ctx, flagPaymentAnomaly, arg.OrderID, arg.Threshold, arg.WindowSeconds)
	var i OrderIncident
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Type,
		&i.Note,
		&i.ActorID,
		&i.ActorRole,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderIncidents = `-- name: ListOrderIncidents :many
SELECT
  i.id,
  i.order_id,
  i.type,
  i.note,
  i.created_at,
  o.code AS order_code,
  o.pickup_at,
  sp.full_name AS actor_name,
  cancelled.reason AS cancel_reason
FROM order_incidents i
JOIN orders o ON o.id = i.order_id
LEFT JOIN staff_profiles sp ON sp.user_id = i.actor_id
LEFT JOIN order_status_events cancelled
  ON i.type = 'bakery_cancelled'
  AND cancelled.order_id = i.order_id
  AND cancelled.to_status = 'cancelled'
WHERE i.created_at >= $1
  AND i.created_at < $2
  AND ($3::order_incident_type IS NULL OR i.type = $3::order_incident_type)
ORDER BY i.created_at DESC, i.id DESC
LIMIT $5 OFFSET $4
`

type ListOrderIncidentsParams struct {
	FromAt time.Time          `json:"fromAt"`
	ToAt   time.Time          `json:"toAt"`
	Type   *OrderIncidentType `json:"type"`
	Offset int32              `json:"offset"`
	Limit  int32              `json:"limit"`
}

type ListOrderIncidentsRow struct {
	ID           uuid.UUID         `json:"id"`
	OrderID      uuid.UUID         `json:"orderId"`
	Type         OrderIncidentType `json:"type"`
	Note         *string           `json:"note"`
	CreatedAt    time.Time         `json:"createdAt"`
	OrderCode    string            `json:"orderCode"`
	PickupAt     *time.Time        `json:"pickupAt"`
	ActorName    *string           `json:"actorName"`
	CancelReason *string           `json:"cancelReason"`
}

// A page of the incidents recorded in [from_at, to_at), latest first, with
// each order's code and pickup time, the staff member who recorded it and, for
// a bakery cancellation, the reason the customer was given (an order is
// cancelled once).
//
//	SELECT
//	  i.id,
//	  i.order_id,
//	  i.type,
//	  i.note,
//	  i.created_at,
//	  o.code AS order_code,
//	  o.pickup_at,
//	  sp.full_name AS actor_name,
//	  cancelled.reason AS cancel_reason
//	FROM order_incidents i
//	JOIN orders o ON o.id = i.order_id
//	LEFT JOIN staff_profiles sp ON sp.user_id = i.actor_id
//	LEFT JOIN order_status_events cancelled
//	  ON i.type = 'bakery_cancelled'
//	  AND cancelled.order_id = i.order_id
//	  AND cancelled.to_status = 'cancelled'
//	WHERE i.created_at >= $1
//	  AND i.created_at < $2
//	  AND ($3::order_incident_type IS NULL OR i.type = $3::order_incident_type)
//	ORDER BY i.created_at DESC, i.id DESC
//	LIMIT $5 OFFSET $4
func (q *Queries) ListOrderIncidents(ctx context.Context, arg ListOrderIncidentsParams) ([]ListOrderIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listOrderIncidents,
		arg.FromAt,
		arg.ToAt,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderIncidentsRow{}
	for rows.Next() {
		var i ListOrderIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Type,
			&i.Note,
			&i.CreatedAt,
			&i.OrderCode,
			&i.PickupAt,
			&i.ActorName,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderIncidentsByOrderIDs = `-- name: ListOrderIncidentsByOrderIDs :many
SELECT id, order_id, type, note, actor_id, actor_role, created_at
FROM order_incidents
WHERE order_id = ANY($1::uuid[])
ORDER BY order_id, created_at ASC, id ASC
`

// The incidents of many orders in one round trip, as a data export reads them.
//
//	SELECT id, order_id, type, note, actor_id, actor_role, created_at
//	FROM order_incidents
//	WHERE order_id = ANY($1::uuid[])
//	ORDER BY order_id, created_at ASC, id ASC
func (q *Queries) ListOrderIncidentsByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]OrderIncident, error) {
	rows, err := q.db.Query(ctx, listOrderIncidentsByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderIncident{}
	for rows.Next() {
		var i OrderIncident
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Type,
			&i.Note,
			&i.ActorID,
			&i.ActorRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerIncidents = `-- name: LockCustomerIncidents :exec
SELECT pg_advisory_xact_lock($1::int, hashtext(user_id::text))
FROM orders
WHERE id = $2
  AND user_id IS NOT NULL
`

type LockCustomerIncidentsParams struct {
	Namespace int32     `json:"namespace"`
	OrderID   uuid.UUID `json:"orderId"`
}

// Holds the flags of the order's customer until the transaction ends, so two
// of their payments failing at once both count. The key is the customer, under
// a namespace of its own; an order without a customer locks nothing.
//
//	SELECT pg_advisory_xact_lock($1::int, hashtext(user_id::text))
//	FROM orders
//	WHERE id = $2
//	  AND user_id IS NOT NULL
func (q *Queries) LockCustomerIncidents(ctx context.Context, arg LockCustomerIncidentsParams) error {
	_, err := q.db.Exec(ctx, lockCustomerIncidents, arg.Namespace, arg.OrderID)
	return err
}
