// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bakerListProductionOrders = `-- name: BakerListProductionOrders :many
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_cents,
  o.discount_cents,
  o.total_cents,
  o.discount_code_id,
  o.discount_code_snapshot,
  o.pickup_at,
  o.created_at,
  o.updated_at,
  o.code,
  u.email AS customer_email,
  cp.display_name AS customer_display_name
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
WHERE o.status IN (
    'confirmed'::order_status,
    'in_production'::order_status,
    'ready'::order_status
  )
  AND (
    $1::order_status IS NULL
    OR o.status = $1::order_status
  )
ORDER BY o.pickup_at ASC NULLS LAST, o.created_at ASC
LIMIT $3 OFFSET $2
`

type BakerListProductionOrdersParams struct {
	Status *OrderStatus `json:"status"`
	Offset int32        `json:"offset"`
	Limit  int32        `json:"limit"`
}

type BakerListProductionOrdersRow struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"userId"`
	Status               OrderStatus `json:"status"`
	SubtotalCents        int64       `json:"subtotalCents"`
	DiscountCents        int64       `json:"discountCents"`
	TotalCents           int64       `json:"totalCents"`
	DiscountCodeID       *uuid.UUID  `json:"discountCodeId"`
	DiscountCodeSnapshot *string     `json:"discountCodeSnapshot"`
	PickupAt             *time.Time  `json:"pickupAt"`
	CreatedAt            time.Time   `json:"createdAt"`
	UpdatedAt            time.Time   `json:"updatedAt"`
	Code                 string      `json:"code"`
	CustomerEmail        string      `json:"customerEmail"`
	CustomerDisplayName  *string     `json:"customerDisplayName"`
}

// BakerListProductionOrders
//
//	SELECT
//	  o.id,
//	  o.user_id,
//	  o.status,
//	  o.subtotal_cents,
//	  o.discount_cents,
//	  o.total_cents,
//	  o.discount_code_id,
//	  o.discount_code_snapshot,
//	  o.pickup_at,
//	  o.created_at,
//	  o.updated_at,
//	  o.code,
//	  u.email AS customer_email,
//	  cp.display_name AS customer_display_name
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	WHERE o.status IN (
//	    'confirmed'::order_status,
//	    'in_production'::order_status,
//	    'ready'::order_status
//	  )
//	  AND (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	  )
//	ORDER BY o.pickup_at ASC NULLS LAST, o.created_at ASC
//	LIMIT $3 OFFSET $2
func (q *Queries) BakerListProductionOrders(ctx context.Context, arg BakerListProductionOrdersParams) ([]BakerListProductionOrdersRow, error) {
	rows, err := q.db.Query(ctx, bakerListProductionOrders, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BakerListProductionOrdersRow{}
	for rows.Next() {
		var i BakerListProductionOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.DiscountCodeID,
			&i.DiscountCodeSnapshot,
			&i.PickupAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
			&i.CustomerEmail,
			&i.CustomerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bakerListProductionOrdersCount = `-- name: BakerListProductionOrdersCount :one
SELECT COUNT(*)::bigint AS count
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE o.status IN (
    'confirmed'::order_status,
    'in_production'::order_status,
    'ready'::order_status
  )
  AND (
    $1::order_status IS NULL
    OR o.status = $1::order_status
  )
`

// BakerListProductionOrdersCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE o.status IN (
//	    'confirmed'::order_status,
//	    'in_production'::order_status,
//	    'ready'::order_status
//	  )
//	  AND (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	  )
func (q *Queries) BakerListProductionOrdersCount(ctx context.Context, status *OrderStatus) (int64, error) {
	row := q.db.QueryRow(ctx, bakerListProductionOrdersCount, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  pickup_at,
  code
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  pickup_at,
  created_at,
  updated_at,
  code
`

type CreateOrderParams struct {
	UserID               uuid.UUID   `json:"userId"`
	Status               OrderStatus `json:"status"`
	SubtotalCents        int64       `json:"subtotalCents"`
	DiscountCents        int64       `json:"discountCents"`
	TotalCents           int64       `json:"totalCents"`
	DiscountCodeID       *uuid.UUID  `json:"discountCodeId"`
	DiscountCodeSnapshot *string     `json:"discountCodeSnapshot"`
	PickupAt             *time.Time  `json:"pickupAt"`
	Code                 string      `json:"code"`
}

// CreateOrder
//
//	INSERT INTO orders (
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  pickup_at,
//	  code
//	)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
//	RETURNING
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  pickup_at,
//	  created_at,
//	  updated_at,
//	  code
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.DiscountCodeID,
		arg.DiscountCodeSnapshot,
		arg.PickupAt,
		arg.Code,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.PickupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}

const createOrderItems = `-- name: CreateOrderItems :execrows
INSERT INTO order_items (
  order_id,
  line_type,
  product_id,
  combo_id,
  configuration,
  name,
  slug,
  quantity,
  unit_price_cents,
  line_total_cents
)
SELECT
  item.order_id,
  item.line_type,
  item.product_id,
  item.combo_id,
  item.configuration,
  item.name,
  item.slug,
  item.quantity,
  item.unit_price_cents,
  item.line_total_cents
FROM jsonb_to_recordset($1::jsonb) AS item (
  order_id uuid,
  line_type line_type,
  product_id uuid,
  combo_id uuid,
  configuration jsonb,
  name text,
  slug text,
  quantity integer,
  unit_price_cents bigint,
  line_total_cents bigint
)
`

// One round trip for every checkout line: the items arrive as a JSON array and
// Postgres casts each field to the column type (constraints still apply per row).
//
//	INSERT INTO order_items (
//	  order_id,
//	  line_type,
//	  product_id,
//	  combo_id,
//	  configuration,
//	  name,
//	  slug,
//	  quantity,
//	  unit_price_cents,
//	  line_total_cents
//	)
//	SELECT
//	  item.order_id,
//	  item.line_type,
//	  item.product_id,
//	  item.combo_id,
//	  item.configuration,
//	  item.name,
//	  item.slug,
//	  item.quantity,
//	  item.unit_price_cents,
//	  item.line_total_cents
//	FROM jsonb_to_recordset($1::jsonb) AS item (
//	  order_id uuid,
//	  line_type line_type,
//	  product_id uuid,
//	  combo_id uuid,
//	  configuration jsonb,
//	  name text,
//	  slug text,
//	  quantity integer,
//	  unit_price_cents bigint,
//	  line_total_cents bigint
//	)
func (q *Queries) CreateOrderItems(ctx context.Context, items json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, createOrderItems, items)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrderStatusEvent = `-- name: CreateOrderStatusEvent :exec
INSERT INTO order_status_events (order_id, from_status, to_status, actor_id, actor_role)
VALUES (
  $1,
  $2::order_status,
  $3::order_status,
  $4,
  $5::user_role
)
`

type CreateOrderStatusEventParams struct {
	OrderID    uuid.UUID    `json:"orderId"`
	FromStatus *OrderStatus `json:"fromStatus"`
	ToStatus   OrderStatus  `json:"toStatus"`
	ActorID    uuid.UUID    `json:"actorId"`
	ActorRole  UserRole     `json:"actorRole"`
}

// CreateOrderStatusEvent
//
//	INSERT INTO order_status_events (order_id, from_status, to_status, actor_id, actor_role)
//	VALUES (
//	  $1,
//	  $2::order_status,
//	  $3::order_status,
//	  $4,
//	  $5::user_role
//	)
func (q *Queries) CreateOrderStatusEvent(ctx context.Context, arg CreateOrderStatusEventParams) error {
	_, err := q.db.Exec(ctx, createOrderStatusEvent,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.ActorRole,
	)
	return err
}

const getOrderByIDForUser = `-- name: GetOrderByIDForUser :one
SELECT
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  pickup_at,
  created_at,
  updated_at,
  code
FROM orders
WHERE id = $1 AND user_id = $2
`

type GetOrderByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

// GetOrderByIDForUser
//
//	SELECT
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  pickup_at,
//	  created_at,
//	  updated_at,
//	  code
//	FROM orders
//	WHERE id = $1 AND user_id = $2
func (q *Queries) GetOrderByIDForUser(ctx context.Context, arg GetOrderByIDForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.PickupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
  id,
  order_id,
  line_type,
  product_id,
  combo_id,
  configuration,
  name,
  slug,
  quantity,
  unit_price_cents,
  line_total_cents,
  created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

// ListOrderItemsByOrderID
//
//	SELECT
//	  id,
//	  order_id,
//	  line_type,
//	  product_id,
//	  combo_id,
//	  configuration,
//	  name,
//	  slug,
//	  quantity,
//	  unit_price_cents,
//	  line_total_cents,
//	  created_at
//	FROM order_items
//	WHERE order_id = $1
//	ORDER BY created_at ASC
func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.LineType,
			&i.ProductID,
			&i.ComboID,
			&i.Configuration,
			&i.Name,
			&i.Slug,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.LineTotalCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatusEvents = `-- name: ListOrderStatusEvents :many
SELECT to_status, actor_role, created_at
FROM order_status_events
WHERE order_id = $1
ORDER BY created_at ASC, id ASC
`

type ListOrderStatusEventsRow struct {
	ToStatus  OrderStatus `json:"toStatus"`
	ActorRole UserRole    `json:"actorRole"`
	CreatedAt time.Time   `json:"createdAt"`
}

// ListOrderStatusEvents
//
//	SELECT to_status, actor_role, created_at
//	FROM order_status_events
//	WHERE order_id = $1
//	ORDER BY created_at ASC, id ASC
func (q *Queries) ListOrderStatusEvents(ctx context.Context, orderID uuid.UUID) ([]ListOrderStatusEventsRow, error) {
	rows, err := q.db.Query(ctx, listOrderStatusEvents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderStatusEventsRow{}
	for rows.Next() {
		var i ListOrderStatusEventsRow
		if err := rows.Scan(&i.ToStatus, &i.ActorRole, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  pickup_at,
  created_at,
  updated_at,
  code
FROM orders
WHERE user_id = $1
  AND (
    $2::order_status IS NULL
    OR status = $2::order_status
  )
  AND (
    $3::timestamptz IS NULL
    OR created_at >= $3::timestamptz
  )
  AND (
    $4::timestamptz IS NULL
    OR created_at < $4::timestamptz
  )
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListOrdersByUserParams struct {
	UserID       uuid.UUID    `json:"userId"`
	Status       *OrderStatus `json:"status"`
	PlacedFrom   *time.Time   `json:"placedFrom"`
	PlacedBefore *time.Time   `json:"placedBefore"`
	Offset       int32        `json:"offset"`
	Limit        int32        `json:"limit"`
}

// ListOrdersByUser
//
//	SELECT
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  pickup_at,
//	  created_at,
//	  updated_at,
//	  code
//	FROM orders
//	WHERE user_id = $1
//	  AND (
//	    $2::order_status IS NULL
//	    OR status = $2::order_status
//	  )
//	  AND (
//	    $3::timestamptz IS NULL
//	    OR created_at >= $3::timestamptz
//	  )
//	  AND (
//	    $4::timestamptz IS NULL
//	    OR created_at < $4::timestamptz
//	  )
//	ORDER BY created_at DESC
//	LIMIT $6 OFFSET $5
func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser,
		arg.UserID,
		arg.Status,
		arg.PlacedFrom,
		arg.PlacedBefore,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.DiscountCodeID,
			&i.DiscountCodeSnapshot,
			&i.PickupAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserCount = `-- name: ListOrdersByUserCount :one
SELECT COUNT(*)::bigint AS count
FROM orders
WHERE user_id = $1
  AND (
    $2::order_status IS NULL
    OR status = $2::order_status
  )
  AND (
    $3::timestamptz IS NULL
    OR created_at >= $3::timestamptz
  )
  AND (
    $4::timestamptz IS NULL
    OR created_at < $4::timestamptz
  )
`

type ListOrdersByUserCountParams struct {
	UserID       uuid.UUID    `json:"userId"`
	Status       *OrderStatus `json:"status"`
	PlacedFrom   *time.Time   `json:"placedFrom"`
	PlacedBefore *time.Time   `json:"placedBefore"`
}

// ListOrdersByUserCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM orders
//	WHERE user_id = $1
//	  AND (
//	    $2::order_status IS NULL
//	    OR status = $2::order_status
//	  )
//	  AND (
//	    $3::timestamptz IS NULL
//	    OR created_at >= $3::timestamptz
//	  )
//	  AND (
//	    $4::timestamptz IS NULL
//	    OR created_at < $4::timestamptz
//	  )
func (q *Queries) ListOrdersByUserCount(ctx context.Context, arg ListOrdersByUserCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, listOrdersByUserCount,
		arg.UserID,
		arg.Status,
		arg.PlacedFrom,
		arg.PlacedBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const nextOrderDayNumber = `-- name: NextOrderDayNumber :one
INSERT INTO order_day_counters (day, last_number)
VALUES ((now() AT TIME ZONE $1::text)::date, 1)
ON CONFLICT (day) DO UPDATE
SET last_number = order_day_counters.last_number + 1
RETURNING day, last_number
`

// The day is read from the transaction's clock, the instant orders.created_at
// takes, so a code and its created_at always name the same bakery day. The row
// lock taken by the upsert holds every other checkout on that day until this
// transaction ends, so numbers are unique and follow each other.
//
//	INSERT INTO order_day_counters (day, last_number)
//	VALUES ((now() AT TIME ZONE $1::text)::date, 1)
//	ON CONFLICT (day) DO UPDATE
//	SET last_number = order_day_counters.last_number + 1
//	RETURNING day, last_number
func (q *Queries) NextOrderDayNumber(ctx context.Context, zone string) (OrderDayCounter, error) {
	row := q.db.QueryRow(ctx, nextOrderDayNumber, zone)
	var i OrderDayCounter
	err := row.Scan(&i.Day, &i.LastNumber)
	return i, err
}

const staffGetOrderByID = `-- name: StaffGetOrderByID :one
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_cents,
  o.discount_cents,
  o.total_cents,
  o.discount_code_id,
  o.discount_code_snapshot,
  o.pickup_at,
  o.created_at,
  o.updated_at,
  o.code,
  u.email AS customer_email,
  cp.display_name AS customer_display_name,
  cp.phone AS customer_phone
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
WHERE o.id = $1
`

type StaffGetOrderByIDRow struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"userId"`
	Status               OrderStatus `json:"status"`
	SubtotalCents        int64       `json:"subtotalCents"`
	DiscountCents        int64       `json:"discountCents"`
	TotalCents           int64       `json:"totalCents"`
	DiscountCodeID       *uuid.UUID  `json:"discountCodeId"`
	DiscountCodeSnapshot *string     `json:"discountCodeSnapshot"`
	PickupAt             *time.Time  `json:"pickupAt"`
	CreatedAt            time.Time   `json:"createdAt"`
	UpdatedAt            time.Time   `json:"updatedAt"`
	Code                 string      `json:"code"`
	CustomerEmail        string      `json:"customerEmail"`
	CustomerDisplayName  *string     `json:"customerDisplayName"`
	CustomerPhone        *string     `json:"customerPhone"`
}

// StaffGetOrderByID
//
//	SELECT
//	  o.id,
//	  o.user_id,
//	  o.status,
//	  o.subtotal_cents,
//	  o.discount_cents,
//	  o.total_cents,
//	  o.discount_code_id,
//	  o.discount_code_snapshot,
//	  o.pickup_at,
//	  o.created_at,
//	  o.updated_at,
//	  o.code,
//	  u.email AS customer_email,
//	  cp.display_name AS customer_display_name,
//	  cp.phone AS customer_phone
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	WHERE o.id = $1
func (q *Queries) StaffGetOrderByID(ctx context.Context, id uuid.UUID) (StaffGetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, staffGetOrderByID, id)
	var i StaffGetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.PickupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.CustomerEmail,
		&i.CustomerDisplayName,
		&i.CustomerPhone,
	)
	return i, err
}

const staffListOrders = `-- name: StaffListOrders :many
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_cents,
  o.discount_cents,
  o.total_cents,
  o.discount_code_id,
  o.discount_code_snapshot,
  o.pickup_at,
  o.created_at,
  o.updated_at,
  o.code,
  u.email AS customer_email,
  cp.display_name AS customer_display_name
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
WHERE (
    $1::order_status IS NULL
    OR o.status = $1::order_status
)
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type StaffListOrdersParams struct {
	Status *OrderStatus `json:"status"`
	Offset int32        `json:"offset"`
	Limit  int32        `json:"limit"`
}

type StaffListOrdersRow struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"userId"`
	Status               OrderStatus `json:"status"`
	SubtotalCents        int64       `json:"subtotalCents"`
	DiscountCents        int64       `json:"discountCents"`
	TotalCents           int64       `json:"totalCents"`
	DiscountCodeID       *uuid.UUID  `json:"discountCodeId"`
	DiscountCodeSnapshot *string     `json:"discountCodeSnapshot"`
	PickupAt             *time.Time  `json:"pickupAt"`
	CreatedAt            time.Time   `json:"createdAt"`
	UpdatedAt            time.Time   `json:"updatedAt"`
	Code                 string      `json:"code"`
	CustomerEmail        string      `json:"customerEmail"`
	CustomerDisplayName  *string     `json:"customerDisplayName"`
}

// StaffListOrders
//
//	SELECT
//	  o.id,
//	  o.user_id,
//	  o.status,
//	  o.subtotal_cents,
//	  o.discount_cents,
//	  o.total_cents,
//	  o.discount_code_id,
//	  o.discount_code_snapshot,
//	  o.pickup_at,
//	  o.created_at,
//	  o.updated_at,
//	  o.code,
//	  u.email AS customer_email,
//	  cp.display_name AS customer_display_name
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	WHERE (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	)
//	ORDER BY o.created_at DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) StaffListOrders(ctx context.Context, arg StaffListOrdersParams) ([]StaffListOrdersRow, error) {
	rows, err := q.db.Query(ctx, staffListOrders, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffListOrdersRow{}
	for rows.Next() {
		var i StaffListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.DiscountCodeID,
			&i.DiscountCodeSnapshot,
			&i.PickupAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
			&i.CustomerEmail,
			&i.CustomerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffListOrdersCount = `-- name: StaffListOrdersCount :one
SELECT COUNT(*)::bigint AS count
FROM orders o
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE (
    $1::order_status IS NULL
    OR o.status = $1::order_status
)
`

// StaffListOrdersCount
//
//	SELECT COUNT(*)::bigint AS count
//	FROM orders o
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE (
//	    $1::order_status IS NULL
//	    OR o.status = $1::order_status
//	)
func (q *Queries) StaffListOrdersCount(ctx context.Context, status *OrderStatus) (int64, error) {
	row := q.db.QueryRow(ctx, staffListOrdersCount, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumOrderItemQuantitiesByOrderIDs = `-- name: SumOrderItemQuantitiesByOrderIDs :many
SELECT order_id, COALESCE(SUM(quantity), 0)::bigint AS item_count
FROM order_items
WHERE order_id = ANY($1::uuid[])
GROUP BY order_id
`

type SumOrderItemQuantitiesByOrderIDsRow struct {
	OrderID   uuid.UUID `json:"orderId"`
	ItemCount int64     `json:"itemCount"`
}

// SumOrderItemQuantitiesByOrderIDs
//
//	SELECT order_id, COALESCE(SUM(quantity), 0)::bigint AS item_count
//	FROM order_items
//	WHERE order_id = ANY($1::uuid[])
//	GROUP BY order_id
func (q *Queries) SumOrderItemQuantitiesByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]SumOrderItemQuantitiesByOrderIDsRow, error) {
	rows, err := q.db.Query(ctx, sumOrderItemQuantitiesByOrderIDs, orderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumOrderItemQuantitiesByOrderIDsRow{}
	for rows.Next() {
		var i SumOrderItemQuantitiesByOrderIDsRow
		if err := rows.Scan(&i.OrderID, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1::order_status,
    updated_at = now()
WHERE id = $2
  AND status = $3::order_status
RETURNING
  id,
  user_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  discount_code_id,
  discount_code_snapshot,
  pickup_at,
  created_at,
  updated_at,
  code
`

type UpdateOrderStatusParams struct {
	ToStatus   OrderStatus `json:"toStatus"`
	ID         uuid.UUID   `json:"id"`
	FromStatus OrderStatus `json:"fromStatus"`
}

// UpdateOrderStatus
//
//	UPDATE orders
//	SET status = $1::order_status,
//	    updated_at = now()
//	WHERE id = $2
//	  AND status = $3::order_status
//	RETURNING
//	  id,
//	  user_id,
//	  status,
//	  subtotal_cents,
//	  discount_cents,
//	  total_cents,
//	  discount_code_id,
//	  discount_code_snapshot,
//	  pickup_at,
//	  created_at,
//	  updated_at,
//	  code
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.DiscountCodeID,
		&i.DiscountCodeSnapshot,
		&i.PickupAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
	)
	return i, err
}
