// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_event.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimUnpublishedOutboxEvents = `-- name: ClaimUnpublishedOutboxEvents :many
SELECT id, topic, audience, data, created_at
FROM outbox_events
WHERE published_at IS NULL
  AND created_at < clock_timestamp() - make_interval(secs => $1::double precision)
ORDER BY created_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimUnpublishedOutboxEventsParams struct {
	GraceSeconds float64 `json:"graceSeconds"`
	Limit        int32   `json:"limit"`
}

type ClaimUnpublishedOutboxEventsRow struct {
	ID        uuid.UUID       `json:"id"`
	Topic     string          `json:"topic"`
	Audience  json.RawMessage `json:"audience"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"createdAt"`
}

// Rows another sweeper already holds are skipped, not waited on, so two workers
// never claim the same row at once.
//
//	SELECT id, topic, audience, data, created_at
//	FROM outbox_events
//	WHERE published_at IS NULL
//	  AND created_at < clock_timestamp() - make_interval(secs => $1::double precision)
//	ORDER BY created_at ASC
//	LIMIT $2
//	FOR UPDATE SKIP LOCKED
func (q *Queries) ClaimUnpublishedOutboxEvents(ctx context.Context, arg ClaimUnpublishedOutboxEventsParams) ([]ClaimUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutboxEvents, arg.GraceSeconds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i ClaimUnpublishedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Audience,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePublishedOutboxEvents = `-- name: DeletePublishedOutboxEvents :execrows
DELETE FROM outbox_events
WHERE published_at < clock_timestamp() - make_interval(secs => $1::double precision)
`

// DeletePublishedOutboxEvents
//
//	DELETE FROM outbox_events
//	WHERE published_at < clock_timestamp() - make_interval(secs => $1::double precision)
func (q *Queries) DeletePublishedOutboxEvents(ctx context.Context, retentionSeconds float64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutboxEvents, retentionSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one

INSERT INTO outbox_events (id, topic, audience, data)
VALUES ($1, $2, $3, $4)
RETURNING created_at
`

type InsertOutboxEventParams struct {
	ID       uuid.UUID       `json:"id"`
	Topic    string          `json:"topic"`
	Audience json.RawMessage `json:"audience"`
	Data     json.RawMessage `json:"data"`
}

// Every time below comes from the database clock (created_at defaults to
// clock_timestamp()), so the API writing rows and the worker sweeping them never
// compare two hosts' clocks.
//
//	INSERT INTO outbox_events (id, topic, audience, data)
//	VALUES ($1, $2, $3, $4)
//	RETURNING created_at
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.Audience,
		arg.Data,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const markOutboxEventsPublished = `-- name: MarkOutboxEventsPublished :exec
UPDATE outbox_events
SET published_at = clock_timestamp()
WHERE id = ANY($1::uuid[])
  AND published_at IS NULL
`

// MarkOutboxEventsPublished
//
//	UPDATE outbox_events
//	SET published_at = clock_timestamp()
//	WHERE id = ANY($1::uuid[])
//	  AND published_at IS NULL
func (q *Queries) MarkOutboxEventsPublished(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventsPublished, ids)
	return err
}

const recordOutboxPublishFailure = `-- name: RecordOutboxPublishFailure :exec
UPDATE outbox_events
SET attempts = attempts + 1,
    last_error = $1::text
WHERE id = ANY($2::uuid[])
  AND published_at IS NULL
`

type RecordOutboxPublishFailureParams struct {
	LastError string      `json:"lastError"`
	Ids       []uuid.UUID `json:"ids"`
}

// RecordOutboxPublishFailure
//
//	UPDATE outbox_events
//	SET attempts = attempts + 1,
//	    last_error = $1::text
//	WHERE id = ANY($2::uuid[])
//	  AND published_at IS NULL
func (q *Queries) RecordOutboxPublishFailure(ctx context.Context, arg RecordOutboxPublishFailureParams) error {
	_, err := q.db.Exec(ctx, recordOutboxPublishFailure, arg.LastError, arg.Ids)
	return err
}
