// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, provider, provider_order_id, approve_url, amount_cents, currency)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (order_id) DO NOTHING
RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID         uuid.UUID       `json:"orderId"`
	Provider        PaymentProvider `json:"provider"`
	ProviderOrderID string          `json:"providerOrderId"`
	ApproveUrl      string          `json:"approveUrl"`
	AmountCents     int64           `json:"amountCents"`
	Currency        string          `json:"currency"`
}

// One payment per order: when the order already has one, nothing is written
// and no row comes back.
//
//	INSERT INTO payments (order_id, provider, provider_order_id, approve_url, amount_cents, currency)
//	VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  $6
//	)
//	ON CONFLICT (order_id) DO NOTHING
//	RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderOrderID,
		arg.ApproveUrl,
		arg.AmountCents,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ApproveUrl,
		&i.Status,
		&i.CaptureID,
		&i.AmountCents,
		&i.Currency,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
FROM payments
WHERE order_id = $1
`

// GetPaymentByOrderID
//
//	SELECT id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
//	FROM payments
//	WHERE order_id = $1
func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ApproveUrl,
		&i.Status,
		&i.CaptureID,
		&i.AmountCents,
		&i.Currency,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderOrderID = `-- name: GetPaymentByProviderOrderID :one
SELECT id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
FROM payments
WHERE provider = $1
  AND provider_order_id = $2
`

type GetPaymentByProviderOrderIDParams struct {
	Provider        PaymentProvider `json:"provider"`
	ProviderOrderID string          `json:"providerOrderId"`
}

// GetPaymentByProviderOrderID
//
//	SELECT id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
//	FROM payments
//	WHERE provider = $1
//	  AND provider_order_id = $2
func (q *Queries) GetPaymentByProviderOrderID(ctx context.Context, arg GetPaymentByProviderOrderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderOrderID, arg.Provider, arg.ProviderOrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ApproveUrl,
		&i.Status,
		&i.CaptureID,
		&i.AmountCents,
		&i.Currency,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPaymentCapture = `-- name: RecordPaymentCapture :one
UPDATE payments
SET status      = $1,
    capture_id  = $2,
    captured_at = CASE WHEN $1::payment_status = 'captured' THEN now() END,
    updated_at  = now()
WHERE id = $3
  AND status IN ('created', 'pending')
RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
`

type RecordPaymentCaptureParams struct {
	Status    PaymentStatus `json:"status"`
	CaptureID *string       `json:"captureId"`
	ID        uuid.UUID     `json:"id"`
}

// Records the provider's answer to a capture: taken, held for review, or a
// held one refused. A payment already taken or refused stays as it is.
//
//	UPDATE payments
//	SET status      = $1,
//	    capture_id  = $2,
//	    captured_at = CASE WHEN $1::payment_status = 'captured' THEN now() END,
//	    updated_at  = now()
//	WHERE id = $3
//	  AND status IN ('created', 'pending')
//	RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
func (q *Queries) RecordPaymentCapture(ctx context.Context, arg RecordPaymentCaptureParams) (Payment, error) {
	row := q.db.QueryRow(ctx, recordPaymentCapture, arg.Status, arg.CaptureID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ApproveUrl,
		&i.Status,
		&i.CaptureID,
		&i.AmountCents,
		&i.Currency,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restartPayment = `-- name: RestartPayment :one
UPDATE payments
SET provider_order_id = $1,
    approve_url       = $2,
    status            = 'created',
    capture_id        = NULL,
    updated_at        = now()
WHERE order_id = $3
  AND status = 'denied'
RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
`

type RestartPaymentParams struct {
	ProviderOrderID string    `json:"providerOrderId"`
	ApproveUrl      string    `json:"approveUrl"`
	OrderID         uuid.UUID `json:"orderId"`
}

// A payment the provider denied starts over with a new provider order.
//
//	UPDATE payments
//	SET provider_order_id = $1,
//	    approve_url       = $2,
//	    status            = 'created',
//	    capture_id        = NULL,
//	    updated_at        = now()
//	WHERE order_id = $3
//	  AND status = 'denied'
//	RETURNING id, order_id, provider, provider_order_id, approve_url, status, capture_id, amount_cents, currency, captured_at, created_at, updated_at
func (q *Queries) RestartPayment(ctx context.Context, arg RestartPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, restartPayment, arg.ProviderOrderID, arg.ApproveUrl, arg.OrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.ApproveUrl,
		&i.Status,
		&i.CaptureID,
		&i.AmountCents,
		&i.Currency,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
