// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_option.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createProductOptions = `-- name: CreateProductOptions :execrows
INSERT INTO product_options (product_id, option_group, label, price_delta_cents, sort_order, is_active)
SELECT $1, r.option_group, r.label, r.price_delta_cents, r.sort_order, r.is_active
FROM jsonb_to_recordset($2::jsonb) AS r (
  option_group product_option_group,
  label text,
  price_delta_cents bigint,
  sort_order smallint,
  is_active boolean
)
`

type CreateProductOptionsParams struct {
	ProductID uuid.UUID       `json:"productId"`
	Rows      json.RawMessage `json:"rows"`
}

// The options the manager added, in one statement.
//
//	INSERT INTO product_options (product_id, option_group, label, price_delta_cents, sort_order, is_active)
//	SELECT $1, r.option_group, r.label, r.price_delta_cents, r.sort_order, r.is_active
//	FROM jsonb_to_recordset($2::jsonb) AS r (
//	  option_group product_option_group,
//	  label text,
//	  price_delta_cents bigint,
//	  sort_order smallint,
//	  is_active boolean
//	)
func (q *Queries) CreateProductOptions(ctx context.Context, arg CreateProductOptionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createProductOptions, arg.ProductID, arg.Rows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProductOptions = `-- name: ListProductOptions :many
SELECT id, product_id, option_group, label, price_delta_cents, sort_order, is_active
FROM product_options
WHERE product_id = ANY($1::uuid[])
  AND deleted_at IS NULL
ORDER BY product_id, option_group, sort_order
`

type ListProductOptionsRow struct {
	ID              uuid.UUID          `json:"id"`
	ProductID       uuid.UUID          `json:"productId"`
	OptionGroup     ProductOptionGroup `json:"optionGroup"`
	Label           string             `json:"label"`
	PriceDeltaCents int64              `json:"priceDeltaCents"`
	SortOrder       int16              `json:"sortOrder"`
	IsActive        bool               `json:"isActive"`
}

// The options these products offer, retired ones left out, in the order a
// customer chooses them.
//
//	SELECT id, product_id, option_group, label, price_delta_cents, sort_order, is_active
//	FROM product_options
//	WHERE product_id = ANY($1::uuid[])
//	  AND deleted_at IS NULL
//	ORDER BY product_id, option_group, sort_order
func (q *Queries) ListProductOptions(ctx context.Context, productIds []uuid.UUID) ([]ListProductOptionsRow, error) {
	rows, err := q.db.Query(ctx, listProductOptions, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductOptionsRow{}
	for rows.Next() {
		var i ListProductOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OptionGroup,
			&i.Label,
			&i.PriceDeltaCents,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireProductOptions = `-- name: RetireProductOptions :exec
UPDATE product_options
SET deleted_at = now(),
    updated_at = now()
WHERE product_id = $1
  AND deleted_at IS NULL
  AND NOT (id = ANY($2::uuid[]))
`

type RetireProductOptionsParams struct {
	ProductID uuid.UUID   `json:"productId"`
	KeptIds   []uuid.UUID `json:"keptIds"`
}

// Retires the product's options the manager left out. Cart lines may still
// name them, so they stay as rows.
//
//	UPDATE product_options
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE product_id = $1
//	  AND deleted_at IS NULL
//	  AND NOT (id = ANY($2::uuid[]))
func (q *Queries) RetireProductOptions(ctx context.Context, arg RetireProductOptionsParams) error {
	_, err := q.db.Exec(ctx, retireProductOptions, arg.ProductID, arg.KeptIds)
	return err
}

const updateProductOptions = `-- name: UpdateProductOptions :execrows
UPDATE product_options o
SET option_group = r.option_group,
    label = r.label,
    price_delta_cents = r.price_delta_cents,
    sort_order = r.sort_order,
    is_active = r.is_active,
    updated_at = now()
FROM jsonb_to_recordset($2::jsonb) AS r (
  id uuid,
  option_group product_option_group,
  label text,
  price_delta_cents bigint,
  sort_order smallint,
  is_active boolean
)
WHERE o.id = r.id
  AND o.product_id = $1
  AND o.deleted_at IS NULL
`

type UpdateProductOptionsParams struct {
	ProductID uuid.UUID       `json:"productId"`
	Rows      json.RawMessage `json:"rows"`
}

// The manager's edits to options the product already has, in one statement.
//
//	UPDATE product_options o
//	SET option_group = r.option_group,
//	    label = r.label,
//	    price_delta_cents = r.price_delta_cents,
//	    sort_order = r.sort_order,
//	    is_active = r.is_active,
//	    updated_at = now()
//	FROM jsonb_to_recordset($2::jsonb) AS r (
//	  id uuid,
//	  option_group product_option_group,
//	  label text,
//	  price_delta_cents bigint,
//	  sort_order smallint,
//	  is_active boolean
//	)
//	WHERE o.id = r.id
//	  AND o.product_id = $1
//	  AND o.deleted_at IS NULL
func (q *Queries) UpdateProductOptions(ctx context.Context, arg UpdateProductOptionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProductOptions, arg.ProductID, arg.Rows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
