// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const catalogGetProductByID = `-- name: CatalogGetProductByID :one
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.price_cents,
    p.is_customizable,
    p.sold_out_on,
    c.name AS category_name,
    c.slug AS category_slug
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE p.id = $1
  AND p.deleted_at IS NULL
  AND p.is_active = true
`

type CatalogGetProductByIDRow struct {
	ID             uuid.UUID  `json:"id"`
	CategoryID     uuid.UUID  `json:"categoryId"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	PriceCents     int64      `json:"priceCents"`
	IsCustomizable bool       `json:"isCustomizable"`
	SoldOutOn      *time.Time `json:"soldOutOn"`
	CategoryName   string     `json:"categoryName"`
	CategorySlug   string     `json:"categorySlug"`
}

// CatalogGetProductByID
//
//	SELECT
//	    p.id,
//	    p.category_id,
//	    p.name,
//	    p.slug,
//	    p.description,
//	    p.price_cents,
//	    p.is_customizable,
//	    p.sold_out_on,
//	    c.name AS category_name,
//	    c.slug AS category_slug
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE p.id = $1
//	  AND p.deleted_at IS NULL
//	  AND p.is_active = true
func (q *Queries) CatalogGetProductByID(ctx context.Context, id uuid.UUID) (CatalogGetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, catalogGetProductByID, id)
	var i CatalogGetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.IsCustomizable,
		&i.SoldOutOn,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const catalogGetProductsByIDs = `-- name: CatalogGetProductsByIDs :many
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.price_cents,
    p.is_customizable,
    p.sold_out_on,
    c.name AS category_name,
    c.slug AS category_slug
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE p.id = ANY($1::uuid[])
  AND p.deleted_at IS NULL
  AND p.is_active = true
`

type CatalogGetProductsByIDsRow struct {
	ID             uuid.UUID  `json:"id"`
	CategoryID     uuid.UUID  `json:"categoryId"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	PriceCents     int64      `json:"priceCents"`
	IsCustomizable bool       `json:"isCustomizable"`
	SoldOutOn      *time.Time `json:"soldOutOn"`
	CategoryName   string     `json:"categoryName"`
	CategorySlug   string     `json:"categorySlug"`
}

// CatalogGetProductsByIDs
//
//	SELECT
//	    p.id,
//	    p.category_id,
//	    p.name,
//	    p.slug,
//	    p.description,
//	    p.price_cents,
//	    p.is_customizable,
//	    p.sold_out_on,
//	    c.name AS category_name,
//	    c.slug AS category_slug
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE p.id = ANY($1::uuid[])
//	  AND p.deleted_at IS NULL
//	  AND p.is_active = true
func (q *Queries) CatalogGetProductsByIDs(ctx context.Context, productIds []uuid.UUID) ([]CatalogGetProductsByIDsRow, error) {
	rows, err := q.db.Query(ctx, catalogGetProductsByIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogGetProductsByIDsRow{}
	for rows.Next() {
		var i CatalogGetProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceCents,
			&i.IsCustomizable,
			&i.SoldOutOn,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListProducts = `-- name: CatalogListProducts :many
SELECT
    page.id,
    page.category_id,
    page.name,
    page.slug,
    page.description,
    page.price_cents,
    page.is_customizable,
    page.sold_out_on,
    page.category_name,
    page.category_slug,
    COALESCE(img.urls, ARRAY[]::text[])::text[] AS image_urls
FROM (
    SELECT
        p.id,
        p.category_id,
        p.name,
        p.slug,
        p.description,
        p.price_cents,
        p.is_customizable,
        p.sold_out_on,
        c.name AS category_name,
        c.slug AS category_slug,
        c.sort_order AS category_sort_order
    FROM products p
    INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
    WHERE p.deleted_at IS NULL
      AND p.is_active = true
      AND (
        $3::uuid IS NULL
        OR p.category_id = $3::uuid
      )
      AND (
        $4::text IS NULL
        OR p.name ILIKE '%' || $4::text || '%'
        OR p.slug ILIKE '%' || $4::text || '%'
      )
    ORDER BY c.sort_order ASC, p.name ASC
    LIMIT $1 OFFSET $2
) page
LEFT JOIN LATERAL (
    SELECT array_agg(pi.image_url ORDER BY pi.sort_order) AS urls
    FROM product_images pi
    WHERE pi.product_id = page.id
) img ON true
ORDER BY page.category_sort_order ASC, page.name ASC
`

type CatalogListProductsParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	CategoryID *uuid.UUID `json:"categoryId"`
	Search     *string    `json:"search"`
}

type CatalogListProductsRow struct {
	ID             uuid.UUID  `json:"id"`
	CategoryID     uuid.UUID  `json:"categoryId"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	Description    *string    `json:"description"`
	PriceCents     int64      `json:"priceCents"`
	IsCustomizable bool       `json:"isCustomizable"`
	SoldOutOn      *time.Time `json:"soldOutOn"`
	CategoryName   string     `json:"categoryName"`
	CategorySlug   string     `json:"categorySlug"`
	ImageUrls      []string   `json:"imageUrls"`
}

// The page is cut first and the gallery gathered after: fetching images
// separately costs a second round trip, and aggregating before LIMIT would run
// once per row the filter matches rather than once per row shown.
//
//	SELECT
//	    page.id,
//	    page.category_id,
//	    page.name,
//	    page.slug,
//	    page.description,
//	    page.price_cents,
//	    page.is_customizable,
//	    page.sold_out_on,
//	    page.category_name,
//	    page.category_slug,
//	    COALESCE(img.urls, ARRAY[]::text[])::text[] AS image_urls
//	FROM (
//	    SELECT
//	        p.id,
//	        p.category_id,
//	        p.name,
//	        p.slug,
//	        p.description,
//	        p.price_cents,
//	        p.is_customizable,
//	        p.sold_out_on,
//	        c.name AS category_name,
//	        c.slug AS category_slug,
//	        c.sort_order AS category_sort_order
//	    FROM products p
//	    INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	    WHERE p.deleted_at IS NULL
//	      AND p.is_active = true
//	      AND (
//	        $3::uuid IS NULL
//	        OR p.category_id = $3::uuid
//	      )
//	      AND (
//	        $4::text IS NULL
//	        OR p.name ILIKE '%' || $4::text || '%'
//	        OR p.slug ILIKE '%' || $4::text || '%'
//	      )
//	    ORDER BY c.sort_order ASC, p.name ASC
//	    LIMIT $1 OFFSET $2
//	) page
//	LEFT JOIN LATERAL (
//	    SELECT array_agg(pi.image_url ORDER BY pi.sort_order) AS urls
//	    FROM product_images pi
//	    WHERE pi.product_id = page.id
//	) img ON true
//	ORDER BY page.category_sort_order ASC, page.name ASC
func (q *Queries) CatalogListProducts(ctx context.Context, arg CatalogListProductsParams) ([]CatalogListProductsRow, error) {
	rows, err := q.db.Query(ctx, catalogListProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogListProductsRow{}
	for rows.Next() {
		var i CatalogListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceCents,
			&i.IsCustomizable,
			&i.SoldOutOn,
			&i.CategoryName,
			&i.CategorySlug,
			&i.ImageUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalogListProductsCount = `-- name: CatalogListProductsCount :one
SELECT count(*)::bigint AS count
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE p.deleted_at IS NULL
  AND p.is_active = true
  AND (
    $1::uuid IS NULL
    OR p.category_id = $1::uuid
  )
  AND (
    $2::text IS NULL
    OR p.name ILIKE '%' || $2::text || '%'
    OR p.slug ILIKE '%' || $2::text || '%'
  )
`

type CatalogListProductsCountParams struct {
	CategoryID *uuid.UUID `json:"categoryId"`
	Search     *string    `json:"search"`
}

// CatalogListProductsCount
//
//	SELECT count(*)::bigint AS count
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE p.deleted_at IS NULL
//	  AND p.is_active = true
//	  AND (
//	    $1::uuid IS NULL
//	    OR p.category_id = $1::uuid
//	  )
//	  AND (
//	    $2::text IS NULL
//	    OR p.name ILIKE '%' || $2::text || '%'
//	    OR p.slug ILIKE '%' || $2::text || '%'
//	  )
func (q *Queries) CatalogListProductsCount(ctx context.Context, arg CatalogListProductsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, catalogListProductsCount, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_id, name, slug, description, price_cents, is_active, lead_time_minutes, is_customizable)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
`

type CreateProductParams struct {
	CategoryID      uuid.UUID `json:"categoryId"`
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	Description     *string   `json:"description"`
	PriceCents      int64     `json:"priceCents"`
	IsActive        bool      `json:"isActive"`
	LeadTimeMinutes int32     `json:"leadTimeMinutes"`
	IsCustomizable  bool      `json:"isCustomizable"`
}

// CreateProduct
//
//	INSERT INTO products (category_id, name, slug, description, price_cents, is_active, lead_time_minutes, is_customizable)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
//	RETURNING id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PriceCents,
		arg.IsActive,
		arg.LeadTimeMinutes,
		arg.IsCustomizable,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LeadTimeMinutes,
		&i.IsCustomizable,
		&i.SoldOutOn,
	)
	return i, err
}

const getFulfillmentOf = `-- name: GetFulfillmentOf :one
WITH line_products AS (
  SELECT unnest($2::uuid[]) AS product_id
  UNION
  SELECT ci.product_id
  FROM combo_items ci
  WHERE ci.combo_id = ANY($3::uuid[])
)
SELECT
  COALESCE(bool_or(c.station = 'kitchen'::station), false)::bool AS has_kitchen_items,
  COALESCE(max(p.lead_time_minutes), 0)::int AS lead_minutes,
  COALESCE(bool_or(p.sold_out_on = $1::date), false)::bool AS sold_out_today
FROM line_products lp
INNER JOIN products p ON p.id = lp.product_id AND p.deleted_at IS NULL
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
`

type GetFulfillmentOfParams struct {
	Today      time.Time   `json:"today"`
	ProductIds []uuid.UUID `json:"productIds"`
	ComboIds   []uuid.UUID `json:"comboIds"`
}

type GetFulfillmentOfRow struct {
	HasKitchenItems bool  `json:"hasKitchenItems"`
	LeadMinutes     int32 `json:"leadMinutes"`
	SoldOutToday    bool  `json:"soldOutToday"`
}

// What these products and combos ask of the bakery, combos counted by what
// they hold: whether any comes from the kitchen, the longest notice any needs,
// and whether one ran out today (a mark is only ever made for the day it is
// made on, so no other day is ever sold out ahead).
//
//	WITH line_products AS (
//	  SELECT unnest($2::uuid[]) AS product_id
//	  UNION
//	  SELECT ci.product_id
//	  FROM combo_items ci
//	  WHERE ci.combo_id = ANY($3::uuid[])
//	)
//	SELECT
//	  COALESCE(bool_or(c.station = 'kitchen'::station), false)::bool AS has_kitchen_items,
//	  COALESCE(max(p.lead_time_minutes), 0)::int AS lead_minutes,
//	  COALESCE(bool_or(p.sold_out_on = $1::date), false)::bool AS sold_out_today
//	FROM line_products lp
//	INNER JOIN products p ON p.id = lp.product_id AND p.deleted_at IS NULL
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
func (q *Queries) GetFulfillmentOf(ctx context.Context, arg GetFulfillmentOfParams) (GetFulfillmentOfRow, error) {
	row := q.db.QueryRow(ctx, getFulfillmentOf, arg.Today, arg.ProductIds, arg.ComboIds)
	var i GetFulfillmentOfRow
	err := row.Scan(&i.HasKitchenItems, &i.LeadMinutes, &i.SoldOutToday)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
FROM products
WHERE id = $1
  AND deleted_at IS NULL
`

// GetProductByID
//
//	SELECT id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
//	FROM products
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LeadTimeMinutes,
		&i.IsCustomizable,
		&i.SoldOutOn,
	)
	return i, err
}

const managerGetProductByID = `-- name: ManagerGetProductByID :one
SELECT
    p.id,
    p.category_id,
    p.name,
    p.slug,
    p.description,
    p.price_cents,
    p.is_active,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    p.lead_time_minutes,
    p.is_customizable,
    c.name AS category_name
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type ManagerGetProductByIDRow struct {
	ID              uuid.UUID  `json:"id"`
	CategoryID      uuid.UUID  `json:"categoryId"`
	Name            string     `json:"name"`
	Slug            string     `json:"slug"`
	Description     *string    `json:"description"`
	PriceCents      int64      `json:"priceCents"`
	IsActive        bool       `json:"isActive"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	DeletedAt       *time.Time `json:"deletedAt"`
	LeadTimeMinutes int32      `json:"leadTimeMinutes"`
	IsCustomizable  bool       `json:"isCustomizable"`
	CategoryName    string     `json:"categoryName"`
}

// ManagerGetProductByID
//
//	SELECT
//	    p.id,
//	    p.category_id,
//	    p.name,
//	    p.slug,
//	    p.description,
//	    p.price_cents,
//	    p.is_active,
//	    p.created_at,
//	    p.updated_at,
//	    p.deleted_at,
//	    p.lead_time_minutes,
//	    p.is_customizable,
//	    c.name AS category_name
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
//	WHERE p.id = $1
//	  AND p.deleted_at IS NULL
func (q *Queries) ManagerGetProductByID(ctx context.Context, id uuid.UUID) (ManagerGetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, managerGetProductByID, id)
	var i ManagerGetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LeadTimeMinutes,
		&i.IsCustomizable,
		&i.CategoryName,
	)
	return i, err
}

const managerListProducts = `-- name: ManagerListProducts :many
SELECT
    page.id,
    page.category_id,
    page.name,
    page.slug,
    page.description,
    page.price_cents,
    page.is_active,
    page.created_at,
    page.updated_at,
    page.deleted_at,
    page.lead_time_minutes,
    page.is_customizable,
    page.category_name,
    COALESCE(img.urls, ARRAY[]::text[])::text[] AS image_urls
FROM (
    SELECT
        p.id,
        p.category_id,
        p.name,
        p.slug,
        p.description,
        p.price_cents,
        p.is_active,
        p.created_at,
        p.updated_at,
        p.deleted_at,
        p.lead_time_minutes,
        p.is_customizable,
        c.name AS category_name
    FROM products p
    INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
    WHERE p.deleted_at IS NULL
      AND (
        $3::uuid IS NULL
        OR p.category_id = $3::uuid
      )
      AND (
        $4::text IS NULL
        OR p.name ILIKE '%' || $4::text || '%'
        OR p.slug ILIKE '%' || $4::text || '%'
      )
    ORDER BY p.name ASC
    LIMIT $1 OFFSET $2
) page
LEFT JOIN LATERAL (
    SELECT array_agg(pi.image_url ORDER BY pi.sort_order) AS urls
    FROM product_images pi
    WHERE pi.product_id = page.id
) img ON true
ORDER BY page.name ASC
`

type ManagerListProductsParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	CategoryID *uuid.UUID `json:"categoryId"`
	Search     *string    `json:"search"`
}

type ManagerListProductsRow struct {
	ID              uuid.UUID  `json:"id"`
	CategoryID      uuid.UUID  `json:"categoryId"`
	Name            string     `json:"name"`
	Slug            string     `json:"slug"`
	Description     *string    `json:"description"`
	PriceCents      int64      `json:"priceCents"`
	IsActive        bool       `json:"isActive"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
	DeletedAt       *time.Time `json:"deletedAt"`
	LeadTimeMinutes int32      `json:"leadTimeMinutes"`
	IsCustomizable  bool       `json:"isCustomizable"`
	CategoryName    string     `json:"categoryName"`
	ImageUrls       []string   `json:"imageUrls"`
}

// ManagerListProducts
//
//	SELECT
//	    page.id,
//	    page.category_id,
//	    page.name,
//	    page.slug,
//	    page.description,
//	    page.price_cents,
//	    page.is_active,
//	    page.created_at,
//	    page.updated_at,
//	    page.deleted_at,
//	    page.lead_time_minutes,
//	    page.is_customizable,
//	    page.category_name,
//	    COALESCE(img.urls, ARRAY[]::text[])::text[] AS image_urls
//	FROM (
//	    SELECT
//	        p.id,
//	        p.category_id,
//	        p.name,
//	        p.slug,
//	        p.description,
//	        p.price_cents,
//	        p.is_active,
//	        p.created_at,
//	        p.updated_at,
//	        p.deleted_at,
//	        p.lead_time_minutes,
//	        p.is_customizable,
//	        c.name AS category_name
//	    FROM products p
//	    INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
//	    WHERE p.deleted_at IS NULL
//	      AND (
//	        $3::uuid IS NULL
//	        OR p.category_id = $3::uuid
//	      )
//	      AND (
//	        $4::text IS NULL
//	        OR p.name ILIKE '%' || $4::text || '%'
//	        OR p.slug ILIKE '%' || $4::text || '%'
//	      )
//	    ORDER BY p.name ASC
//	    LIMIT $1 OFFSET $2
//	) page
//	LEFT JOIN LATERAL (
//	    SELECT array_agg(pi.image_url ORDER BY pi.sort_order) AS urls
//	    FROM product_images pi
//	    WHERE pi.product_id = page.id
//	) img ON true
//	ORDER BY page.name ASC
func (q *Queries) ManagerListProducts(ctx context.Context, arg ManagerListProductsParams) ([]ManagerListProductsRow, error) {
	rows, err := q.db.Query(ctx, managerListProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagerListProductsRow{}
	for rows.Next() {
		var i ManagerListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceCents,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LeadTimeMinutes,
			&i.IsCustomizable,
			&i.CategoryName,
			&i.ImageUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListProductsCount = `-- name: ManagerListProductsCount :one
SELECT count(*)::bigint AS count
FROM products p
WHERE p.deleted_at IS NULL
  AND (
    $1::uuid IS NULL
    OR p.category_id = $1::uuid
  )
  AND (
    $2::text IS NULL
    OR p.name ILIKE '%' || $2::text || '%'
    OR p.slug ILIKE '%' || $2::text || '%'
  )
`

type ManagerListProductsCountParams struct {
	CategoryID *uuid.UUID `json:"categoryId"`
	Search     *string    `json:"search"`
}

// ManagerListProductsCount
//
//	SELECT count(*)::bigint AS count
//	FROM products p
//	WHERE p.deleted_at IS NULL
//	  AND (
//	    $1::uuid IS NULL
//	    OR p.category_id = $1::uuid
//	  )
//	  AND (
//	    $2::text IS NULL
//	    OR p.name ILIKE '%' || $2::text || '%'
//	    OR p.slug ILIKE '%' || $2::text || '%'
//	  )
func (q *Queries) ManagerListProductsCount(ctx context.Context, arg ManagerListProductsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, managerListProductsCount, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setProductSoldOut = `-- name: SetProductSoldOut :one
UPDATE products p
SET sold_out_on = $1,
    updated_at  = now()
FROM categories c
WHERE p.id = $2
  AND p.deleted_at IS NULL
  AND p.is_active = true
  AND c.id = p.category_id
  AND c.deleted_at IS NULL
RETURNING p.id, p.name, c.name AS category_name, c.station, p.sold_out_on
`

type SetProductSoldOutParams struct {
	SoldOutOn *time.Time `json:"soldOutOn"`
	ID        uuid.UUID  `json:"id"`
}

type SetProductSoldOutRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	CategoryName string     `json:"categoryName"`
	Station      Station    `json:"station"`
	SoldOutOn    *time.Time `json:"soldOutOn"`
}

// Marks a product sold out on a bakery day, or back with NULL.
//
//	UPDATE products p
//	SET sold_out_on = $1,
//	    updated_at  = now()
//	FROM categories c
//	WHERE p.id = $2
//	  AND p.deleted_at IS NULL
//	  AND p.is_active = true
//	  AND c.id = p.category_id
//	  AND c.deleted_at IS NULL
//	RETURNING p.id, p.name, c.name AS category_name, c.station, p.sold_out_on
func (q *Queries) SetProductSoldOut(ctx context.Context, arg SetProductSoldOutParams) (SetProductSoldOutRow, error) {
	row := q.db.QueryRow(ctx, setProductSoldOut, arg.SoldOutOn, arg.ID)
	var i SetProductSoldOutRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryName,
		&i.Station,
		&i.SoldOutOn,
	)
	return i, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SoftDeleteProduct
//
//	UPDATE products
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staffListProducts = `-- name: StaffListProducts :many
SELECT
  p.id,
  p.name,
  c.name AS category_name,
  c.station,
  p.sold_out_on
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.is_active = true
  AND (
    $1::date IS NULL
    OR p.sold_out_on = $1::date
  )
ORDER BY c.sort_order ASC, p.name ASC, p.id ASC
LIMIT $3 OFFSET $2
`

type StaffListProductsParams struct {
	SoldOutOn *time.Time `json:"soldOutOn"`
	Offset    int32      `json:"offset"`
	Limit     int32      `json:"limit"`
}

type StaffListProductsRow struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	CategoryName string     `json:"categoryName"`
	Station      Station    `json:"station"`
	SoldOutOn    *time.Time `json:"soldOutOn"`
}

// What the counter can mark sold out, by category and name, with the day
// each last ran out; sold_out_on narrows the page to those out that day.
//
//	SELECT
//	  p.id,
//	  p.name,
//	  c.name AS category_name,
//	  c.station,
//	  p.sold_out_on
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
//	WHERE p.deleted_at IS NULL
//	  AND p.is_active = true
//	  AND (
//	    $1::date IS NULL
//	    OR p.sold_out_on = $1::date
//	  )
//	ORDER BY c.sort_order ASC, p.name ASC, p.id ASC
//	LIMIT $3 OFFSET $2
func (q *Queries) StaffListProducts(ctx context.Context, arg StaffListProductsParams) ([]StaffListProductsRow, error) {
	rows, err := q.db.Query(ctx, staffListProducts, arg.SoldOutOn, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffListProductsRow{}
	for rows.Next() {
		var i StaffListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryName,
			&i.Station,
			&i.SoldOutOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staffListProductsCount = `-- name: StaffListProductsCount :one
SELECT count(*)::bigint AS count
FROM products p
INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND p.is_active = true
  AND (
    $1::date IS NULL
    OR p.sold_out_on = $1::date
  )
`

// StaffListProductsCount
//
//	SELECT count(*)::bigint AS count
//	FROM products p
//	INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
//	WHERE p.deleted_at IS NULL
//	  AND p.is_active = true
//	  AND (
//	    $1::date IS NULL
//	    OR p.sold_out_on = $1::date
//	  )
func (q *Queries) StaffListProductsCount(ctx context.Context, soldOutOn *time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, staffListProductsCount, soldOutOn)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id  = $2,
    name         = $3,
    slug         = $4,
    description  = $5,
    price_cents  = $6,
    is_active    = $7,
    lead_time_minutes = $8,
    is_customizable = $9,
    updated_at   = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
`

type UpdateProductParams struct {
	ID              uuid.UUID `json:"id"`
	CategoryID      uuid.UUID `json:"categoryId"`
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	Description     *string   `json:"description"`
	PriceCents      int64     `json:"priceCents"`
	IsActive        bool      `json:"isActive"`
	LeadTimeMinutes int32     `json:"leadTimeMinutes"`
	IsCustomizable  bool      `json:"isCustomizable"`
}

// UpdateProduct
//
//	UPDATE products
//	SET category_id  = $2,
//	    name         = $3,
//	    slug         = $4,
//	    description  = $5,
//	    price_cents  = $6,
//	    is_active    = $7,
//	    lead_time_minutes = $8,
//	    is_customizable = $9,
//	    updated_at   = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	RETURNING id, category_id, name, slug, description, price_cents, is_active, created_at, updated_at, deleted_at, lead_time_minutes, is_customizable, sold_out_on
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PriceCents,
		arg.IsActive,
		arg.LeadTimeMinutes,
		arg.IsCustomizable,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LeadTimeMinutes,
		&i.IsCustomizable,
		&i.SoldOutOn,
	)
	return i, err
}
