// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_image.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteProductImagesByProductID = `-- name: DeleteProductImagesByProductID :exec
DELETE FROM product_images
WHERE product_id = $1
`

// DeleteProductImagesByProductID
//
//	DELETE FROM product_images
//	WHERE product_id = $1
func (q *Queries) DeleteProductImagesByProductID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImagesByProductID, productID)
	return err
}

const insertProductImage = `-- name: InsertProductImage :one
INSERT INTO product_images (product_id, sort_order, image_url)
VALUES ($1, $2, $3)
RETURNING id, product_id, sort_order, image_url, created_at, updated_at
`

type InsertProductImageParams struct {
	ProductID uuid.UUID `json:"productId"`
	SortOrder int16     `json:"sortOrder"`
	ImageUrl  string    `json:"imageUrl"`
}

// InsertProductImage
//
//	INSERT INTO product_images (product_id, sort_order, image_url)
//	VALUES ($1, $2, $3)
//	RETURNING id, product_id, sort_order, image_url, created_at, updated_at
func (q *Queries) InsertProductImage(ctx context.Context, arg InsertProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, insertProductImage, arg.ProductID, arg.SortOrder, arg.ImageUrl)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SortOrder,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductImagesByProductID = `-- name: ListProductImagesByProductID :many
SELECT image_url, sort_order
FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC
`

type ListProductImagesByProductIDRow struct {
	ImageUrl  string `json:"imageUrl"`
	SortOrder int16  `json:"sortOrder"`
}

// ListProductImagesByProductID
//
//	SELECT image_url, sort_order
//	FROM product_images
//	WHERE product_id = $1
//	ORDER BY sort_order ASC
func (q *Queries) ListProductImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ListProductImagesByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductImagesByProductIDRow{}
	for rows.Next() {
		var i ListProductImagesByProductIDRow
		if err := rows.Scan(&i.ImageUrl, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
