// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotion.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPromotionRecipients = `-- name: CountPromotionRecipients :one
SELECT count(*)::bigint
FROM customer_profiles cp
JOIN users u ON u.id = cp.user_id
WHERE cp.marketing_consent_at IS NOT NULL
  AND u.deleted_at IS NULL
  AND u.email_verified_at IS NOT NULL
  AND u.role = 'customer'::user_role
`

// CountPromotionRecipients
//
//	SELECT count(*)::bigint
//	FROM customer_profiles cp
//	JOIN users u ON u.id = cp.user_id
//	WHERE cp.marketing_consent_at IS NOT NULL
//	  AND u.deleted_at IS NULL
//	  AND u.email_verified_at IS NOT NULL
//	  AND u.role = 'customer'::user_role
func (q *Queries) CountPromotionRecipients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPromotionRecipients)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPromotions = `-- name: CountPromotions :one
SELECT count(*)::bigint FROM promotions
`

// CountPromotions
//
//	SELECT count(*)::bigint FROM promotions
func (q *Queries) CountPromotions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPromotions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPromotion = `-- name: CreatePromotion :one
WITH created AS (
  INSERT INTO promotions (subject, body, created_by)
  VALUES ($1, $2, $3)
  RETURNING id, subject, status, recipient_count, created_at, created_by
)
SELECT
  c.id,
  c.subject,
  c.status,
  c.recipient_count,
  c.created_at,
  sp.full_name AS sender_name
FROM created c
LEFT JOIN staff_profiles sp ON sp.user_id = c.created_by
`

type CreatePromotionParams struct {
	Subject   string    `json:"subject"`
	Body      string    `json:"body"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

type CreatePromotionRow struct {
	ID             uuid.UUID       `json:"id"`
	Subject        string          `json:"subject"`
	Status         PromotionStatus `json:"status"`
	RecipientCount *int32          `json:"recipientCount"`
	CreatedAt      time.Time       `json:"createdAt"`
	SenderName     *string         `json:"senderName"`
}

// Records a promotion to send, and returns it as managers list it.
//
//	WITH created AS (
//	  INSERT INTO promotions (subject, body, created_by)
//	  VALUES ($1, $2, $3)
//	  RETURNING id, subject, status, recipient_count, created_at, created_by
//	)
//	SELECT
//	  c.id,
//	  c.subject,
//	  c.status,
//	  c.recipient_count,
//	  c.created_at,
//	  sp.full_name AS sender_name
//	FROM created c
//	LEFT JOIN staff_profiles sp ON sp.user_id = c.created_by
func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) (CreatePromotionRow, error) {
	row := q.db.QueryRow(ctx, createPromotion, arg.Subject, arg.Body, arg.CreatedBy)
	var i CreatePromotionRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Status,
		&i.RecipientCount,
		&i.CreatedAt,
		&i.SenderName,
	)
	return i, err
}

const getPromotionDelivery = `-- name: GetPromotionDelivery :one
SELECT p.subject, p.body, u.email, cp.display_name
FROM promotions p
CROSS JOIN customer_profiles cp
JOIN users u ON u.id = cp.user_id
WHERE p.id = $1
  AND cp.user_id = $2
  AND cp.marketing_consent_at IS NOT NULL
  AND u.deleted_at IS NULL
  AND u.email_verified_at IS NOT NULL
  AND u.role = 'customer'::user_role
`

type GetPromotionDeliveryParams struct {
	PromotionID uuid.UUID `json:"promotionId"`
	UserID      uuid.UUID `json:"userId"`
}

type GetPromotionDeliveryRow struct {
	Subject     string  `json:"subject"`
	Body        string  `json:"body"`
	Email       string  `json:"email"`
	DisplayName *string `json:"displayName"`
}

// What one customer's email of a promotion says and where it goes, while
// promotions still go to them.
//
//	SELECT p.subject, p.body, u.email, cp.display_name
//	FROM promotions p
//	CROSS JOIN customer_profiles cp
//	JOIN users u ON u.id = cp.user_id
//	WHERE p.id = $1
//	  AND cp.user_id = $2
//	  AND cp.marketing_consent_at IS NOT NULL
//	  AND u.deleted_at IS NULL
//	  AND u.email_verified_at IS NOT NULL
//	  AND u.role = 'customer'::user_role
func (q *Queries) GetPromotionDelivery(ctx context.Context, arg GetPromotionDeliveryParams) (GetPromotionDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getPromotionDelivery, arg.PromotionID, arg.UserID)
	var i GetPromotionDeliveryRow
	err := row.Scan(
		&i.Subject,
		&i.Body,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const getPromotionStatus = `-- name: GetPromotionStatus :one
SELECT status
FROM promotions
WHERE id = $1
`

// GetPromotionStatus
//
//	SELECT status
//	FROM promotions
//	WHERE id = $1
func (q *Queries) GetPromotionStatus(ctx context.Context, id uuid.UUID) (PromotionStatus, error) {
	row := q.db.QueryRow(ctx, getPromotionStatus, id)
	var status PromotionStatus
	err := row.Scan(&status)
	return status, err
}

const listPromotionRecipients = `-- name: ListPromotionRecipients :many
SELECT cp.user_id
FROM customer_profiles cp
JOIN users u ON u.id = cp.user_id
WHERE cp.marketing_consent_at IS NOT NULL
  AND u.deleted_at IS NULL
  AND u.email_verified_at IS NOT NULL
  AND u.role = 'customer'::user_role
  AND ($1::uuid IS NULL OR cp.user_id > $1::uuid)
ORDER BY cp.user_id
LIMIT $2
`

type ListPromotionRecipientsParams struct {
	AfterID *uuid.UUID `json:"afterId"`
	Limit   int32      `json:"limit"`
}

// A page of the customers promotions go to, by id after after_id: open
// accounts with a confirmed address whose holder agreed to promotions.
//
//	SELECT cp.user_id
//	FROM customer_profiles cp
//	JOIN users u ON u.id = cp.user_id
//	WHERE cp.marketing_consent_at IS NOT NULL
//	  AND u.deleted_at IS NULL
//	  AND u.email_verified_at IS NOT NULL
//	  AND u.role = 'customer'::user_role
//	  AND ($1::uuid IS NULL OR cp.user_id > $1::uuid)
//	ORDER BY cp.user_id
//	LIMIT $2
func (q *Queries) ListPromotionRecipients(ctx context.Context, arg ListPromotionRecipientsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPromotionRecipients, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotions = `-- name: ListPromotions :many
SELECT
  p.id,
  p.subject,
  p.status,
  p.recipient_count,
  p.created_at,
  sp.full_name AS sender_name
FROM promotions p
LEFT JOIN staff_profiles sp ON sp.user_id = p.created_by
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $1
`

type ListPromotionsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type ListPromotionsRow struct {
	ID             uuid.UUID       `json:"id"`
	Subject        string          `json:"subject"`
	Status         PromotionStatus `json:"status"`
	RecipientCount *int32          `json:"recipientCount"`
	CreatedAt      time.Time       `json:"createdAt"`
	SenderName     *string         `json:"senderName"`
}

// A page of the promotions sent, latest first, with the manager who sent each.
//
//	SELECT
//	  p.id,
//	  p.subject,
//	  p.status,
//	  p.recipient_count,
//	  p.created_at,
//	  sp.full_name AS sender_name
//	FROM promotions p
//	LEFT JOIN staff_profiles sp ON sp.user_id = p.created_by
//	ORDER BY p.created_at DESC, p.id DESC
//	LIMIT $2 OFFSET $1
func (q *Queries) ListPromotions(ctx context.Context, arg ListPromotionsParams) ([]ListPromotionsRow, error) {
	rows, err := q.db.Query(ctx, listPromotions, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromotionsRow{}
	for rows.Next() {
		var i ListPromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Status,
			&i.RecipientCount,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPromotionSent = `-- name: MarkPromotionSent :execrows
UPDATE promotions
SET status = 'sent'::promotion_status,
    recipient_count = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'sending'::promotion_status
`

type MarkPromotionSentParams struct {
	RecipientCount *int32    `json:"recipientCount"`
	ID             uuid.UUID `json:"id"`
}

// Records how many customers a promotion was queued for, once.
//
//	UPDATE promotions
//	SET status = 'sent'::promotion_status,
//	    recipient_count = $1,
//	    updated_at = now()
//	WHERE id = $2
//	  AND status = 'sending'::promotion_status
func (q *Queries) MarkPromotionSent(ctx context.Context, arg MarkPromotionSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPromotionSent, arg.RecipientCount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
