// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	//AdminCreate
	//
	//  INSERT INTO users (email, password_hash, role, must_change_password)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
	AdminCreate(ctx context.Context, arg AdminCreateParams) (User, error)
	//AdminList
	//
	//  SELECT
	//      u.id,
	//      u.email,
	//      u.role,
	//      u.email_verified_at,
	//      u.must_change_password,
	//      u.created_at,
	//      u.updated_at,
	//      u.deleted_at,
	//      cp.display_name,
	//      COALESCE(sp.full_name, ap.full_name, '') AS full_name,
	//      COALESCE(sp.phone, ap.phone, cp.phone) AS phone,
	//      sp.employee_code
	//  FROM users u
	//  LEFT JOIN customer_profiles cp ON cp.user_id = u.id
	//  LEFT JOIN staff_profiles sp ON sp.user_id = u.id
	//  LEFT JOIN admin_profiles ap ON ap.user_id = u.id
	//  WHERE u.deleted_at IS NULL
	//    AND (
	//      $1::text = ''
	//      OR u.email ILIKE '%' || $1 || '%'
	//      OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
	//      OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
	//    )
	//  ORDER BY u.created_at DESC
	//  LIMIT $2 OFFSET $3
	AdminList(ctx context.Context, arg AdminListParams) ([]AdminListRow, error)
	//AdminListCount
	//
	//  SELECT COUNT(*)
	//  FROM users u
	//  LEFT JOIN customer_profiles cp ON cp.user_id = u.id
	//  LEFT JOIN staff_profiles sp ON sp.user_id = u.id
	//  LEFT JOIN admin_profiles ap ON ap.user_id = u.id
	//  WHERE u.deleted_at IS NULL
	//    AND (
	//      $1::text = ''
	//      OR u.email ILIKE '%' || $1 || '%'
	//      OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
	//      OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
	//    )
	AdminListCount(ctx context.Context, dollar_1 string) (int64, error)
	//CatalogGetComboByID
	//
	//  SELECT id, name, slug, price_cents, starts_at, ends_at
	//  FROM combos
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//    AND is_active = true
	//    AND starts_at <= now()
	//    AND ends_at > now()
	CatalogGetComboByID(ctx context.Context, id uuid.UUID) (CatalogGetComboByIDRow, error)
	//CatalogGetCombosByIDs
	//
	//  SELECT c.id, c.name, c.slug, c.price_cents, c.starts_at, c.ends_at
	//  FROM combos c
	//  WHERE c.id = ANY($1::uuid[])
	//    AND c.deleted_at IS NULL
	//    AND c.is_active = true
	//    AND c.starts_at <= now()
	//    AND c.ends_at > now()
	//    AND EXISTS (
	//      SELECT 1
	//      FROM combo_items ci
	//      INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_available = true
	//      INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
	//      WHERE ci.combo_id = c.id
	//    )
	CatalogGetCombosByIDs(ctx context.Context, comboIds []uuid.UUID) ([]CatalogGetCombosByIDsRow, error)
	//CatalogGetProductByID
	//
	//  SELECT
	//      p.id,
	//      p.category_id,
	//      p.name,
	//      p.slug,
	//      p.description,
	//      p.price_cents,
	//      p.image_url,
	//      c.name AS category_name,
	//      c.slug AS category_slug
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
	//  WHERE p.id = $1
	//    AND p.deleted_at IS NULL
	//    AND p.is_available = true
	CatalogGetProductByID(ctx context.Context, id uuid.UUID) (CatalogGetProductByIDRow, error)
	//CatalogGetProductsByIDs
	//
	//  SELECT
	//      p.id,
	//      p.category_id,
	//      p.name,
	//      p.slug,
	//      p.description,
	//      p.price_cents,
	//      p.image_url,
	//      c.name AS category_name,
	//      c.slug AS category_slug
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
	//  WHERE p.id = ANY($1::uuid[])
	//    AND p.deleted_at IS NULL
	//    AND p.is_available = true
	CatalogGetProductsByIDs(ctx context.Context, productIds []uuid.UUID) ([]CatalogGetProductsByIDsRow, error)
	//CatalogListCategories
	//
	//  SELECT id, name, slug, sort_order
	//  FROM categories
	//  WHERE deleted_at IS NULL
	//    AND is_active = true
	//  ORDER BY sort_order ASC, name ASC
	//  LIMIT $1 OFFSET $2
	CatalogListCategories(ctx context.Context, arg CatalogListCategoriesParams) ([]CatalogListCategoriesRow, error)
	//CatalogListCategoriesCount
	//
	//  SELECT count(*)::bigint AS count
	//  FROM categories
	//  WHERE deleted_at IS NULL
	//    AND is_active = true
	CatalogListCategoriesCount(ctx context.Context) (int64, error)
	//CatalogListCombos
	//
	//  SELECT c.id, c.name, c.slug, c.price_cents, c.starts_at, c.ends_at
	//  FROM combos c
	//  WHERE c.deleted_at IS NULL
	//    AND c.is_active = true
	//    AND c.starts_at <= now()
	//    AND c.ends_at > now()
	//    AND EXISTS (
	//      SELECT 1
	//      FROM combo_items ci
	//      INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_available = true
	//      INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
	//      WHERE ci.combo_id = c.id
	//    )
	//  ORDER BY c.starts_at ASC, c.name ASC
	//  LIMIT $1 OFFSET $2
	CatalogListCombos(ctx context.Context, arg CatalogListCombosParams) ([]CatalogListCombosRow, error)
	//CatalogListCombosCount
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM combos c
	//  WHERE c.deleted_at IS NULL
	//    AND c.is_active = true
	//    AND c.starts_at <= now()
	//    AND c.ends_at > now()
	//    AND EXISTS (
	//      SELECT 1
	//      FROM combo_items ci
	//      INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_available = true
	//      INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
	//      WHERE ci.combo_id = c.id
	//    )
	CatalogListCombosCount(ctx context.Context) (int64, error)
	//CatalogListProducts
	//
	//  SELECT
	//      p.id,
	//      p.category_id,
	//      p.name,
	//      p.slug,
	//      p.description,
	//      p.price_cents,
	//      p.image_url,
	//      c.name AS category_name,
	//      c.slug AS category_slug
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
	//  WHERE p.deleted_at IS NULL
	//    AND p.is_available = true
	//    AND (
	//      $3::uuid IS NULL
	//      OR p.category_id = $3::uuid
	//    )
	//    AND (
	//      $4::text IS NULL
	//      OR p.name ILIKE '%' || $4::text || '%'
	//      OR p.slug ILIKE '%' || $4::text || '%'
	//    )
	//  ORDER BY c.sort_order ASC, p.name ASC
	//  LIMIT $1 OFFSET $2
	CatalogListProducts(ctx context.Context, arg CatalogListProductsParams) ([]CatalogListProductsRow, error)
	//CatalogListProductsCount
	//
	//  SELECT count(*)::bigint AS count
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
	//  WHERE p.deleted_at IS NULL
	//    AND p.is_available = true
	//    AND (
	//      $1::uuid IS NULL
	//      OR p.category_id = $1::uuid
	//    )
	//    AND (
	//      $2::text IS NULL
	//      OR p.name ILIKE '%' || $2::text || '%'
	//      OR p.slug ILIKE '%' || $2::text || '%'
	//    )
	CatalogListProductsCount(ctx context.Context, arg CatalogListProductsCountParams) (int64, error)
	//ClearCartDiscountCode
	//
	//  UPDATE carts
	//  SET discount_code_id = NULL, updated_at = now()
	//  WHERE id = $1
	ClearCartDiscountCode(ctx context.Context, id uuid.UUID) error
	//ClearMustChangePassword
	//
	//  UPDATE users
	//  SET must_change_password = false,
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	ClearMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error)
	//CountAvailableProductsForCombo
	//
	//  SELECT COUNT(DISTINCT p.id)::bigint AS count
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
	//  WHERE p.id = ANY($1::uuid[])
	//    AND p.deleted_at IS NULL
	//    AND p.is_available = true
	CountAvailableProductsForCombo(ctx context.Context, productIds []uuid.UUID) (int64, error)
	//CountCartItems
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM cart_items
	//  WHERE cart_id = $1
	CountCartItems(ctx context.Context, cartID uuid.UUID) (int64, error)
	//CreateAdminProfile
	//
	//  INSERT INTO admin_profiles (user_id, full_name, phone)
	//  VALUES ($1, $2, $3)
	//  RETURNING user_id, full_name, phone, created_at, updated_at
	CreateAdminProfile(ctx context.Context, arg CreateAdminProfileParams) (AdminProfile, error)
	//CreateAuditLog
	//
	//  INSERT INTO audit_logs (
	//      actor_id,
	//      actor_role,
	//      action,
	//      target_id,
	//      target_type,
	//      before_jsonb,
	//      after_jsonb,
	//      ip,
	//      user_agent
	//  )
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, NULLIF($8, '')::inet, $9)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	//CreateCart
	//
	//  INSERT INTO carts (user_id)
	//  VALUES ($1)
	//  RETURNING id, user_id, discount_code_id, created_at, updated_at
	CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	//CreateCartItem
	//
	//  INSERT INTO cart_items (cart_id, line_type, product_id, combo_id, quantity)
	//  VALUES ($1, $2, $3, $4, $5)
	//  RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	//CreateCategory
	//
	//  INSERT INTO categories (name, slug, sort_order, is_active)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	//CreateCombo
	//
	//  INSERT INTO combos (name, slug, price_cents, starts_at, ends_at, is_active)
	//  VALUES ($1, $2, $3, $4, $5, $6)
	//  RETURNING id, name, slug, price_cents, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
	CreateCombo(ctx context.Context, arg CreateComboParams) (Combo, error)
	//CreateCustomerProfile
	//
	//  INSERT INTO customer_profiles (user_id, display_name, phone)
	//  VALUES ($1, $2, $3)
	//  RETURNING user_id, display_name, phone, created_at, updated_at
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error)
	//CreateDiscountCode
	//
	//  INSERT INTO discount_codes (
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      starts_at,
	//      ends_at,
	//      is_active
	//  )
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
	//  RETURNING
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) (DiscountCode, error)
	//CreateOrder
	//
	//  INSERT INTO orders (
	//    user_id,
	//    status,
	//    subtotal_cents,
	//    discount_cents,
	//    total_cents,
	//    discount_code_id,
	//    discount_code_snapshot
	//  )
	//  VALUES ($1, $2, $3, $4, $5, $6, $7)
	//  RETURNING
	//    id,
	//    user_id,
	//    status,
	//    subtotal_cents,
	//    discount_cents,
	//    total_cents,
	//    discount_code_id,
	//    discount_code_snapshot,
	//    created_at,
	//    updated_at
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	//CreateOrderItem
	//
	//  INSERT INTO order_items (
	//    order_id,
	//    line_type,
	//    product_id,
	//    combo_id,
	//    name,
	//    slug,
	//    quantity,
	//    unit_price_cents,
	//    line_total_cents
	//  )
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	//  RETURNING
	//    id,
	//    order_id,
	//    line_type,
	//    product_id,
	//    combo_id,
	//    name,
	//    slug,
	//    quantity,
	//    unit_price_cents,
	//    line_total_cents,
	//    created_at
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	//CreateProduct
	//
	//  INSERT INTO products (category_id, name, slug, description, price_cents, is_available, image_url)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7)
	//  RETURNING id, category_id, name, slug, description, price_cents, is_available, image_url, created_at, updated_at, deleted_at
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	//CreateStaffProfile
	//
	//  INSERT INTO staff_profiles (user_id, full_name, phone, employee_code)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
	CreateStaffProfile(ctx context.Context, arg CreateStaffProfileParams) (StaffProfile, error)
	//CreateUser
	//
	//  INSERT INTO users (email, password_hash, role, must_change_password)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//DeleteAdminProfileByUserID
	//
	//  DELETE FROM admin_profiles
	//  WHERE user_id = $1
	DeleteAdminProfileByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	//DeleteAllCartItems
	//
	//  DELETE FROM cart_items
	//  WHERE cart_id = $1
	DeleteAllCartItems(ctx context.Context, cartID uuid.UUID) error
	//DeleteCartItem
	//
	//  DELETE FROM cart_items
	//  WHERE cart_id = $1 AND id = $2
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	//DeleteComboItemsByComboID
	//
	//  DELETE FROM combo_items
	//  WHERE combo_id = $1
	DeleteComboItemsByComboID(ctx context.Context, comboID uuid.UUID) error
	//DeleteCustomerProfileByUserID
	//
	//  DELETE FROM customer_profiles
	//  WHERE user_id = $1
	DeleteCustomerProfileByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	//DeleteStaffProfileByUserID
	//
	//  DELETE FROM staff_profiles
	//  WHERE user_id = $1
	DeleteStaffProfileByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	//GetAdminProfileByUserID
	//
	//  SELECT user_id, full_name, phone, created_at, updated_at
	//  FROM admin_profiles
	//  WHERE user_id = $1
	GetAdminProfileByUserID(ctx context.Context, userID uuid.UUID) (AdminProfile, error)
	//GetCartByUserID
	//
	//  SELECT id, user_id, discount_code_id, created_at, updated_at
	//  FROM carts
	//  WHERE user_id = $1
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	//GetCartItemByCombo
	//
	//  SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	//  FROM cart_items
	//  WHERE cart_id = $1 AND line_type = 'combo' AND combo_id = $2
	GetCartItemByCombo(ctx context.Context, arg GetCartItemByComboParams) (CartItem, error)
	//GetCartItemByID
	//
	//  SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	//  FROM cart_items
	//  WHERE cart_id = $1 AND id = $2
	GetCartItemByID(ctx context.Context, arg GetCartItemByIDParams) (CartItem, error)
	//GetCartItemByProduct
	//
	//  SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	//  FROM cart_items
	//  WHERE cart_id = $1 AND line_type = 'product' AND product_id = $2
	GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error)
	//GetCategoryByID
	//
	//  SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
	//  FROM categories
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	//GetComboByID
	//
	//  SELECT id, name, slug, price_cents, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
	//  FROM combos
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetComboByID(ctx context.Context, id uuid.UUID) (Combo, error)
	//GetCustomerProfileByUserID
	//
	//  SELECT user_id, display_name, phone, created_at, updated_at
	//  FROM customer_profiles
	//  WHERE user_id = $1
	GetCustomerProfileByUserID(ctx context.Context, userID uuid.UUID) (CustomerProfile, error)
	//GetDiscountCodeByCode
	//
	//  SELECT
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	//  FROM discount_codes
	//  WHERE code = $1
	//    AND deleted_at IS NULL
	GetDiscountCodeByCode(ctx context.Context, code string) (DiscountCode, error)
	//GetDiscountCodeByID
	//
	//  SELECT
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	//  FROM discount_codes
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetDiscountCodeByID(ctx context.Context, id uuid.UUID) (DiscountCode, error)
	//GetOrderByIDForUser
	//
	//  SELECT
	//    id,
	//    user_id,
	//    status,
	//    subtotal_cents,
	//    discount_cents,
	//    total_cents,
	//    discount_code_id,
	//    discount_code_snapshot,
	//    created_at,
	//    updated_at
	//  FROM orders
	//  WHERE id = $1 AND user_id = $2
	GetOrderByIDForUser(ctx context.Context, arg GetOrderByIDForUserParams) (Order, error)
	//GetProductByID
	//
	//  SELECT id, category_id, name, slug, description, price_cents, is_available, image_url, created_at, updated_at, deleted_at
	//  FROM products
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	//GetStaffProfileByUserID
	//
	//  SELECT user_id, full_name, phone, employee_code, created_at, updated_at
	//  FROM staff_profiles
	//  WHERE user_id = $1
	GetStaffProfileByUserID(ctx context.Context, userID uuid.UUID) (StaffProfile, error)
	//GetUserByEmail
	//
	//  SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
	//  FROM users
	//  WHERE email = $1
	//    AND deleted_at IS NULL
	GetUserByEmail(ctx context.Context, email string) (User, error)
	//GetUserByID
	//
	//  SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
	//  FROM users
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	//GetUserByIDForUpdate
	//
	//  SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
	//  FROM users
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  FOR UPDATE
	GetUserByIDForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	//IncrementDiscountCodeUsedCount
	//
	//  UPDATE discount_codes
	//  SET used_count = used_count + 1,
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//    AND (max_uses IS NULL OR used_count < max_uses)
	//  RETURNING
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	IncrementDiscountCodeUsedCount(ctx context.Context, id uuid.UUID) (DiscountCode, error)
	//InsertComboItem
	//
	//  INSERT INTO combo_items (combo_id, product_id, quantity)
	//  VALUES ($1, $2, $3)
	InsertComboItem(ctx context.Context, arg InsertComboItemParams) error
	//ListCartItemsByCartID
	//
	//  SELECT id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	//  FROM cart_items
	//  WHERE cart_id = $1
	//  ORDER BY created_at ASC
	ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	//ListCatalogComboItemsByComboIDs
	//
	//  SELECT
	//      ci.id,
	//      ci.combo_id,
	//      ci.product_id,
	//      ci.quantity,
	//      p.name AS product_name,
	//      p.slug AS product_slug,
	//      p.price_cents
	//  FROM combo_items ci
	//  INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL AND p.is_available = true
	//  INNER JOIN categories cat ON cat.id = p.category_id AND cat.deleted_at IS NULL AND cat.is_active = true
	//  WHERE ci.combo_id = ANY($1::uuid[])
	//  ORDER BY ci.combo_id ASC, p.name ASC
	ListCatalogComboItemsByComboIDs(ctx context.Context, comboIds []uuid.UUID) ([]ListCatalogComboItemsByComboIDsRow, error)
	//ListComboItemsByComboID
	//
	//  SELECT
	//      ci.id,
	//      ci.combo_id,
	//      ci.product_id,
	//      ci.quantity,
	//      p.name AS product_name,
	//      p.slug AS product_slug,
	//      p.price_cents
	//  FROM combo_items ci
	//  INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
	//  WHERE ci.combo_id = $1
	//  ORDER BY p.name ASC
	ListComboItemsByComboID(ctx context.Context, comboID uuid.UUID) ([]ListComboItemsByComboIDRow, error)
	//ListComboItemsByComboIDs
	//
	//  SELECT
	//      ci.id,
	//      ci.combo_id,
	//      ci.product_id,
	//      ci.quantity,
	//      p.name AS product_name,
	//      p.slug AS product_slug,
	//      p.price_cents
	//  FROM combo_items ci
	//  INNER JOIN products p ON p.id = ci.product_id AND p.deleted_at IS NULL
	//  WHERE ci.combo_id = ANY($1::uuid[])
	//  ORDER BY ci.combo_id ASC, p.name ASC
	ListComboItemsByComboIDs(ctx context.Context, comboIds []uuid.UUID) ([]ListComboItemsByComboIDsRow, error)
	//ListOrderItemsByOrderID
	//
	//  SELECT
	//    id,
	//    order_id,
	//    line_type,
	//    product_id,
	//    combo_id,
	//    name,
	//    slug,
	//    quantity,
	//    unit_price_cents,
	//    line_total_cents,
	//    created_at
	//  FROM order_items
	//  WHERE order_id = $1
	//  ORDER BY created_at ASC
	ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	//ListOrdersByUser
	//
	//  SELECT
	//    id,
	//    user_id,
	//    status,
	//    subtotal_cents,
	//    discount_cents,
	//    total_cents,
	//    discount_code_id,
	//    discount_code_snapshot,
	//    created_at,
	//    updated_at
	//  FROM orders
	//  WHERE user_id = $1
	//  ORDER BY created_at DESC
	//  LIMIT $2 OFFSET $3
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	//ListOrdersByUserCount
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM orders
	//  WHERE user_id = $1
	ListOrdersByUserCount(ctx context.Context, userID uuid.UUID) (int64, error)
	//ManagerGetProductByID
	//
	//  SELECT
	//      p.id,
	//      p.category_id,
	//      p.name,
	//      p.slug,
	//      p.description,
	//      p.price_cents,
	//      p.is_available,
	//      p.image_url,
	//      p.created_at,
	//      p.updated_at,
	//      p.deleted_at,
	//      c.name AS category_name
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
	//  WHERE p.id = $1
	//    AND p.deleted_at IS NULL
	ManagerGetProductByID(ctx context.Context, id uuid.UUID) (ManagerGetProductByIDRow, error)
	//ManagerListCategories
	//
	//  SELECT id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
	//  FROM categories
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $3::text IS NULL
	//      OR name ILIKE '%' || $3::text || '%'
	//      OR slug ILIKE '%' || $3::text || '%'
	//    )
	//  ORDER BY sort_order ASC, name ASC
	//  LIMIT $1 OFFSET $2
	ManagerListCategories(ctx context.Context, arg ManagerListCategoriesParams) ([]Category, error)
	//ManagerListCategoriesCount
	//
	//  SELECT count(*)::bigint AS count
	//  FROM categories
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $1::text IS NULL
	//      OR name ILIKE '%' || $1::text || '%'
	//      OR slug ILIKE '%' || $1::text || '%'
	//    )
	ManagerListCategoriesCount(ctx context.Context, search sql.NullString) (int64, error)
	//ManagerListCombos
	//
	//  SELECT id, name, slug, price_cents, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
	//  FROM combos
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $3::text IS NULL
	//      OR name ILIKE '%' || $3::text || '%'
	//      OR slug ILIKE '%' || $3::text || '%'
	//    )
	//  ORDER BY starts_at DESC, name ASC
	//  LIMIT $1 OFFSET $2
	ManagerListCombos(ctx context.Context, arg ManagerListCombosParams) ([]Combo, error)
	//ManagerListCombosCount
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM combos
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $1::text IS NULL
	//      OR name ILIKE '%' || $1::text || '%'
	//      OR slug ILIKE '%' || $1::text || '%'
	//    )
	ManagerListCombosCount(ctx context.Context, search sql.NullString) (int64, error)
	//ManagerListDiscountCodes
	//
	//  SELECT
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	//  FROM discount_codes
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $3::text IS NULL
	//      OR code ILIKE '%' || $3::text || '%'
	//    )
	//  ORDER BY created_at DESC
	//  LIMIT $1 OFFSET $2
	ManagerListDiscountCodes(ctx context.Context, arg ManagerListDiscountCodesParams) ([]DiscountCode, error)
	//ManagerListDiscountCodesCount
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM discount_codes
	//  WHERE deleted_at IS NULL
	//    AND (
	//      $1::text IS NULL
	//      OR code ILIKE '%' || $1::text || '%'
	//    )
	ManagerListDiscountCodesCount(ctx context.Context, search sql.NullString) (int64, error)
	//ManagerListProducts
	//
	//  SELECT
	//      p.id,
	//      p.category_id,
	//      p.name,
	//      p.slug,
	//      p.description,
	//      p.price_cents,
	//      p.is_available,
	//      p.image_url,
	//      p.created_at,
	//      p.updated_at,
	//      p.deleted_at,
	//      c.name AS category_name
	//  FROM products p
	//  INNER JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
	//  WHERE p.deleted_at IS NULL
	//    AND (
	//      $3::uuid IS NULL
	//      OR p.category_id = $3::uuid
	//    )
	//    AND (
	//      $4::text IS NULL
	//      OR p.name ILIKE '%' || $4::text || '%'
	//      OR p.slug ILIKE '%' || $4::text || '%'
	//    )
	//  ORDER BY p.name ASC
	//  LIMIT $1 OFFSET $2
	ManagerListProducts(ctx context.Context, arg ManagerListProductsParams) ([]ManagerListProductsRow, error)
	//ManagerListProductsCount
	//
	//  SELECT count(*)::bigint AS count
	//  FROM products p
	//  WHERE p.deleted_at IS NULL
	//    AND (
	//      $1::uuid IS NULL
	//      OR p.category_id = $1::uuid
	//    )
	//    AND (
	//      $2::text IS NULL
	//      OR p.name ILIKE '%' || $2::text || '%'
	//      OR p.slug ILIKE '%' || $2::text || '%'
	//    )
	ManagerListProductsCount(ctx context.Context, arg ManagerListProductsCountParams) (int64, error)
	//SetCartDiscountCodeID
	//
	//  UPDATE carts
	//  SET discount_code_id = $2, updated_at = now()
	//  WHERE id = $1
	SetCartDiscountCodeID(ctx context.Context, arg SetCartDiscountCodeIDParams) error
	//SetMustChangePassword
	//
	//  UPDATE users
	//  SET must_change_password = true,
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	SetMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error)
	//SoftDelete
	//
	//  UPDATE users
	//  SET deleted_at = now(),
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	SoftDelete(ctx context.Context, id uuid.UUID) (int64, error)
	//SoftDeleteCategoryIfNoProducts
	//
	//  UPDATE categories
	//  SET deleted_at = now(),
	//      updated_at = now()
	//  WHERE categories.id = $1
	//    AND categories.deleted_at IS NULL
	//    AND NOT EXISTS (
	//      SELECT 1
	//      FROM products
	//      WHERE products.category_id = categories.id
	//        AND products.deleted_at IS NULL
	//    )
	SoftDeleteCategoryIfNoProducts(ctx context.Context, id uuid.UUID) (int64, error)
	//SoftDeleteCombo
	//
	//  UPDATE combos
	//  SET deleted_at = now(),
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	SoftDeleteCombo(ctx context.Context, id uuid.UUID) (int64, error)
	//SoftDeleteDiscountCode
	//
	//  UPDATE discount_codes
	//  SET deleted_at = now(),
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	SoftDeleteDiscountCode(ctx context.Context, id uuid.UUID) (int64, error)
	//SoftDeleteProduct
	//
	//  UPDATE products
	//  SET deleted_at = now(),
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) (int64, error)
	//StaffGetOrderByID
	//
	//  SELECT
	//    o.id,
	//    o.user_id,
	//    o.status,
	//    o.subtotal_cents,
	//    o.discount_cents,
	//    o.total_cents,
	//    o.discount_code_id,
	//    o.discount_code_snapshot,
	//    o.created_at,
	//    o.updated_at,
	//    u.email AS customer_email,
	//    cp.display_name AS customer_display_name
	//  FROM orders o
	//  INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
	//  LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
	//  WHERE o.id = $1
	StaffGetOrderByID(ctx context.Context, id uuid.UUID) (StaffGetOrderByIDRow, error)
	//StaffListOrders
	//
	//  SELECT
	//    o.id,
	//    o.user_id,
	//    o.status,
	//    o.subtotal_cents,
	//    o.discount_cents,
	//    o.total_cents,
	//    o.discount_code_id,
	//    o.discount_code_snapshot,
	//    o.created_at,
	//    o.updated_at,
	//    u.email AS customer_email,
	//    cp.display_name AS customer_display_name
	//  FROM orders o
	//  INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
	//  LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
	//  WHERE (
	//      $1::order_status IS NULL
	//      OR o.status = $1::order_status
	//  )
	//  ORDER BY o.created_at DESC
	//  LIMIT $3 OFFSET $2
	StaffListOrders(ctx context.Context, arg StaffListOrdersParams) ([]StaffListOrdersRow, error)
	//StaffListOrdersCount
	//
	//  SELECT COUNT(*)::bigint AS count
	//  FROM orders o
	//  INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
	//  WHERE (
	//      $1::order_status IS NULL
	//      OR o.status = $1::order_status
	//  )
	StaffListOrdersCount(ctx context.Context, status NullOrderStatus) (int64, error)
	//SumOrderItemQuantitiesByOrderIDs
	//
	//  SELECT order_id, COALESCE(SUM(quantity), 0)::bigint AS item_count
	//  FROM order_items
	//  WHERE order_id = ANY($1::uuid[])
	//  GROUP BY order_id
	SumOrderItemQuantitiesByOrderIDs(ctx context.Context, orderIds []uuid.UUID) ([]SumOrderItemQuantitiesByOrderIDsRow, error)
	//UpdateAdminProfileByUserID
	//
	//  UPDATE admin_profiles
	//  SET full_name = $2,
	//      phone = $3,
	//      updated_at = now()
	//  WHERE user_id = $1
	//  RETURNING user_id, full_name, phone, created_at, updated_at
	UpdateAdminProfileByUserID(ctx context.Context, arg UpdateAdminProfileByUserIDParams) (AdminProfile, error)
	//UpdateCartItemQuantity
	//
	//  UPDATE cart_items
	//  SET quantity = $3, updated_at = now()
	//  WHERE cart_id = $1 AND id = $2
	//  RETURNING id, cart_id, line_type, product_id, combo_id, quantity, created_at, updated_at
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	//UpdateCategory
	//
	//  UPDATE categories
	//  SET name       = $2,
	//      slug       = $3,
	//      sort_order = $4,
	//      is_active  = $5,
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  RETURNING id, name, slug, sort_order, is_active, created_at, updated_at, deleted_at
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	//UpdateCombo
	//
	//  UPDATE combos
	//  SET name        = $2,
	//      slug        = $3,
	//      price_cents = $4,
	//      starts_at   = $5,
	//      ends_at     = $6,
	//      is_active   = $7,
	//      updated_at  = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  RETURNING id, name, slug, price_cents, starts_at, ends_at, is_active, created_at, updated_at, deleted_at
	UpdateCombo(ctx context.Context, arg UpdateComboParams) (Combo, error)
	//UpdateCustomerProfileByUserID
	//
	//  UPDATE customer_profiles
	//  SET display_name = $2,
	//      phone = $3,
	//      updated_at = now()
	//  WHERE user_id = $1
	//  RETURNING user_id, display_name, phone, created_at, updated_at
	UpdateCustomerProfileByUserID(ctx context.Context, arg UpdateCustomerProfileByUserIDParams) (CustomerProfile, error)
	//UpdateDiscountCode
	//
	//  UPDATE discount_codes
	//  SET code            = $2,
	//      discount_type   = $3,
	//      value           = $4,
	//      min_order_cents = $5,
	//      max_uses        = $6,
	//      starts_at       = $7,
	//      ends_at         = $8,
	//      is_active       = $9,
	//      updated_at      = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  RETURNING
	//      id,
	//      code,
	//      discount_type,
	//      value,
	//      min_order_cents,
	//      max_uses,
	//      used_count,
	//      starts_at,
	//      ends_at,
	//      is_active,
	//      created_at,
	//      updated_at,
	//      deleted_at
	UpdateDiscountCode(ctx context.Context, arg UpdateDiscountCodeParams) (DiscountCode, error)
	//UpdateOrderStatus
	//
	//  UPDATE orders
	//  SET status = $1::order_status,
	//      updated_at = now()
	//  WHERE id = $2
	//    AND status = $3::order_status
	//  RETURNING
	//    id,
	//    user_id,
	//    status,
	//    subtotal_cents,
	//    discount_cents,
	//    total_cents,
	//    discount_code_id,
	//    discount_code_snapshot,
	//    created_at,
	//    updated_at
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	//UpdateProduct
	//
	//  UPDATE products
	//  SET category_id  = $2,
	//      name         = $3,
	//      slug         = $4,
	//      description  = $5,
	//      price_cents  = $6,
	//      is_available = $7,
	//      image_url    = $8,
	//      updated_at   = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	//  RETURNING id, category_id, name, slug, description, price_cents, is_available, image_url, created_at, updated_at, deleted_at
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	//UpdateRole
	//
	//  UPDATE users
	//  SET role = $2,
	//      updated_at = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error)
	//UpdateStaffProfileByUserID
	//
	//  UPDATE staff_profiles
	//  SET full_name = $2,
	//      phone = $3,
	//      employee_code = $4,
	//      updated_at = now()
	//  WHERE user_id = $1
	//  RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
	UpdateStaffProfileByUserID(ctx context.Context, arg UpdateStaffProfileByUserIDParams) (StaffProfile, error)
	//UpdateUserPassword
	//
	//  UPDATE users
	//  SET password_hash = $2,
	//      updated_at    = now()
	//  WHERE id = $1
	//    AND deleted_at IS NULL
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
