// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPublishedReviews = `-- name: CountPublishedReviews :one
SELECT
  count(*)::bigint AS review_count,
  COALESCE(sum(rating), 0)::bigint AS rating_total
FROM reviews
WHERE product_id = $1
  AND status = 'published'::review_status
  AND deleted_at IS NULL
`

type CountPublishedReviewsRow struct {
	ReviewCount int64 `json:"reviewCount"`
	RatingTotal int64 `json:"ratingTotal"`
}

// How many published reviews a product has, and their ratings added up.
//
//	SELECT
//	  count(*)::bigint AS review_count,
//	  COALESCE(sum(rating), 0)::bigint AS rating_total
//	FROM reviews
//	WHERE product_id = $1
//	  AND status = 'published'::review_status
//	  AND deleted_at IS NULL
func (q *Queries) CountPublishedReviews(ctx context.Context, productID uuid.UUID) (CountPublishedReviewsRow, error) {
	row := q.db.QueryRow(ctx, countPublishedReviews, productID)
	var i CountPublishedReviewsRow
	err := row.Scan(&i.ReviewCount, &i.RatingTotal)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (order_id, product_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, rating, comment, status, created_at
`

type CreateReviewParams struct {
	OrderID   uuid.UUID `json:"orderId"`
	ProductID uuid.UUID `json:"productId"`
	UserID    uuid.UUID `json:"userId"`
	Rating    int16     `json:"rating"`
	Comment   *string   `json:"comment"`
}

type CreateReviewRow struct {
	ID        uuid.UUID    `json:"id"`
	ProductID uuid.UUID    `json:"productId"`
	Rating    int16        `json:"rating"`
	Comment   *string      `json:"comment"`
	Status    ReviewStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
}

// CreateReview
//
//	INSERT INTO reviews (order_id, product_id, user_id, rating, comment)
//	VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, product_id, rating, comment, status, created_at
func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (CreateReviewRow, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.OrderID,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i CreateReviewRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const eraseUserReviews = `-- name: EraseUserReviews :exec
UPDATE reviews
SET comment = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND deleted_at IS NULL
`

// Erases what the customer wrote as their account is erased; their reviews
// no longer count.
//
//	UPDATE reviews
//	SET comment = NULL,
//	    deleted_at = now(),
//	    updated_at = now()
//	WHERE user_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) EraseUserReviews(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, eraseUserReviews, userID)
	return err
}

const getReviewForUpdate = `-- name: GetReviewForUpdate :one
SELECT status, user_id
FROM reviews
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

type GetReviewForUpdateRow struct {
	Status ReviewStatus `json:"status"`
	UserID uuid.UUID    `json:"userId"`
}

// Where a review stands and who wrote it, held until the transaction ends.
//
//	SELECT status, user_id
//	FROM reviews
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	FOR UPDATE
func (q *Queries) GetReviewForUpdate(ctx context.Context, id uuid.UUID) (GetReviewForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getReviewForUpdate, id)
	var i GetReviewForUpdateRow
	err := row.Scan(&i.Status, &i.UserID)
	return i, err
}

const listPublishedReviews = `-- name: ListPublishedReviews :many
SELECT r.id, r.rating, r.comment, r.created_at
FROM reviews r
WHERE r.product_id = $1
  AND r.status = 'published'::review_status
  AND r.deleted_at IS NULL
  AND (
    $2::uuid IS NULL
    OR (r.created_at, r.id) < (
      SELECT b.created_at, b.id FROM reviews b
      WHERE b.id = $2::uuid AND b.product_id = r.product_id
    )
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3
`

type ListPublishedReviewsParams struct {
	ProductID uuid.UUID  `json:"productId"`
	BeforeID  *uuid.UUID `json:"beforeId"`
	Limit     int32      `json:"limit"`
}

type ListPublishedReviewsRow struct {
	ID        uuid.UUID `json:"id"`
	Rating    int16     `json:"rating"`
	Comment   *string   `json:"comment"`
	CreatedAt time.Time `json:"createdAt"`
}

// A page of a product's published reviews, latest first: the latest, or those
// written before the review before_id names.
//
//	SELECT r.id, r.rating, r.comment, r.created_at
//	FROM reviews r
//	WHERE r.product_id = $1
//	  AND r.status = 'published'::review_status
//	  AND r.deleted_at IS NULL
//	  AND (
//	    $2::uuid IS NULL
//	    OR (r.created_at, r.id) < (
//	      SELECT b.created_at, b.id FROM reviews b
//	      WHERE b.id = $2::uuid AND b.product_id = r.product_id
//	    )
//	  )
//	ORDER BY r.created_at DESC, r.id DESC
//	LIMIT $3
func (q *Queries) ListPublishedReviews(ctx context.Context, arg ListPublishedReviewsParams) ([]ListPublishedReviewsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedReviews, arg.ProductID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedReviewsRow{}
	for rows.Next() {
		var i ListPublishedReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByOrder = `-- name: ListReviewsByOrder :many
SELECT id, product_id, rating, comment, status, created_at
FROM reviews
WHERE order_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
ORDER BY created_at, id
`

type ListReviewsByOrderParams struct {
	OrderID uuid.UUID `json:"orderId"`
	UserID  uuid.UUID `json:"userId"`
}

type ListReviewsByOrderRow struct {
	ID        uuid.UUID    `json:"id"`
	ProductID uuid.UUID    `json:"productId"`
	Rating    int16        `json:"rating"`
	Comment   *string      `json:"comment"`
	Status    ReviewStatus `json:"status"`
	CreatedAt time.Time    `json:"createdAt"`
}

// The customer's reviews of the products on one of their orders.
//
//	SELECT id, product_id, rating, comment, status, created_at
//	FROM reviews
//	WHERE order_id = $1
//	  AND user_id = $2
//	  AND deleted_at IS NULL
//	ORDER BY created_at, id
func (q *Queries) ListReviewsByOrder(ctx context.Context, arg ListReviewsByOrderParams) ([]ListReviewsByOrderRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByOrder, arg.OrderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByOrderRow{}
	for rows.Next() {
		var i ListReviewsByOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT
  r.order_id,
  o.code AS order_code,
  r.product_id,
  p.name AS product_name,
  r.rating,
  r.comment,
  r.status,
  r.created_at
FROM reviews r
JOIN orders o ON o.id = r.order_id
JOIN products p ON p.id = r.product_id
WHERE r.user_id = $1
  AND r.deleted_at IS NULL
ORDER BY r.created_at, r.id
`

type ListReviewsByUserRow struct {
	OrderID     uuid.UUID    `json:"orderId"`
	OrderCode   string       `json:"orderCode"`
	ProductID   uuid.UUID    `json:"productId"`
	ProductName string       `json:"productName"`
	Rating      int16        `json:"rating"`
	Comment     *string      `json:"comment"`
	Status      ReviewStatus `json:"status"`
	CreatedAt   time.Time    `json:"createdAt"`
}

// Every review the customer wrote, for a personal data export.
//
//	SELECT
//	  r.order_id,
//	  o.code AS order_code,
//	  r.product_id,
//	  p.name AS product_name,
//	  r.rating,
//	  r.comment,
//	  r.status,
//	  r.created_at
//	FROM reviews r
//	JOIN orders o ON o.id = r.order_id
//	JOIN products p ON p.id = r.product_id
//	WHERE r.user_id = $1
//	  AND r.deleted_at IS NULL
//	ORDER BY r.created_at, r.id
func (q *Queries) ListReviewsByUser(ctx context.Context, userID uuid.UUID) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByUserRow{}
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.OrderID,
			&i.OrderCode,
			&i.ProductID,
			&i.ProductName,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListReviews = `-- name: ManagerListReviews :many
SELECT
  r.id,
  o.code AS order_code,
  r.product_id,
  p.name AS product_name,
  r.rating,
  r.comment,
  r.status,
  r.created_at,
  cp.display_name AS customer_name,
  sp.full_name AS moderator_name
FROM reviews r
JOIN orders o ON o.id = r.order_id
JOIN products p ON p.id = r.product_id
LEFT JOIN customer_profiles cp ON cp.user_id = r.user_id
LEFT JOIN staff_profiles sp ON sp.user_id = r.moderated_by
WHERE r.deleted_at IS NULL
  AND (
    $1::review_status IS NULL
    OR r.status = $1::review_status
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $3 OFFSET $2
`

type ManagerListReviewsParams struct {
	Status *ReviewStatus `json:"status"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

type ManagerListReviewsRow struct {
	ID            uuid.UUID    `json:"id"`
	OrderCode     string       `json:"orderCode"`
	ProductID     uuid.UUID    `json:"productId"`
	ProductName   string       `json:"productName"`
	Rating        int16        `json:"rating"`
	Comment       *string      `json:"comment"`
	Status        ReviewStatus `json:"status"`
	CreatedAt     time.Time    `json:"createdAt"`
	CustomerName  *string      `json:"customerName"`
	ModeratorName *string      `json:"moderatorName"`
}

// A page of reviews to moderate, latest first, with the product, the order
// and the name the customer gave.
//
//	SELECT
//	  r.id,
//	  o.code AS order_code,
//	  r.product_id,
//	  p.name AS product_name,
//	  r.rating,
//	  r.comment,
//	  r.status,
//	  r.created_at,
//	  cp.display_name AS customer_name,
//	  sp.full_name AS moderator_name
//	FROM reviews r
//	JOIN orders o ON o.id = r.order_id
//	JOIN products p ON p.id = r.product_id
//	LEFT JOIN customer_profiles cp ON cp.user_id = r.user_id
//	LEFT JOIN staff_profiles sp ON sp.user_id = r.moderated_by
//	WHERE r.deleted_at IS NULL
//	  AND (
//	    $1::review_status IS NULL
//	    OR r.status = $1::review_status
//	  )
//	ORDER BY r.created_at DESC, r.id DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) ManagerListReviews(ctx context.Context, arg ManagerListReviewsParams) ([]ManagerListReviewsRow, error) {
	rows, err := q.db.Query(ctx, managerListReviews, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ManagerListReviewsRow{}
	for rows.Next() {
		var i ManagerListReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderCode,
			&i.ProductID,
			&i.ProductName,
			&i.Rating,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
			&i.CustomerName,
			&i.ModeratorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const managerListReviewsCount = `-- name: ManagerListReviewsCount :one
SELECT count(*)::bigint
FROM reviews r
WHERE r.deleted_at IS NULL
  AND (
    $1::review_status IS NULL
    OR r.status = $1::review_status
  )
`

// ManagerListReviewsCount
//
//	SELECT count(*)::bigint
//	FROM reviews r
//	WHERE r.deleted_at IS NULL
//	  AND (
//	    $1::review_status IS NULL
//	    OR r.status = $1::review_status
//	  )
func (q *Queries) ManagerListReviewsCount(ctx context.Context, status *ReviewStatus) (int64, error) {
	row := q.db.QueryRow(ctx, managerListReviewsCount, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const moderateReview = `-- name: ModerateReview :one
WITH moderated AS (
  UPDATE reviews
  SET status = $1,
      moderated_by = $2,
      moderated_at = now(),
      updated_at = now()
  WHERE reviews.id = $3
    AND reviews.deleted_at IS NULL
  RETURNING id, order_id, product_id, user_id, rating, comment, status, created_at, moderated_by
)
SELECT
  m.id,
  o.code AS order_code,
  m.product_id,
  p.name AS product_name,
  m.rating,
  m.comment,
  m.status,
  m.created_at,
  cp.display_name AS customer_name,
  sp.full_name AS moderator_name
FROM moderated m
JOIN orders o ON o.id = m.order_id
JOIN products p ON p.id = m.product_id
LEFT JOIN customer_profiles cp ON cp.user_id = m.user_id
LEFT JOIN staff_profiles sp ON sp.user_id = m.moderated_by
`

type ModerateReviewParams struct {
	Status      ReviewStatus `json:"status"`
	ModeratedBy *uuid.UUID   `json:"moderatedBy"`
	ID          uuid.UUID    `json:"id"`
}

type ModerateReviewRow struct {
	ID            uuid.UUID    `json:"id"`
	OrderCode     string       `json:"orderCode"`
	ProductID     uuid.UUID    `json:"productId"`
	ProductName   string       `json:"productName"`
	Rating        int16        `json:"rating"`
	Comment       *string      `json:"comment"`
	Status        ReviewStatus `json:"status"`
	CreatedAt     time.Time    `json:"createdAt"`
	CustomerName  *string      `json:"customerName"`
	ModeratorName *string      `json:"moderatorName"`
}

// Publishes or hides a review, and returns it as the moderation list shows it.
//
//	WITH moderated AS (
//	  UPDATE reviews
//	  SET status = $1,
//	      moderated_by = $2,
//	      moderated_at = now(),
//	      updated_at = now()
//	  WHERE reviews.id = $3
//	    AND reviews.deleted_at IS NULL
//	  RETURNING id, order_id, product_id, user_id, rating, comment, status, created_at, moderated_by
//	)
//	SELECT
//	  m.id,
//	  o.code AS order_code,
//	  m.product_id,
//	  p.name AS product_name,
//	  m.rating,
//	  m.comment,
//	  m.status,
//	  m.created_at,
//	  cp.display_name AS customer_name,
//	  sp.full_name AS moderator_name
//	FROM moderated m
//	JOIN orders o ON o.id = m.order_id
//	JOIN products p ON p.id = m.product_id
//	LEFT JOIN customer_profiles cp ON cp.user_id = m.user_id
//	LEFT JOIN staff_profiles sp ON sp.user_id = m.moderated_by
func (q *Queries) ModerateReview(ctx context.Context, arg ModerateReviewParams) (ModerateReviewRow, error) {
	row := q.db.QueryRow(ctx, moderateReview, arg.Status, arg.ModeratedBy, arg.ID)
	var i ModerateReviewRow
	err := row.Scan(
		&i.ID,
		&i.OrderCode,
		&i.ProductID,
		&i.ProductName,
		&i.Rating,
		&i.Comment,
		&i.Status,
		&i.CreatedAt,
		&i.CustomerName,
		&i.ModeratorName,
	)
	return i, err
}

const reviewRatingCounts = `-- name: ReviewRatingCounts :one
SELECT
  count(*)::bigint AS review_count,
  count(*) FILTER (WHERE r.status = 'pending'::review_status)::bigint AS pending_count,
  COALESCE(sum(r.rating), 0)::bigint AS rating_total,
  count(*) FILTER (WHERE r.rating = 1)::bigint AS one_star,
  count(*) FILTER (WHERE r.rating = 2)::bigint AS two_stars,
  count(*) FILTER (WHERE r.rating = 3)::bigint AS three_stars,
  count(*) FILTER (WHERE r.rating = 4)::bigint AS four_stars,
  count(*) FILTER (WHERE r.rating = 5)::bigint AS five_stars
FROM reviews r
JOIN products p ON p.id = r.product_id AND p.deleted_at IS NULL
WHERE r.deleted_at IS NULL
  AND r.status <> 'hidden'::review_status
`

type ReviewRatingCountsRow struct {
	ReviewCount  int64 `json:"reviewCount"`
	PendingCount int64 `json:"pendingCount"`
	RatingTotal  int64 `json:"ratingTotal"`
	OneStar      int64 `json:"oneStar"`
	TwoStars     int64 `json:"twoStars"`
	ThreeStars   int64 `json:"threeStars"`
	FourStars    int64 `json:"fourStars"`
	FiveStars    int64 `json:"fiveStars"`
}

// Every review not hidden of a product the bakery keeps: how many, how many
// wait for a manager, their ratings added up, and how many of each rating.
//
//	SELECT
//	  count(*)::bigint AS review_count,
//	  count(*) FILTER (WHERE r.status = 'pending'::review_status)::bigint AS pending_count,
//	  COALESCE(sum(r.rating), 0)::bigint AS rating_total,
//	  count(*) FILTER (WHERE r.rating = 1)::bigint AS one_star,
//	  count(*) FILTER (WHERE r.rating = 2)::bigint AS two_stars,
//	  count(*) FILTER (WHERE r.rating = 3)::bigint AS three_stars,
//	  count(*) FILTER (WHERE r.rating = 4)::bigint AS four_stars,
//	  count(*) FILTER (WHERE r.rating = 5)::bigint AS five_stars
//	FROM reviews r
//	JOIN products p ON p.id = r.product_id AND p.deleted_at IS NULL
//	WHERE r.deleted_at IS NULL
//	  AND r.status <> 'hidden'::review_status
func (q *Queries) ReviewRatingCounts(ctx context.Context) (ReviewRatingCountsRow, error) {
	row := q.db.QueryRow(ctx, reviewRatingCounts)
	var i ReviewRatingCountsRow
	err := row.Scan(
		&i.ReviewCount,
		&i.PendingCount,
		&i.RatingTotal,
		&i.OneStar,
		&i.TwoStars,
		&i.ThreeStars,
		&i.FourStars,
		&i.FiveStars,
	)
	return i, err
}

const reviewRatingsByProduct = `-- name: ReviewRatingsByProduct :many
SELECT
  p.id,
  p.name,
  count(*)::bigint AS review_count,
  sum(r.rating)::bigint AS rating_total
FROM reviews r
JOIN products p ON p.id = r.product_id AND p.deleted_at IS NULL
WHERE r.deleted_at IS NULL
  AND r.status <> 'hidden'::review_status
GROUP BY p.id, p.name
ORDER BY sum(r.rating)::numeric / count(*), count(*) DESC, p.name
LIMIT $1
`

type ReviewRatingsByProductRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	ReviewCount int64     `json:"reviewCount"`
	RatingTotal int64     `json:"ratingTotal"`
}

// Each reviewed product the bakery keeps, its reviews not hidden added up, the
// lowest average first: what needs a manager's attention leads.
//
//	SELECT
//	  p.id,
//	  p.name,
//	  count(*)::bigint AS review_count,
//	  sum(r.rating)::bigint AS rating_total
//	FROM reviews r
//	JOIN products p ON p.id = r.product_id AND p.deleted_at IS NULL
//	WHERE r.deleted_at IS NULL
//	  AND r.status <> 'hidden'::review_status
//	GROUP BY p.id, p.name
//	ORDER BY sum(r.rating)::numeric / count(*), count(*) DESC, p.name
//	LIMIT $1
func (q *Queries) ReviewRatingsByProduct(ctx context.Context, limit int32) ([]ReviewRatingsByProductRow, error) {
	rows, err := q.db.Query(ctx, reviewRatingsByProduct, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRatingsByProductRow{}
	for rows.Next() {
		var i ReviewRatingsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ReviewCount,
			&i.RatingTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
