// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_report.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const productionTime = `-- name: ProductionTime :one
SELECT
  count(*)::bigint AS orders,
  COALESCE(round(avg(extract(epoch FROM r.created_at - s.created_at)) / 60), 0)::int AS average_minutes
FROM order_status_events r
JOIN order_status_events s ON s.order_id = r.order_id AND s.to_status = 'in_production'::order_status
WHERE r.to_status = 'ready'::order_status
  AND r.created_at >= $1::timestamptz
  AND r.created_at < $2::timestamptz
`

type ProductionTimeParams struct {
	FromAt time.Time `json:"fromAt"`
	ToAt   time.Time `json:"toAt"`
}

type ProductionTimeRow struct {
	Orders         int64 `json:"orders"`
	AverageMinutes int32 `json:"averageMinutes"`
}

// The orders that became ready in [from_at, to_at), and on average how many
// whole minutes they took from the first ticket started (in production) to
// ready; 0 when none did.
//
//	SELECT
//	  count(*)::bigint AS orders,
//	  COALESCE(round(avg(extract(epoch FROM r.created_at - s.created_at)) / 60), 0)::int AS average_minutes
//	FROM order_status_events r
//	JOIN order_status_events s ON s.order_id = r.order_id AND s.to_status = 'in_production'::order_status
//	WHERE r.to_status = 'ready'::order_status
//	  AND r.created_at >= $1::timestamptz
//	  AND r.created_at < $2::timestamptz
func (q *Queries) ProductionTime(ctx context.Context, arg ProductionTimeParams) (ProductionTimeRow, error) {
	row := q.db.QueryRow(ctx, productionTime, arg.FromAt, arg.ToAt)
	var i ProductionTimeRow
	err := row.Scan(&i.Orders, &i.AverageMinutes)
	return i, err
}

const salesByCategory = `-- name: SalesByCategory :many
SELECT
  cat.id AS category_id,
  cat.name AS category_name,
  sum(i.quantity)::bigint AS quantity,
  sum(i.line_total_cents)::bigint AS sales_cents
FROM order_items i
JOIN orders o ON o.id = i.order_id
JOIN payments pay ON pay.order_id = o.id
LEFT JOIN products p ON p.id = i.product_id
LEFT JOIN categories cat ON cat.id = p.category_id
WHERE pay.captured_at >= $1::timestamptz
  AND pay.captured_at < $2::timestamptz
  AND o.status <> 'cancelled'::order_status
GROUP BY cat.id, cat.name
ORDER BY sales_cents DESC, category_name
`

type SalesByCategoryParams struct {
	FromAt time.Time `json:"fromAt"`
	ToAt   time.Time `json:"toAt"`
}

type SalesByCategoryRow struct {
	CategoryID   *uuid.UUID `json:"categoryId"`
	CategoryName *string    `json:"categoryName"`
	Quantity     int64      `json:"quantity"`
	SalesCents   int64      `json:"salesCents"`
}

// What the orders paid in [from_at, to_at) and not cancelled sold in each
// product's category now, before any order discount; combos, which have no
// category, come as one row without one.
//
//	SELECT
//	  cat.id AS category_id,
//	  cat.name AS category_name,
//	  sum(i.quantity)::bigint AS quantity,
//	  sum(i.line_total_cents)::bigint AS sales_cents
//	FROM order_items i
//	JOIN orders o ON o.id = i.order_id
//	JOIN payments pay ON pay.order_id = o.id
//	LEFT JOIN products p ON p.id = i.product_id
//	LEFT JOIN categories cat ON cat.id = p.category_id
//	WHERE pay.captured_at >= $1::timestamptz
//	  AND pay.captured_at < $2::timestamptz
//	  AND o.status <> 'cancelled'::order_status
//	GROUP BY cat.id, cat.name
//	ORDER BY sales_cents DESC, category_name
func (q *Queries) SalesByCategory(ctx context.Context, arg SalesByCategoryParams) ([]SalesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, salesByCategory, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByCategoryRow{}
	for rows.Next() {
		var i SalesByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Quantity,
			&i.SalesCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByPeriod = `-- name: SalesByPeriod :many
WITH periods AS (
  SELECT generate_series(
    date_trunc($2::text, $1::date::timestamp),
    $3::date::timestamp,
    ('1 ' || $2::text)::interval
  )::date AS start
),
taken AS (
  SELECT
    date_trunc($2::text, pay.captured_at AT TIME ZONE $4::text)::date AS start,
    count(*) AS orders,
    sum(pay.amount_cents) AS gross_cents
  FROM payments pay
  WHERE pay.captured_at >= $5::timestamptz
    AND pay.captured_at < $6::timestamptz
  GROUP BY 1
),
refunded AS (
  SELECT
    date_trunc($2::text, pay.refunded_at AT TIME ZONE $4::text)::date AS start,
    sum(pay.amount_cents) AS refunds_cents
  FROM payments pay
  WHERE pay.refunded_at >= $5::timestamptz
    AND pay.refunded_at < $6::timestamptz
  GROUP BY 1
)
SELECT
  GREATEST(p.start, $1::date)::date AS start,
  COALESCE(t.orders, 0)::bigint AS orders,
  COALESCE(t.gross_cents, 0)::bigint AS gross_cents,
  COALESCE(r.refunds_cents, 0)::bigint AS refunds_cents
FROM periods p
LEFT JOIN taken t ON t.start = p.start
LEFT JOIN refunded r ON r.start = p.start
ORDER BY p.start
`

type SalesByPeriodParams struct {
	FromDay  time.Time `json:"fromDay"`
	Grouping string    `json:"grouping"`
	ToDay    time.Time `json:"toDay"`
	Zone     string    `json:"zone"`
	FromAt   time.Time `json:"fromAt"`
	ToAt     time.Time `json:"toAt"`
}

type SalesByPeriodRow struct {
	Start        time.Time `json:"start"`
	Orders       int64     `json:"orders"`
	GrossCents   int64     `json:"grossCents"`
	RefundsCents int64     `json:"refundsCents"`
}

// The payments taken and the refunds made in [from_at, to_at), by bakery day,
// week (from Monday) or month, every period of [from_day, to_day] listed even
// when nothing happened; the first period starts no earlier than from_day.
//
//	WITH periods AS (
//	  SELECT generate_series(
//	    date_trunc($2::text, $1::date::timestamp),
//	    $3::date::timestamp,
//	    ('1 ' || $2::text)::interval
//	  )::date AS start
//	),
//	taken AS (
//	  SELECT
//	    date_trunc($2::text, pay.captured_at AT TIME ZONE $4::text)::date AS start,
//	    count(*) AS orders,
//	    sum(pay.amount_cents) AS gross_cents
//	  FROM payments pay
//	  WHERE pay.captured_at >= $5::timestamptz
//	    AND pay.captured_at < $6::timestamptz
//	  GROUP BY 1
//	),
//	refunded AS (
//	  SELECT
//	    date_trunc($2::text, pay.refunded_at AT TIME ZONE $4::text)::date AS start,
//	    sum(pay.amount_cents) AS refunds_cents
//	  FROM payments pay
//	  WHERE pay.refunded_at >= $5::timestamptz
//	    AND pay.refunded_at < $6::timestamptz
//	  GROUP BY 1
//	)
//	SELECT
//	  GREATEST(p.start, $1::date)::date AS start,
//	  COALESCE(t.orders, 0)::bigint AS orders,
//	  COALESCE(t.gross_cents, 0)::bigint AS gross_cents,
//	  COALESCE(r.refunds_cents, 0)::bigint AS refunds_cents
//	FROM periods p
//	LEFT JOIN taken t ON t.start = p.start
//	LEFT JOIN refunded r ON r.start = p.start
//	ORDER BY p.start
func (q *Queries) SalesByPeriod(ctx context.Context, arg SalesByPeriodParams) ([]SalesByPeriodRow, error) {
	rows, err := q.db.Query(ctx, salesByPeriod,
		arg.FromDay,
		arg.Grouping,
		arg.ToDay,
		arg.Zone,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByPeriodRow{}
	for rows.Next() {
		var i SalesByPeriodRow
		if err := rows.Scan(
			&i.Start,
			&i.Orders,
			&i.GrossCents,
			&i.RefundsCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesDiscountCodes = `-- name: SalesDiscountCodes :many
SELECT
  o.discount_code_snapshot::text AS code,
  count(*)::bigint AS orders,
  sum(o.discount_cents)::bigint AS discount_cents
FROM orders o
JOIN payments pay ON pay.order_id = o.id
WHERE pay.captured_at >= $1::timestamptz
  AND pay.captured_at < $2::timestamptz
  AND o.status <> 'cancelled'::order_status
  AND o.discount_code_snapshot IS NOT NULL
GROUP BY o.discount_code_snapshot
ORDER BY discount_cents DESC, code
LIMIT $3::int
`

type SalesDiscountCodesParams struct {
	FromAt  time.Time `json:"fromAt"`
	ToAt    time.Time `json:"toAt"`
	MaxRows int32     `json:"maxRows"`
}

type SalesDiscountCodesRow struct {
	Code          string `json:"code"`
	Orders        int64  `json:"orders"`
	DiscountCents int64  `json:"discountCents"`
}

// The discount codes those orders used: how many orders each, and how much it
// took off, the most first, up to max_rows.
//
//	SELECT
//	  o.discount_code_snapshot::text AS code,
//	  count(*)::bigint AS orders,
//	  sum(o.discount_cents)::bigint AS discount_cents
//	FROM orders o
//	JOIN payments pay ON pay.order_id = o.id
//	WHERE pay.captured_at >= $1::timestamptz
//	  AND pay.captured_at < $2::timestamptz
//	  AND o.status <> 'cancelled'::order_status
//	  AND o.discount_code_snapshot IS NOT NULL
//	GROUP BY o.discount_code_snapshot
//	ORDER BY discount_cents DESC, code
//	LIMIT $3::int
func (q *Queries) SalesDiscountCodes(ctx context.Context, arg SalesDiscountCodesParams) ([]SalesDiscountCodesRow, error) {
	rows, err := q.db.Query(ctx, salesDiscountCodes, arg.FromAt, arg.ToAt, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesDiscountCodesRow{}
	for rows.Next() {
		var i SalesDiscountCodesRow
		if err := rows.Scan(&i.Code, &i.Orders, &i.DiscountCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesDiscounts = `-- name: SalesDiscounts :one
SELECT
  count(*)::bigint AS orders,
  count(*) FILTER (WHERE o.discount_code_snapshot IS NOT NULL)::bigint AS discounted_orders,
  COALESCE(sum(o.discount_cents), 0)::bigint AS discount_cents
FROM orders o
JOIN payments pay ON pay.order_id = o.id
WHERE pay.captured_at >= $1::timestamptz
  AND pay.captured_at < $2::timestamptz
  AND o.status <> 'cancelled'::order_status
`

type SalesDiscountsParams struct {
	FromAt time.Time `json:"fromAt"`
	ToAt   time.Time `json:"toAt"`
}

type SalesDiscountsRow struct {
	Orders           int64 `json:"orders"`
	DiscountedOrders int64 `json:"discountedOrders"`
	DiscountCents    int64 `json:"discountCents"`
}

// The orders paid in [from_at, to_at) and not cancelled, how many of them
// used a discount code, and how much the codes took off.
//
//	SELECT
//	  count(*)::bigint AS orders,
//	  count(*) FILTER (WHERE o.discount_code_snapshot IS NOT NULL)::bigint AS discounted_orders,
//	  COALESCE(sum(o.discount_cents), 0)::bigint AS discount_cents
//	FROM orders o
//	JOIN payments pay ON pay.order_id = o.id
//	WHERE pay.captured_at >= $1::timestamptz
//	  AND pay.captured_at < $2::timestamptz
//	  AND o.status <> 'cancelled'::order_status
func (q *Queries) SalesDiscounts(ctx context.Context, arg SalesDiscountsParams) (SalesDiscountsRow, error) {
	row := q.db.QueryRow(ctx, salesDiscounts, arg.FromAt, arg.ToAt)
	var i SalesDiscountsRow
	err := row.Scan(&i.Orders, &i.DiscountedOrders, &i.DiscountCents)
	return i, err
}

const topSoldItems = `-- name: TopSoldItems :many
SELECT
  i.line_type,
  COALESCE(i.product_id, i.combo_id)::uuid AS item_id,
  COALESCE(p.name, c.name)::text AS name,
  sum(i.quantity)::bigint AS quantity,
  sum(i.line_total_cents)::bigint AS sales_cents
FROM order_items i
JOIN orders o ON o.id = i.order_id
JOIN payments pay ON pay.order_id = o.id
LEFT JOIN products p ON p.id = i.product_id
LEFT JOIN combos c ON c.id = i.combo_id
WHERE pay.captured_at >= $1::timestamptz
  AND pay.captured_at < $2::timestamptz
  AND o.status <> 'cancelled'::order_status
GROUP BY i.line_type, COALESCE(i.product_id, i.combo_id), COALESCE(p.name, c.name)
ORDER BY sales_cents DESC, quantity DESC, COALESCE(p.name, c.name)
LIMIT $3::int
`

type TopSoldItemsParams struct {
	FromAt  time.Time `json:"fromAt"`
	ToAt    time.Time `json:"toAt"`
	MaxRows int32     `json:"maxRows"`
}

type TopSoldItemsRow struct {
	LineType   LineType  `json:"lineType"`
	ItemID     uuid.UUID `json:"itemId"`
	Name       string    `json:"name"`
	Quantity   int64     `json:"quantity"`
	SalesCents int64     `json:"salesCents"`
}

// The products and combos sold most, by sales, on the orders paid in
// [from_at, to_at) and not cancelled: units and line totals, before any
// order discount, under the name each has now.
//
//	SELECT
//	  i.line_type,
//	  COALESCE(i.product_id, i.combo_id)::uuid AS item_id,
//	  COALESCE(p.name, c.name)::text AS name,
//	  sum(i.quantity)::bigint AS quantity,
//	  sum(i.line_total_cents)::bigint AS sales_cents
//	FROM order_items i
//	JOIN orders o ON o.id = i.order_id
//	JOIN payments pay ON pay.order_id = o.id
//	LEFT JOIN products p ON p.id = i.product_id
//	LEFT JOIN combos c ON c.id = i.combo_id
//	WHERE pay.captured_at >= $1::timestamptz
//	  AND pay.captured_at < $2::timestamptz
//	  AND o.status <> 'cancelled'::order_status
//	GROUP BY i.line_type, COALESCE(i.product_id, i.combo_id), COALESCE(p.name, c.name)
//	ORDER BY sales_cents DESC, quantity DESC, COALESCE(p.name, c.name)
//	LIMIT $3::int
func (q *Queries) TopSoldItems(ctx context.Context, arg TopSoldItemsParams) ([]TopSoldItemsRow, error) {
	rows, err := q.db.Query(ctx, topSoldItems, arg.FromAt, arg.ToAt, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopSoldItemsRow{}
	for rows.Next() {
		var i TopSoldItemsRow
		if err := rows.Scan(
			&i.LineType,
			&i.ItemID,
			&i.Name,
			&i.Quantity,
			&i.SalesCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
