// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_product.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOtherSavedProducts = `-- name: CountOtherSavedProducts :one
SELECT count(*)::bigint
FROM saved_products s
JOIN products p ON p.id = s.product_id AND p.deleted_at IS NULL AND p.is_active = true
JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE s.user_id = $1
  AND s.list = $2
  AND s.product_id <> $3
  AND s.deleted_at IS NULL
`

type CountOtherSavedProductsParams struct {
	UserID    uuid.UUID `json:"userId"`
	List      SavedList `json:"list"`
	ProductID uuid.UUID `json:"productId"`
}

// How many products on sale the customer's list shows besides the one given.
//
//	SELECT count(*)::bigint
//	FROM saved_products s
//	JOIN products p ON p.id = s.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE s.user_id = $1
//	  AND s.list = $2
//	  AND s.product_id <> $3
//	  AND s.deleted_at IS NULL
func (q *Queries) CountOtherSavedProducts(ctx context.Context, arg CountOtherSavedProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherSavedProducts, arg.UserID, arg.List, arg.ProductID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listSavedProducts = `-- name: ListSavedProducts :many
SELECT
  s.list,
  s.saved_at,
  p.id,
  p.category_id,
  p.name,
  p.slug,
  p.price_cents,
  p.is_customizable,
  p.sold_out_on,
  c.name AS category_name,
  c.slug AS category_slug
FROM saved_products s
JOIN products p ON p.id = s.product_id AND p.deleted_at IS NULL AND p.is_active = true
JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE s.user_id = $1
  AND s.deleted_at IS NULL
ORDER BY s.list, s.saved_at DESC, s.id DESC
`

type ListSavedProductsRow struct {
	List           SavedList  `json:"list"`
	SavedAt        time.Time  `json:"savedAt"`
	ID             uuid.UUID  `json:"id"`
	CategoryID     uuid.UUID  `json:"categoryId"`
	Name           string     `json:"name"`
	Slug           string     `json:"slug"`
	PriceCents     int64      `json:"priceCents"`
	IsCustomizable bool       `json:"isCustomizable"`
	SoldOutOn      *time.Time `json:"soldOutOn"`
	CategoryName   string     `json:"categoryName"`
	CategorySlug   string     `json:"categorySlug"`
}

// Both of the customer's lists, latest first, with each product as the
// catalog shows it. A product the bakery stopped selling is kept but not
// shown, as the catalog does not show it; it is back on the list when it is
// back on sale.
//
//	SELECT
//	  s.list,
//	  s.saved_at,
//	  p.id,
//	  p.category_id,
//	  p.name,
//	  p.slug,
//	  p.price_cents,
//	  p.is_customizable,
//	  p.sold_out_on,
//	  c.name AS category_name,
//	  c.slug AS category_slug
//	FROM saved_products s
//	JOIN products p ON p.id = s.product_id AND p.deleted_at IS NULL AND p.is_active = true
//	JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE s.user_id = $1
//	  AND s.deleted_at IS NULL
//	ORDER BY s.list, s.saved_at DESC, s.id DESC
func (q *Queries) ListSavedProducts(ctx context.Context, userID uuid.UUID) ([]ListSavedProductsRow, error) {
	rows, err := q.db.Query(ctx, listSavedProducts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedProductsRow{}
	for rows.Next() {
		var i ListSavedProductsRow
		if err := rows.Scan(
			&i.List,
			&i.SavedAt,
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.PriceCents,
			&i.IsCustomizable,
			&i.SoldOutOn,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedProductsForExport = `-- name: ListSavedProductsForExport :many
SELECT
  s.list,
  s.saved_at,
  s.deleted_at AS removed_at,
  p.id,
  p.name
FROM saved_products s
JOIN products p ON p.id = s.product_id
WHERE s.user_id = $1
ORDER BY s.list, s.saved_at DESC, s.id DESC
`

type ListSavedProductsForExportRow struct {
	List      SavedList  `json:"list"`
	SavedAt   time.Time  `json:"savedAt"`
	RemovedAt *time.Time `json:"removedAt"`
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
}

// Every product the customer saved to a list, shown or not, taken off or not
// (with when), for a personal data export: what is held about them, whatever
// the bakery does with the product.
//
//	SELECT
//	  s.list,
//	  s.saved_at,
//	  s.deleted_at AS removed_at,
//	  p.id,
//	  p.name
//	FROM saved_products s
//	JOIN products p ON p.id = s.product_id
//	WHERE s.user_id = $1
//	ORDER BY s.list, s.saved_at DESC, s.id DESC
func (q *Queries) ListSavedProductsForExport(ctx context.Context, userID uuid.UUID) ([]ListSavedProductsForExportRow, error) {
	rows, err := q.db.Query(ctx, listSavedProductsForExport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedProductsForExportRow{}
	for rows.Next() {
		var i ListSavedProductsForExportRow
		if err := rows.Scan(
			&i.List,
			&i.SavedAt,
			&i.RemovedAt,
			&i.ID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllSavedProducts = `-- name: RemoveAllSavedProducts :exec
UPDATE saved_products
SET deleted_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND deleted_at IS NULL
`

// Empties the customer's lists as their account is erased.
//
//	UPDATE saved_products
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE user_id = $1
//	  AND deleted_at IS NULL
func (q *Queries) RemoveAllSavedProducts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllSavedProducts, userID)
	return err
}

const removeSavedProduct = `-- name: RemoveSavedProduct :exec
UPDATE saved_products
SET deleted_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND product_id = $2
  AND list = $3
  AND deleted_at IS NULL
`

type RemoveSavedProductParams struct {
	UserID    uuid.UUID `json:"userId"`
	ProductID uuid.UUID `json:"productId"`
	List      SavedList `json:"list"`
}

// RemoveSavedProduct
//
//	UPDATE saved_products
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE user_id = $1
//	  AND product_id = $2
//	  AND list = $3
//	  AND deleted_at IS NULL
func (q *Queries) RemoveSavedProduct(ctx context.Context, arg RemoveSavedProductParams) error {
	_, err := q.db.Exec(ctx, removeSavedProduct, arg.UserID, arg.ProductID, arg.List)
	return err
}

const saveProduct = `-- name: SaveProduct :execrows
INSERT INTO saved_products (user_id, product_id, list)
SELECT $1, p.id, $2
FROM products p
JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
WHERE p.id = $3
  AND p.deleted_at IS NULL
  AND p.is_active = true
ON CONFLICT (user_id, product_id, list) DO UPDATE
SET saved_at = CASE WHEN saved_products.deleted_at IS NULL THEN saved_products.saved_at ELSE now() END,
    deleted_at = NULL,
    updated_at = now()
`

type SaveProductParams struct {
	UserID    uuid.UUID `json:"userId"`
	List      SavedList `json:"list"`
	ProductID uuid.UUID `json:"productId"`
}

// Puts a product on sale on one of the customer's lists, or brings back the
// row they removed. Saving it again leaves it where it is on the list. No row
// is written for a product that is not on sale.
//
//	INSERT INTO saved_products (user_id, product_id, list)
//	SELECT $1, p.id, $2
//	FROM products p
//	JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL AND c.is_active = true
//	WHERE p.id = $3
//	  AND p.deleted_at IS NULL
//	  AND p.is_active = true
//	ON CONFLICT (user_id, product_id, list) DO UPDATE
//	SET saved_at = CASE WHEN saved_products.deleted_at IS NULL THEN saved_products.saved_at ELSE now() END,
//	    deleted_at = NULL,
//	    updated_at = now()
func (q *Queries) SaveProduct(ctx context.Context, arg SaveProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveProduct, arg.UserID, arg.List, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
