// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff_profile.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStaffProfile = `-- name: CreateStaffProfile :one
INSERT INTO staff_profiles (user_id, full_name, phone, employee_code)
VALUES ($1, $2, $3, $4)
RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
`

type CreateStaffProfileParams struct {
	UserID       uuid.UUID      `db:"user_id" json:"userId"`
	FullName     string         `db:"full_name" json:"fullName"`
	Phone        sql.NullString `db:"phone" json:"phone"`
	EmployeeCode string         `db:"employee_code" json:"employeeCode"`
}

// CreateStaffProfile
//
//	INSERT INTO staff_profiles (user_id, full_name, phone, employee_code)
//	VALUES ($1, $2, $3, $4)
//	RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
func (q *Queries) CreateStaffProfile(ctx context.Context, arg CreateStaffProfileParams) (StaffProfile, error) {
	row := q.db.QueryRowContext(ctx, createStaffProfile,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.EmployeeCode,
	)
	var i StaffProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.EmployeeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffProfileByUserID = `-- name: DeleteStaffProfileByUserID :execrows
DELETE FROM staff_profiles
WHERE user_id = $1
`

// DeleteStaffProfileByUserID
//
//	DELETE FROM staff_profiles
//	WHERE user_id = $1
func (q *Queries) DeleteStaffProfileByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaffProfileByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStaffProfileByUserID = `-- name: GetStaffProfileByUserID :one
SELECT user_id, full_name, phone, employee_code, created_at, updated_at
FROM staff_profiles
WHERE user_id = $1
`

// GetStaffProfileByUserID
//
//	SELECT user_id, full_name, phone, employee_code, created_at, updated_at
//	FROM staff_profiles
//	WHERE user_id = $1
func (q *Queries) GetStaffProfileByUserID(ctx context.Context, userID uuid.UUID) (StaffProfile, error) {
	row := q.db.QueryRowContext(ctx, getStaffProfileByUserID, userID)
	var i StaffProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.EmployeeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStaffProfileByUserID = `-- name: UpdateStaffProfileByUserID :one
UPDATE staff_profiles
SET full_name = $2,
    phone = $3,
    employee_code = $4,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
`

type UpdateStaffProfileByUserIDParams struct {
	UserID       uuid.UUID      `db:"user_id" json:"userId"`
	FullName     string         `db:"full_name" json:"fullName"`
	Phone        sql.NullString `db:"phone" json:"phone"`
	EmployeeCode string         `db:"employee_code" json:"employeeCode"`
}

// UpdateStaffProfileByUserID
//
//	UPDATE staff_profiles
//	SET full_name = $2,
//	    phone = $3,
//	    employee_code = $4,
//	    updated_at = now()
//	WHERE user_id = $1
//	RETURNING user_id, full_name, phone, employee_code, created_at, updated_at
func (q *Queries) UpdateStaffProfileByUserID(ctx context.Context, arg UpdateStaffProfileByUserIDParams) (StaffProfile, error) {
	row := q.db.QueryRowContext(ctx, updateStaffProfileByUserID,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.EmployeeCode,
	)
	var i StaffProfile
	err := row.Scan(
		&i.UserID,
		&i.FullName,
		&i.Phone,
		&i.EmployeeCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
