// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_settings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStoreClosedDate = `-- name: CreateStoreClosedDate :one
INSERT INTO store_closed_dates (closed_on, reason)
VALUES ($1, $2)
RETURNING id, closed_on, reason, created_at
`

type CreateStoreClosedDateParams struct {
	ClosedOn time.Time `json:"closedOn"`
	Reason   string    `json:"reason"`
}

type CreateStoreClosedDateRow struct {
	ID        uuid.UUID `json:"id"`
	ClosedOn  time.Time `json:"closedOn"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"createdAt"`
}

// CreateStoreClosedDate
//
//	INSERT INTO store_closed_dates (closed_on, reason)
//	VALUES ($1, $2)
//	RETURNING id, closed_on, reason, created_at
func (q *Queries) CreateStoreClosedDate(ctx context.Context, arg CreateStoreClosedDateParams) (CreateStoreClosedDateRow, error) {
	row := q.db.QueryRow(ctx, createStoreClosedDate, arg.ClosedOn, arg.Reason)
	var i CreateStoreClosedDateRow
	err := row.Scan(
		&i.ID,
		&i.ClosedOn,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getStoreSettings = `-- name: GetStoreSettings :one
SELECT opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
FROM store_settings
WHERE id = 1
`

type GetStoreSettingsRow struct {
	OpensAtMinute          int16     `json:"opensAtMinute"`
	ClosesAtMinute         int16     `json:"closesAtMinute"`
	PreorderMinLeadMinutes int32     `json:"preorderMinLeadMinutes"`
	MaxAdvanceDays         int16     `json:"maxAdvanceDays"`
	SlotMinutes            int16     `json:"slotMinutes"`
	SlotCapacity           int16     `json:"slotCapacity"`
	InstantPrepMinutes     int16     `json:"instantPrepMinutes"`
	UpdatedAt              time.Time `json:"updatedAt"`
}

// GetStoreSettings
//
//	SELECT opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
//	FROM store_settings
//	WHERE id = 1
func (q *Queries) GetStoreSettings(ctx context.Context) (GetStoreSettingsRow, error) {
	row := q.db.QueryRow(ctx, getStoreSettings)
	var i GetStoreSettingsRow
	err := row.Scan(
		&i.OpensAtMinute,
		&i.ClosesAtMinute,
		&i.PreorderMinLeadMinutes,
		&i.MaxAdvanceDays,
		&i.SlotMinutes,
		&i.SlotCapacity,
		&i.InstantPrepMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreSettingsForUpdate = `-- name: GetStoreSettingsForUpdate :one
SELECT opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
FROM store_settings
WHERE id = 1
FOR UPDATE
`

type GetStoreSettingsForUpdateRow struct {
	OpensAtMinute          int16     `json:"opensAtMinute"`
	ClosesAtMinute         int16     `json:"closesAtMinute"`
	PreorderMinLeadMinutes int32     `json:"preorderMinLeadMinutes"`
	MaxAdvanceDays         int16     `json:"maxAdvanceDays"`
	SlotMinutes            int16     `json:"slotMinutes"`
	SlotCapacity           int16     `json:"slotCapacity"`
	InstantPrepMinutes     int16     `json:"instantPrepMinutes"`
	UpdatedAt              time.Time `json:"updatedAt"`
}

// Locks the row so two admins editing at once cannot undo each other.
//
//	SELECT opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
//	FROM store_settings
//	WHERE id = 1
//	FOR UPDATE
func (q *Queries) GetStoreSettingsForUpdate(ctx context.Context) (GetStoreSettingsForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getStoreSettingsForUpdate)
	var i GetStoreSettingsForUpdateRow
	err := row.Scan(
		&i.OpensAtMinute,
		&i.ClosesAtMinute,
		&i.PreorderMinLeadMinutes,
		&i.MaxAdvanceDays,
		&i.SlotMinutes,
		&i.SlotCapacity,
		&i.InstantPrepMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoreClosedDates = `-- name: ListStoreClosedDates :many
SELECT id, closed_on, reason, created_at
FROM store_closed_dates
WHERE deleted_at IS NULL
  AND closed_on BETWEEN $1::date AND $2::date
ORDER BY closed_on
LIMIT $3::int
`

type ListStoreClosedDatesParams struct {
	FromDay time.Time `json:"fromDay"`
	ToDay   time.Time `json:"toDay"`
	MaxRows int32     `json:"maxRows"`
}

type ListStoreClosedDatesRow struct {
	ID        uuid.UUID `json:"id"`
	ClosedOn  time.Time `json:"closedOn"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"createdAt"`
}

// Days in [from_day, to_day]; the caller bounds the window, and one row per
// day keeps the result bounded by it.
//
//	SELECT id, closed_on, reason, created_at
//	FROM store_closed_dates
//	WHERE deleted_at IS NULL
//	  AND closed_on BETWEEN $1::date AND $2::date
//	ORDER BY closed_on
//	LIMIT $3::int
func (q *Queries) ListStoreClosedDates(ctx context.Context, arg ListStoreClosedDatesParams) ([]ListStoreClosedDatesRow, error) {
	rows, err := q.db.Query(ctx, listStoreClosedDates, arg.FromDay, arg.ToDay, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoreClosedDatesRow{}
	for rows.Next() {
		var i ListStoreClosedDatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClosedOn,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStoreClosedDate = `-- name: SoftDeleteStoreClosedDate :one
UPDATE store_closed_dates
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, closed_on, reason, created_at
`

type SoftDeleteStoreClosedDateRow struct {
	ID        uuid.UUID `json:"id"`
	ClosedOn  time.Time `json:"closedOn"`
	Reason    string    `json:"reason"`
	CreatedAt time.Time `json:"createdAt"`
}

// SoftDeleteStoreClosedDate
//
//	UPDATE store_closed_dates
//	SET deleted_at = now(), updated_at = now()
//	WHERE id = $1 AND deleted_at IS NULL
//	RETURNING id, closed_on, reason, created_at
func (q *Queries) SoftDeleteStoreClosedDate(ctx context.Context, id uuid.UUID) (SoftDeleteStoreClosedDateRow, error) {
	row := q.db.QueryRow(ctx, softDeleteStoreClosedDate, id)
	var i SoftDeleteStoreClosedDateRow
	err := row.Scan(
		&i.ID,
		&i.ClosedOn,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const updateStoreSettings = `-- name: UpdateStoreSettings :one
UPDATE store_settings
SET opens_at_minute = $1,
    closes_at_minute = $2,
    preorder_min_lead_minutes = $3,
    max_advance_days = $4,
    slot_minutes = $5,
    slot_capacity = $6,
    instant_prep_minutes = $7,
    updated_at = now()
WHERE id = 1
RETURNING opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
`

type UpdateStoreSettingsParams struct {
	OpensAtMinute          int16 `json:"opensAtMinute"`
	ClosesAtMinute         int16 `json:"closesAtMinute"`
	PreorderMinLeadMinutes int32 `json:"preorderMinLeadMinutes"`
	MaxAdvanceDays         int16 `json:"maxAdvanceDays"`
	SlotMinutes            int16 `json:"slotMinutes"`
	SlotCapacity           int16 `json:"slotCapacity"`
	InstantPrepMinutes     int16 `json:"instantPrepMinutes"`
}

type UpdateStoreSettingsRow struct {
	OpensAtMinute          int16     `json:"opensAtMinute"`
	ClosesAtMinute         int16     `json:"closesAtMinute"`
	PreorderMinLeadMinutes int32     `json:"preorderMinLeadMinutes"`
	MaxAdvanceDays         int16     `json:"maxAdvanceDays"`
	SlotMinutes            int16     `json:"slotMinutes"`
	SlotCapacity           int16     `json:"slotCapacity"`
	InstantPrepMinutes     int16     `json:"instantPrepMinutes"`
	UpdatedAt              time.Time `json:"updatedAt"`
}

// UpdateStoreSettings
//
//	UPDATE store_settings
//	SET opens_at_minute = $1,
//	    closes_at_minute = $2,
//	    preorder_min_lead_minutes = $3,
//	    max_advance_days = $4,
//	    slot_minutes = $5,
//	    slot_capacity = $6,
//	    instant_prep_minutes = $7,
//	    updated_at = now()
//	WHERE id = 1
//	RETURNING opens_at_minute, closes_at_minute, preorder_min_lead_minutes, max_advance_days, slot_minutes, slot_capacity, instant_prep_minutes, updated_at
func (q *Queries) UpdateStoreSettings(ctx context.Context, arg UpdateStoreSettingsParams) (UpdateStoreSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateStoreSettings,
		arg.OpensAtMinute,
		arg.ClosesAtMinute,
		arg.PreorderMinLeadMinutes,
		arg.MaxAdvanceDays,
		arg.SlotMinutes,
		arg.SlotCapacity,
		arg.InstantPrepMinutes,
	)
	var i UpdateStoreSettingsRow
	err := row.Scan(
		&i.OpensAtMinute,
		&i.ClosesAtMinute,
		&i.PreorderMinLeadMinutes,
		&i.MaxAdvanceDays,
		&i.SlotMinutes,
		&i.SlotCapacity,
		&i.InstantPrepMinutes,
		&i.UpdatedAt,
	)
	return i, err
}
