// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelOrderTickets = `-- name: CancelOrderTickets :many
UPDATE order_tickets
SET status = 'cancelled'::ticket_status,
    updated_at = now()
WHERE order_id = $1
  AND status <> 'cancelled'::ticket_status
RETURNING id, order_id, station, status, created_at, updated_at
`

// CancelOrderTickets
//
//	UPDATE order_tickets
//	SET status = 'cancelled'::ticket_status,
//	    updated_at = now()
//	WHERE order_id = $1
//	  AND status <> 'cancelled'::ticket_status
//	RETURNING id, order_id, station, status, created_at, updated_at
func (q *Queries) CancelOrderTickets(ctx context.Context, orderID uuid.UUID) ([]OrderTicket, error) {
	rows, err := q.db.Query(ctx, cancelOrderTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTicket{}
	for rows.Next() {
		var i OrderTicket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Station,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStationTickets = `-- name: CountStationTickets :one
SELECT count(*)::bigint AS count
FROM order_tickets t
INNER JOIN orders o ON o.id = t.order_id
INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
WHERE t.station = $1::station
  AND t.status <> 'cancelled'::ticket_status
  AND o.status IN ('confirmed'::order_status, 'in_production'::order_status, 'ready'::order_status)
  AND (
    $2::ticket_status IS NULL
    OR t.status = $2::ticket_status
  )
`

type CountStationTicketsParams struct {
	Station Station       `json:"station"`
	Status  *TicketStatus `json:"status"`
}

// CountStationTickets
//
//	SELECT count(*)::bigint AS count
//	FROM order_tickets t
//	INNER JOIN orders o ON o.id = t.order_id
//	INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	WHERE t.station = $1::station
//	  AND t.status <> 'cancelled'::ticket_status
//	  AND o.status IN ('confirmed'::order_status, 'in_production'::order_status, 'ready'::order_status)
//	  AND (
//	    $2::ticket_status IS NULL
//	    OR t.status = $2::ticket_status
//	  )
func (q *Queries) CountStationTickets(ctx context.Context, arg CountStationTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStationTickets, arg.Station, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderTicketItems = `-- name: CreateOrderTicketItems :execrows
INSERT INTO order_ticket_items (ticket_id, order_item_id, product_id, name, quantity)
SELECT item.ticket_id, item.order_item_id, item.product_id, item.name, item.quantity
FROM jsonb_to_recordset($1::jsonb) AS item (
  ticket_id uuid,
  order_item_id uuid,
  product_id uuid,
  name text,
  quantity integer
)
`

// CreateOrderTicketItems
//
//	INSERT INTO order_ticket_items (ticket_id, order_item_id, product_id, name, quantity)
//	SELECT item.ticket_id, item.order_item_id, item.product_id, item.name, item.quantity
//	FROM jsonb_to_recordset($1::jsonb) AS item (
//	  ticket_id uuid,
//	  order_item_id uuid,
//	  product_id uuid,
//	  name text,
//	  quantity integer
//	)
func (q *Queries) CreateOrderTicketItems(ctx context.Context, items json.RawMessage) (int64, error) {
	result, err := q.db.Exec(ctx, createOrderTicketItems, items)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrderTickets = `-- name: CreateOrderTickets :many
INSERT INTO order_tickets (order_id, station)
SELECT $1, ticket.station
FROM jsonb_to_recordset($2::jsonb) AS ticket (station station)
RETURNING id, order_id, station, status, created_at, updated_at
`

type CreateOrderTicketsParams struct {
	OrderID uuid.UUID       `json:"orderId"`
	Tickets json.RawMessage `json:"tickets"`
}

// One statement for every station of an order, like CreateOrderItems.
//
//	INSERT INTO order_tickets (order_id, station)
//	SELECT $1, ticket.station
//	FROM jsonb_to_recordset($2::jsonb) AS ticket (station station)
//	RETURNING id, order_id, station, status, created_at, updated_at
func (q *Queries) CreateOrderTickets(ctx context.Context, arg CreateOrderTicketsParams) ([]OrderTicket, error) {
	rows, err := q.db.Query(ctx, createOrderTickets, arg.OrderID, arg.Tickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTicket{}
	for rows.Next() {
		var i OrderTicket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Station,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderTicket = `-- name: GetOrderTicket :one
SELECT id, order_id, station, status, created_at, updated_at
FROM order_tickets
WHERE id = $1
`

// GetOrderTicket
//
//	SELECT id, order_id, station, status, created_at, updated_at
//	FROM order_tickets
//	WHERE id = $1
func (q *Queries) GetOrderTicket(ctx context.Context, id uuid.UUID) (OrderTicket, error) {
	row := q.db.QueryRow(ctx, getOrderTicket, id)
	var i OrderTicket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Station,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderTicketItems = `-- name: ListOrderTicketItems :many
SELECT i.ticket_id, i.order_item_id, i.product_id, i.name, i.quantity, oi.configuration
FROM order_ticket_items i
INNER JOIN order_tickets t ON t.id = i.ticket_id
INNER JOIN order_items oi ON oi.id = i.order_item_id
WHERE t.order_id = $1
ORDER BY i.created_at, i.name
`

type ListOrderTicketItemsRow struct {
	TicketID      uuid.UUID       `json:"ticketId"`
	OrderItemID   uuid.UUID       `json:"orderItemId"`
	ProductID     uuid.UUID       `json:"productId"`
	Name          string          `json:"name"`
	Quantity      int32           `json:"quantity"`
	Configuration json.RawMessage `json:"configuration"`
}

// The items of every ticket of an order, with what the customer configured.
//
//	SELECT i.ticket_id, i.order_item_id, i.product_id, i.name, i.quantity, oi.configuration
//	FROM order_ticket_items i
//	INNER JOIN order_tickets t ON t.id = i.ticket_id
//	INNER JOIN order_items oi ON oi.id = i.order_item_id
//	WHERE t.order_id = $1
//	ORDER BY i.created_at, i.name
func (q *Queries) ListOrderTicketItems(ctx context.Context, orderID uuid.UUID) ([]ListOrderTicketItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderTicketItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderTicketItemsRow{}
	for rows.Next() {
		var i ListOrderTicketItemsRow
		if err := rows.Scan(
			&i.TicketID,
			&i.OrderItemID,
			&i.ProductID,
			&i.Name,
			&i.Quantity,
			&i.Configuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderTicketLines = `-- name: ListOrderTicketLines :many
SELECT
  oi.id AS order_item_id,
  p.id AS product_id,
  oi.name,
  c.station,
  oi.quantity::int AS quantity
FROM order_items oi
INNER JOIN products p ON p.id = oi.product_id
INNER JOIN categories c ON c.id = p.category_id
WHERE oi.order_id = $1
  AND oi.line_type = 'product'
UNION ALL
SELECT
  oi.id AS order_item_id,
  p.id AS product_id,
  p.name,
  c.station,
  (oi.quantity * ci.quantity)::int AS quantity
FROM order_items oi
INNER JOIN combo_items ci ON ci.combo_id = oi.combo_id
INNER JOIN products p ON p.id = ci.product_id
INNER JOIN categories c ON c.id = p.category_id
WHERE oi.order_id = $1
  AND oi.line_type = 'combo'
`

type ListOrderTicketLinesRow struct {
	OrderItemID uuid.UUID `json:"orderItemId"`
	ProductID   uuid.UUID `json:"productId"`
	Name        string    `json:"name"`
	Station     Station   `json:"station"`
	Quantity    int32     `json:"quantity"`
}

// What an order's lines ask each station to make: a product line itself, by
// the name on the receipt, and every product a combo line holds, times the
// line's quantity.
//
//	SELECT
//	  oi.id AS order_item_id,
//	  p.id AS product_id,
//	  oi.name,
//	  c.station,
//	  oi.quantity::int AS quantity
//	FROM order_items oi
//	INNER JOIN products p ON p.id = oi.product_id
//	INNER JOIN categories c ON c.id = p.category_id
//	WHERE oi.order_id = $1
//	  AND oi.line_type = 'product'
//	UNION ALL
//	SELECT
//	  oi.id AS order_item_id,
//	  p.id AS product_id,
//	  p.name,
//	  c.station,
//	  (oi.quantity * ci.quantity)::int AS quantity
//	FROM order_items oi
//	INNER JOIN combo_items ci ON ci.combo_id = oi.combo_id
//	INNER JOIN products p ON p.id = ci.product_id
//	INNER JOIN categories c ON c.id = p.category_id
//	WHERE oi.order_id = $1
//	  AND oi.line_type = 'combo'
func (q *Queries) ListOrderTicketLines(ctx context.Context, orderID uuid.UUID) ([]ListOrderTicketLinesRow, error) {
	rows, err := q.db.Query(ctx, listOrderTicketLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderTicketLinesRow{}
	for rows.Next() {
		var i ListOrderTicketLinesRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.ProductID,
			&i.Name,
			&i.Station,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderTickets = `-- name: ListOrderTickets :many
SELECT id, order_id, station, status, created_at, updated_at
FROM order_tickets
WHERE order_id = $1
ORDER BY station
`

// ListOrderTickets
//
//	SELECT id, order_id, station, status, created_at, updated_at
//	FROM order_tickets
//	WHERE order_id = $1
//	ORDER BY station
func (q *Queries) ListOrderTickets(ctx context.Context, orderID uuid.UUID) ([]OrderTicket, error) {
	rows, err := q.db.Query(ctx, listOrderTickets, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTicket{}
	for rows.Next() {
		var i OrderTicket
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Station,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationTickets = `-- name: ListStationTickets :many
SELECT
  page.id,
  page.order_id,
  page.station,
  page.status,
  page.created_at,
  page.updated_at,
  page.order_code,
  page.order_status,
  page.pickup_at,
  page.customer_display_name,
  COALESCE(items.list, '[]'::json)::json AS items
FROM (
  SELECT
    t.id,
    t.order_id,
    t.station,
    t.status,
    t.created_at,
    t.updated_at,
    o.code AS order_code,
    o.status AS order_status,
    o.pickup_at,
    cp.display_name AS customer_display_name
  FROM order_tickets t
  INNER JOIN orders o ON o.id = t.order_id
  INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
  LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
  WHERE t.station = $1::station
    AND t.status <> 'cancelled'::ticket_status
    AND o.status IN ('confirmed'::order_status, 'in_production'::order_status, 'ready'::order_status)
    AND (
      $2::ticket_status IS NULL
      OR t.status = $2::ticket_status
    )
  ORDER BY o.pickup_at ASC NULLS LAST, t.created_at ASC, t.id ASC
  LIMIT $4 OFFSET $3
) page
LEFT JOIN LATERAL (
  SELECT json_agg(json_build_object('name', i.name, 'quantity', i.quantity) ORDER BY i.created_at, i.name) AS list
  FROM order_ticket_items i
  WHERE i.ticket_id = page.id
) items ON true
ORDER BY page.pickup_at ASC NULLS LAST, page.created_at ASC, page.id ASC
`

type ListStationTicketsParams struct {
	Station Station       `json:"station"`
	Status  *TicketStatus `json:"status"`
	Offset  int32         `json:"offset"`
	Limit   int32         `json:"limit"`
}

type ListStationTicketsRow struct {
	ID                  uuid.UUID    `json:"id"`
	OrderID             uuid.UUID    `json:"orderId"`
	Station             Station      `json:"station"`
	Status              TicketStatus `json:"status"`
	CreatedAt           time.Time    `json:"createdAt"`
	UpdatedAt           time.Time    `json:"updatedAt"`
	OrderCode           string       `json:"orderCode"`
	OrderStatus         OrderStatus  `json:"orderStatus"`
	PickupAt            *time.Time   `json:"pickupAt"`
	CustomerDisplayName *string      `json:"customerDisplayName"`
	Items               []byte       `json:"items"`
}

// A station's queue: its tickets of orders accepted and not yet collected,
// soonest pickup first, each with what it makes. The page is cut first and
// the items gathered after, as in CatalogListProducts.
//
//	SELECT
//	  page.id,
//	  page.order_id,
//	  page.station,
//	  page.status,
//	  page.created_at,
//	  page.updated_at,
//	  page.order_code,
//	  page.order_status,
//	  page.pickup_at,
//	  page.customer_display_name,
//	  COALESCE(items.list, '[]'::json)::json AS items
//	FROM (
//	  SELECT
//	    t.id,
//	    t.order_id,
//	    t.station,
//	    t.status,
//	    t.created_at,
//	    t.updated_at,
//	    o.code AS order_code,
//	    o.status AS order_status,
//	    o.pickup_at,
//	    cp.display_name AS customer_display_name
//	  FROM order_tickets t
//	  INNER JOIN orders o ON o.id = t.order_id
//	  INNER JOIN users u ON u.id = o.user_id AND u.deleted_at IS NULL
//	  LEFT JOIN customer_profiles cp ON cp.user_id = o.user_id
//	  WHERE t.station = $1::station
//	    AND t.status <> 'cancelled'::ticket_status
//	    AND o.status IN ('confirmed'::order_status, 'in_production'::order_status, 'ready'::order_status)
//	    AND (
//	      $2::ticket_status IS NULL
//	      OR t.status = $2::ticket_status
//	    )
//	  ORDER BY o.pickup_at ASC NULLS LAST, t.created_at ASC, t.id ASC
//	  LIMIT $4 OFFSET $3
//	) page
//	LEFT JOIN LATERAL (
//	  SELECT json_agg(json_build_object('name', i.name, 'quantity', i.quantity) ORDER BY i.created_at, i.name) AS list
//	  FROM order_ticket_items i
//	  WHERE i.ticket_id = page.id
//	) items ON true
//	ORDER BY page.pickup_at ASC NULLS LAST, page.created_at ASC, page.id ASC
func (q *Queries) ListStationTickets(ctx context.Context, arg ListStationTicketsParams) ([]ListStationTicketsRow, error) {
	rows, err := q.db.Query(ctx, listStationTickets,
		arg.Station,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationTicketsRow{}
	for rows.Next() {
		var i ListStationTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Station,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderCode,
			&i.OrderStatus,
			&i.PickupAt,
			&i.CustomerDisplayName,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveOrderTicket = `-- name: MoveOrderTicket :one
UPDATE order_tickets
SET station = $1::station,
    updated_at = now()
WHERE id = $2
  AND station = $3::station
  AND status = 'queued'::ticket_status
RETURNING id, order_id, station, status, created_at, updated_at
`

type MoveOrderTicketParams struct {
	ToStation   Station   `json:"toStation"`
	ID          uuid.UUID `json:"id"`
	FromStation Station   `json:"fromStation"`
}

// Only a ticket nobody has started moves; the order's unique ticket per
// station refuses a station that already has one.
//
//	UPDATE order_tickets
//	SET station = $1::station,
//	    updated_at = now()
//	WHERE id = $2
//	  AND station = $3::station
//	  AND status = 'queued'::ticket_status
//	RETURNING id, order_id, station, status, created_at, updated_at
func (q *Queries) MoveOrderTicket(ctx context.Context, arg MoveOrderTicketParams) (OrderTicket, error) {
	row := q.db.QueryRow(ctx, moveOrderTicket, arg.ToStation, arg.ID, arg.FromStation)
	var i OrderTicket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Station,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderTicketStatus = `-- name: UpdateOrderTicketStatus :one
UPDATE order_tickets
SET status = $1::ticket_status,
    updated_at = now()
WHERE id = $2
  AND station = $3::station
  AND status = $4::ticket_status
RETURNING id, order_id, station, status, created_at, updated_at
`

type UpdateOrderTicketStatusParams struct {
	ToStatus   TicketStatus `json:"toStatus"`
	ID         uuid.UUID    `json:"id"`
	Station    Station      `json:"station"`
	FromStatus TicketStatus `json:"fromStatus"`
}

// A move made at the ticket's own station; a ticket that already moved on, or
// sits at another station, is left alone.
//
//	UPDATE order_tickets
//	SET status = $1::ticket_status,
//	    updated_at = now()
//	WHERE id = $2
//	  AND station = $3::station
//	  AND status = $4::ticket_status
//	RETURNING id, order_id, station, status, created_at, updated_at
func (q *Queries) UpdateOrderTicketStatus(ctx context.Context, arg UpdateOrderTicketStatusParams) (OrderTicket, error) {
	row := q.db.QueryRow(ctx, updateOrderTicketStatus,
		arg.ToStatus,
		arg.ID,
		arg.Station,
		arg.FromStatus,
	)
	var i OrderTicket
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Station,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
