// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCreate = `-- name: AdminCreate :one
INSERT INTO users (email, password_hash, role, must_change_password, email_verified_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
`

type AdminCreateParams struct {
	Email              string   `json:"email"`
	PasswordHash       string   `json:"passwordHash"`
	Role               UserRole `json:"role"`
	MustChangePassword bool     `json:"mustChangePassword"`
}

type AdminCreateRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// An administrator vouches for the address of an account they create: it
// counts as confirmed.
//
//	INSERT INTO users (email, password_hash, role, must_change_password, email_verified_at)
//	VALUES ($1, $2, $3, $4, now())
//	RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
func (q *Queries) AdminCreate(ctx context.Context, arg AdminCreateParams) (AdminCreateRow, error) {
	row := q.db.QueryRow(ctx, adminCreate,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i AdminCreateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const adminGetByID = `-- name: AdminGetByID :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
FROM users
WHERE id = $1
`

type AdminGetByIDRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// AdminGetByID
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
//	FROM users
//	WHERE id = $1
func (q *Queries) AdminGetByID(ctx context.Context, id uuid.UUID) (AdminGetByIDRow, error) {
	row := q.db.QueryRow(ctx, adminGetByID, id)
	var i AdminGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const adminGetByIDForUpdate = `-- name: AdminGetByIDForUpdate :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
FROM users
WHERE id = $1
FOR UPDATE
`

type AdminGetByIDForUpdateRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// Disabled rows included, like AdminGetByID: the caller reports "user is disabled".
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
//	FROM users
//	WHERE id = $1
//	FOR UPDATE
func (q *Queries) AdminGetByIDForUpdate(ctx context.Context, id uuid.UUID) (AdminGetByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, adminGetByIDForUpdate, id)
	var i AdminGetByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const adminList = `-- name: AdminList :many
SELECT
    u.id,
    u.email,
    u.role,
    u.email_verified_at,
    u.must_change_password,
    u.created_at,
    u.updated_at,
    u.deleted_at,
    u.erased_at,
    cp.display_name,
    COALESCE(sp.full_name, ap.full_name, '') AS full_name,
    COALESCE(sp.phone, ap.phone, cp.phone) AS phone,
    COALESCE(sp.employee_code, ''::citext) AS employee_code
FROM users u
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
LEFT JOIN staff_profiles sp ON sp.user_id = u.id
LEFT JOIN admin_profiles ap ON ap.user_id = u.id
WHERE (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
  )
  AND (
    $2::text = ''
    OR u.role::text = $2
  )
ORDER BY u.created_at DESC
LIMIT $4 OFFSET $3
`

type AdminListParams struct {
	Search     string `json:"search"`
	RoleFilter string `json:"roleFilter"`
	Offset     int32  `json:"offset"`
	Limit      int32  `json:"limit"`
}

type AdminListRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
	DisplayName        *string    `json:"displayName"`
	FullName           string     `json:"fullName"`
	Phone              *string    `json:"phone"`
	EmployeeCode       string     `json:"employeeCode"`
}

// AdminList
//
//	SELECT
//	    u.id,
//	    u.email,
//	    u.role,
//	    u.email_verified_at,
//	    u.must_change_password,
//	    u.created_at,
//	    u.updated_at,
//	    u.deleted_at,
//	    u.erased_at,
//	    cp.display_name,
//	    COALESCE(sp.full_name, ap.full_name, '') AS full_name,
//	    COALESCE(sp.phone, ap.phone, cp.phone) AS phone,
//	    COALESCE(sp.employee_code, ''::citext) AS employee_code
//	FROM users u
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	LEFT JOIN staff_profiles sp ON sp.user_id = u.id
//	LEFT JOIN admin_profiles ap ON ap.user_id = u.id
//	WHERE (
//	    $1::text = ''
//	    OR u.email ILIKE '%' || $1 || '%'
//	    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
//	    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
//	  )
//	  AND (
//	    $2::text = ''
//	    OR u.role::text = $2
//	  )
//	ORDER BY u.created_at DESC
//	LIMIT $4 OFFSET $3
func (q *Queries) AdminList(ctx context.Context, arg AdminListParams) ([]AdminListRow, error) {
	rows, err := q.db.Query(ctx, adminList,
		arg.Search,
		arg.RoleFilter,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRow{}
	for rows.Next() {
		var i AdminListRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.EmailVerifiedAt,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ErasedAt,
			&i.DisplayName,
			&i.FullName,
			&i.Phone,
			&i.EmployeeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCount = `-- name: AdminListCount :one
SELECT COUNT(*)
FROM users u
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
LEFT JOIN staff_profiles sp ON sp.user_id = u.id
LEFT JOIN admin_profiles ap ON ap.user_id = u.id
WHERE (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
  )
  AND (
    $2::text = ''
    OR u.role::text = $2
  )
`

type AdminListCountParams struct {
	Search     string `json:"search"`
	RoleFilter string `json:"roleFilter"`
}

// AdminListCount
//
//	SELECT COUNT(*)
//	FROM users u
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	LEFT JOIN staff_profiles sp ON sp.user_id = u.id
//	LEFT JOIN admin_profiles ap ON ap.user_id = u.id
//	WHERE (
//	    $1::text = ''
//	    OR u.email ILIKE '%' || $1 || '%'
//	    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
//	    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
//	  )
//	  AND (
//	    $2::text = ''
//	    OR u.role::text = $2
//	  )
func (q *Queries) AdminListCount(ctx context.Context, arg AdminListCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminListCount, arg.Search, arg.RoleFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminRestore = `-- name: AdminRestore :execrows
UPDATE users
SET deleted_at = NULL,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NOT NULL
  AND erased_at IS NULL
`

// An erased account never comes back: its details are gone for good.
//
//	UPDATE users
//	SET deleted_at = NULL,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NOT NULL
//	  AND erased_at IS NULL
func (q *Queries) AdminRestore(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminRestore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdateUserPassword = `-- name: AdminUpdateUserPassword :execrows
UPDATE users
SET password_hash = $2,
    must_change_password = true,
    session_version = session_version + 1,
    updated_at = now()
WHERE id = $1
`

type AdminUpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"passwordHash"`
}

// AdminUpdateUserPassword
//
//	UPDATE users
//	SET password_hash = $2,
//	    must_change_password = true,
//	    session_version = session_version + 1,
//	    updated_at = now()
//	WHERE id = $1
func (q *Queries) AdminUpdateUserPassword(ctx context.Context, arg AdminUpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpSessionVersion = `-- name: BumpSessionVersion :execrows
UPDATE users
SET session_version = session_version + 1,
    updated_at = now()
WHERE id = $1
`

// Ends every session of the account: refresh tokens of the old version are
// refused. A disabled account counts too, as it may be enabled again.
//
//	UPDATE users
//	SET session_version = session_version + 1,
//	    updated_at = now()
//	WHERE id = $1
func (q *Queries) BumpSessionVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bumpSessionVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearMustChangePassword = `-- name: ClearMustChangePassword :execrows
UPDATE users
SET must_change_password = false,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// ClearMustChangePassword
//
//	UPDATE users
//	SET must_change_password = false,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) ClearMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearMustChangePassword, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, must_change_password, terms_version, terms_accepted_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::text,
  CASE WHEN $5::text IS NULL THEN NULL ELSE now() END
)
RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
`

type CreateUserParams struct {
	Email              string   `json:"email"`
	PasswordHash       string   `json:"passwordHash"`
	Role               UserRole `json:"role"`
	MustChangePassword bool     `json:"mustChangePassword"`
	TermsVersion       *string  `json:"termsVersion"`
}

type CreateUserRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// A version means the person accepted those terms as the account was created.
//
//	INSERT INTO users (email, password_hash, role, must_change_password, terms_version, terms_accepted_at)
//	VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5::text,
//	  CASE WHEN $5::text IS NULL THEN NULL ELSE now() END
//	)
//	RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
		arg.TermsVersion,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const eraseUser = `-- name: EraseUser :execrows
UPDATE users
SET email = 'erased-' || id::text || '@erased.invalid',
    password_hash = 'erased',
    must_change_password = false,
    deleted_at = now(),
    erased_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// Erases an account's personal details at its owner's request and closes it.
// The email becomes a placeholder nobody can sign in with or receive mail at
// (RFC 2606 reserves .invalid), freeing the address, and the password can no
// longer match. The row stays, so the orders it placed remain the bakery's
// anonymous sales records.
//
//	UPDATE users
//	SET email = 'erased-' || id::text || '@erased.invalid',
//	    password_hash = 'erased',
//	    must_change_password = false,
//	    deleted_at = now(),
//	    erased_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) EraseUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eraseUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at, session_version
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
	SessionVersion     int32      `json:"sessionVersion"`
}

// GetUserByEmail
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at, session_version
//	FROM users
//	WHERE email = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
		&i.SessionVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at, session_version
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
	SessionVersion     int32      `json:"sessionVersion"`
}

// GetUserByID
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at, session_version
//	FROM users
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
		&i.SessionVersion,
	)
	return i, err
}

const getUserByIDForShare = `-- name: GetUserByIDForShare :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
FOR SHARE
`

type GetUserByIDForShareRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// Holds the account open until the transaction ends: closing it (an erasure, a
// disable) waits, and a reader that waited on a closing finds no row.
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
//	FROM users
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	FOR SHARE
func (q *Queries) GetUserByIDForShare(ctx context.Context, id uuid.UUID) (GetUserByIDForShareRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForShare, id)
	var i GetUserByIDForShareRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

type GetUserByIDForUpdateRow struct {
	ID                 uuid.UUID  `json:"id"`
	Email              string     `json:"email"`
	PasswordHash       string     `json:"passwordHash"`
	Role               UserRole   `json:"role"`
	EmailVerifiedAt    *time.Time `json:"emailVerifiedAt"`
	MustChangePassword bool       `json:"mustChangePassword"`
	CreatedAt          time.Time  `json:"createdAt"`
	UpdatedAt          time.Time  `json:"updatedAt"`
	DeletedAt          *time.Time `json:"deletedAt"`
	ErasedAt           *time.Time `json:"erasedAt"`
}

// GetUserByIDForUpdate
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at, erased_at
//	FROM users
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	FOR UPDATE
func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id uuid.UUID) (GetUserByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i GetUserByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ErasedAt,
	)
	return i, err
}

const getUserTermsAcceptance = `-- name: GetUserTermsAcceptance :one
SELECT terms_version, terms_accepted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserTermsAcceptanceRow struct {
	TermsVersion    *string    `json:"termsVersion"`
	TermsAcceptedAt *time.Time `json:"termsAcceptedAt"`
}

// GetUserTermsAcceptance
//
//	SELECT terms_version, terms_accepted_at
//	FROM users
//	WHERE id = $1 AND deleted_at IS NULL
func (q *Queries) GetUserTermsAcceptance(ctx context.Context, id uuid.UUID) (GetUserTermsAcceptanceRow, error) {
	row := q.db.QueryRow(ctx, getUserTermsAcceptance, id)
	var i GetUserTermsAcceptanceRow
	err := row.Scan(&i.TermsVersion, &i.TermsAcceptedAt)
	return i, err
}

const lockPhone = `-- name: LockPhone :exec
SELECT pg_advisory_xact_lock(8734212, hashtext($1::text))
`

// Phones live in three profile tables, so no single unique index can guard them.
// This lock (namespace 8734212, keyed by the number) serializes writers of one
// number until the transaction ends.
//
//	SELECT pg_advisory_xact_lock(8734212, hashtext($1::text))
func (q *Queries) LockPhone(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, lockPhone, phone)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :execrows
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now()),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// MarkEmailVerified
//
//	UPDATE users
//	SET email_verified_at = COALESCE(email_verified_at, now()),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerified, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const phoneHeldByOtherActiveUser = `-- name: PhoneHeldByOtherActiveUser :one
SELECT EXISTS (
  SELECT 1
  FROM (
    SELECT user_id FROM customer_profiles WHERE phone = $1::text
    UNION ALL
    SELECT user_id FROM staff_profiles WHERE phone = $1::text
    UNION ALL
    SELECT user_id FROM admin_profiles WHERE phone = $1::text
  ) AS holder
  JOIN users u ON u.id = holder.user_id
  WHERE u.id <> $2::uuid
    AND u.deleted_at IS NULL
) AS held
`

type PhoneHeldByOtherActiveUserParams struct {
	Phone  string    `json:"phone"`
	UserID uuid.UUID `json:"userId"`
}

// PhoneHeldByOtherActiveUser
//
//	SELECT EXISTS (
//	  SELECT 1
//	  FROM (
//	    SELECT user_id FROM customer_profiles WHERE phone = $1::text
//	    UNION ALL
//	    SELECT user_id FROM staff_profiles WHERE phone = $1::text
//	    UNION ALL
//	    SELECT user_id FROM admin_profiles WHERE phone = $1::text
//	  ) AS holder
//	  JOIN users u ON u.id = holder.user_id
//	  WHERE u.id <> $2::uuid
//	    AND u.deleted_at IS NULL
//	) AS held
func (q *Queries) PhoneHeldByOtherActiveUser(ctx context.Context, arg PhoneHeldByOtherActiveUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, phoneHeldByOtherActiveUser, arg.Phone, arg.UserID)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const releasePhone = `-- name: ReleasePhone :exec
WITH released_customer AS (
  UPDATE customer_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
), released_staff AS (
  UPDATE staff_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
)
UPDATE admin_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
`

// Clears the phone on whichever profile the user has. Used when a returning
// account finds its number taken by an active one: the active holder keeps it.
//
//	WITH released_customer AS (
//	  UPDATE customer_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
//	), released_staff AS (
//	  UPDATE staff_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
//	)
//	UPDATE admin_profiles SET phone = NULL, updated_at = now() WHERE user_id = $1::uuid
func (q *Queries) ReleasePhone(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, releasePhone, userID)
	return err
}

const resetUserPassword = `-- name: ResetUserPassword :execrows
UPDATE users
SET password_hash = $2,
    must_change_password = false,
    email_verified_at = COALESCE(email_verified_at, now()),
    session_version = session_version + 1,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type ResetUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"passwordHash"`
}

// A reset link reached the account's inbox, so it confirms the address too.
//
//	UPDATE users
//	SET password_hash = $2,
//	    must_change_password = false,
//	    email_verified_at = COALESCE(email_verified_at, now()),
//	    session_version = session_version + 1,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMustChangePassword = `-- name: SetMustChangePassword :execrows
UPDATE users
SET must_change_password = true,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SetMustChangePassword
//
//	UPDATE users
//	SET must_change_password = true,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SetMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, setMustChangePassword, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDelete = `-- name: SoftDelete :execrows
UPDATE users
SET deleted_at = now(),
    session_version = session_version + 1,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// Closing an account ends its sessions for good, even if it is enabled again.
//
//	UPDATE users
//	SET deleted_at = now(),
//	    session_version = session_version + 1,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDelete(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staffFindCustomerByEmail = `-- name: StaffFindCustomerByEmail :one
SELECT
  u.id,
  u.email::text AS email,
  cp.display_name,
  cp.phone
FROM users u
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
WHERE u.email = $1
  AND u.role = 'customer'::user_role
  AND u.deleted_at IS NULL
`

type StaffFindCustomerByEmailRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName *string   `json:"displayName"`
	Phone       *string   `json:"phone"`
}

// An open customer account by its email, with what staff need to take an
// order for it.
//
//	SELECT
//	  u.id,
//	  u.email::text AS email,
//	  cp.display_name,
//	  cp.phone
//	FROM users u
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	WHERE u.email = $1
//	  AND u.role = 'customer'::user_role
//	  AND u.deleted_at IS NULL
func (q *Queries) StaffFindCustomerByEmail(ctx context.Context, email string) (StaffFindCustomerByEmailRow, error) {
	row := q.db.QueryRow(ctx, staffFindCustomerByEmail, email)
	var i StaffFindCustomerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Phone,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

// UpdateRole
//
//	UPDATE users
//	SET role = $2,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRole, arg.ID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash   = $2,
    session_version = session_version + 1,
    updated_at      = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"passwordHash"`
}

// A new password ends every session: refresh tokens of the old version are refused.
//
//	UPDATE users
//	SET password_hash   = $2,
//	    session_version = session_version + 1,
//	    updated_at      = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
