// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_token.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserTokens = `-- name: DeleteUserTokens :exec
DELETE FROM user_tokens
WHERE user_id = $1
`

// DeleteUserTokens
//
//	DELETE FROM user_tokens
//	WHERE user_id = $1
func (q *Queries) DeleteUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTokens, userID)
	return err
}

const redeemUserToken = `-- name: RedeemUserToken :one
DELETE FROM user_tokens t
USING users u
WHERE t.token_hash = $1
  AND t.purpose = $2
  AND t.expires_at > now()
  AND u.id = t.user_id
  AND u.deleted_at IS NULL
RETURNING t.user_id
`

type RedeemUserTokenParams struct {
	TokenHash []byte           `json:"tokenHash"`
	Purpose   UserTokenPurpose `json:"purpose"`
}

// Single use: the token goes as it is redeemed, in one statement, so two
// requests with the same link cannot both succeed. An expired token, or one
// of a closed account, opens nothing.
//
//	DELETE FROM user_tokens t
//	USING users u
//	WHERE t.token_hash = $1
//	  AND t.purpose = $2
//	  AND t.expires_at > now()
//	  AND u.id = t.user_id
//	  AND u.deleted_at IS NULL
//	RETURNING t.user_id
func (q *Queries) RedeemUserToken(ctx context.Context, arg RedeemUserTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, redeemUserToken, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const replaceUserToken = `-- name: ReplaceUserToken :exec
INSERT INTO user_tokens (user_id, purpose, token_hash, expires_at)
VALUES (
  $1,
  $2,
  $3,
  now() + make_interval(secs => $4::double precision)
)
ON CONFLICT (user_id, purpose) DO UPDATE
SET token_hash = EXCLUDED.token_hash,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
`

type ReplaceUserTokenParams struct {
	UserID     uuid.UUID        `json:"userId"`
	Purpose    UserTokenPurpose `json:"purpose"`
	TokenHash  []byte           `json:"tokenHash"`
	TtlSeconds float64          `json:"ttlSeconds"`
}

// Issuing a token replaces the user's last one of that purpose, so only the
// newest link works. Expiry is set on the database clock, which redemption
// checks against.
//
//	INSERT INTO user_tokens (user_id, purpose, token_hash, expires_at)
//	VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  now() + make_interval(secs => $4::double precision)
//	)
//	ON CONFLICT (user_id, purpose) DO UPDATE
//	SET token_hash = EXCLUDED.token_hash,
//	    expires_at = EXCLUDED.expires_at,
//	    created_at = now()
func (q *Queries) ReplaceUserToken(ctx context.Context, arg ReplaceUserTokenParams) error {
	_, err := q.db.Exec(ctx, replaceUserToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.TtlSeconds,
	)
	return err
}
