// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const adminCreate = `-- name: AdminCreate :one
INSERT INTO users (email, password_hash, role, must_change_password)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
`

type AdminCreateParams struct {
	Email              string   `db:"email" json:"email"`
	PasswordHash       string   `db:"password_hash" json:"passwordHash"`
	Role               UserRole `db:"role" json:"role"`
	MustChangePassword bool     `db:"must_change_password" json:"mustChangePassword"`
}

// AdminCreate
//
//	INSERT INTO users (email, password_hash, role, must_change_password)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
func (q *Queries) AdminCreate(ctx context.Context, arg AdminCreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminCreate,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const adminList = `-- name: AdminList :many
SELECT
    u.id,
    u.email,
    u.role,
    u.email_verified_at,
    u.must_change_password,
    u.created_at,
    u.updated_at,
    u.deleted_at,
    cp.display_name,
    COALESCE(sp.full_name, ap.full_name) AS full_name,
    COALESCE(sp.phone, ap.phone, cp.phone) AS phone,
    sp.employee_code,
    sp.hire_date,
    sp.shift
FROM users u
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
LEFT JOIN staff_profiles sp ON sp.user_id = u.id
LEFT JOIN admin_profiles ap ON ap.user_id = u.id
WHERE u.deleted_at IS NULL
  AND (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
  )
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type AdminListParams struct {
	Column1 string `db:"column_1" json:"column1"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type AdminListRow struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	Email              string         `db:"email" json:"email"`
	Role               UserRole       `db:"role" json:"role"`
	EmailVerifiedAt    sql.NullTime   `db:"email_verified_at" json:"emailVerifiedAt"`
	MustChangePassword bool           `db:"must_change_password" json:"mustChangePassword"`
	CreatedAt          time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updatedAt"`
	DeletedAt          sql.NullTime   `db:"deleted_at" json:"deletedAt"`
	DisplayName        sql.NullString `db:"display_name" json:"displayName"`
	FullName           string         `db:"full_name" json:"fullName"`
	Phone              sql.NullString `db:"phone" json:"phone"`
	EmployeeCode       sql.NullString `db:"employee_code" json:"employeeCode"`
	HireDate           sql.NullTime   `db:"hire_date" json:"hireDate"`
	Shift              sql.NullString `db:"shift" json:"shift"`
}

// AdminList
//
//	SELECT
//	    u.id,
//	    u.email,
//	    u.role,
//	    u.email_verified_at,
//	    u.must_change_password,
//	    u.created_at,
//	    u.updated_at,
//	    u.deleted_at,
//	    cp.display_name,
//	    COALESCE(sp.full_name, ap.full_name) AS full_name,
//	    COALESCE(sp.phone, ap.phone, cp.phone) AS phone,
//	    sp.employee_code,
//	    sp.hire_date,
//	    sp.shift
//	FROM users u
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	LEFT JOIN staff_profiles sp ON sp.user_id = u.id
//	LEFT JOIN admin_profiles ap ON ap.user_id = u.id
//	WHERE u.deleted_at IS NULL
//	  AND (
//	    $1::text = ''
//	    OR u.email ILIKE '%' || $1 || '%'
//	    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
//	    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
//	  )
//	ORDER BY u.created_at DESC
//	LIMIT $2 OFFSET $3
func (q *Queries) AdminList(ctx context.Context, arg AdminListParams) ([]AdminListRow, error) {
	rows, err := q.db.QueryContext(ctx, adminList, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRow{}
	for rows.Next() {
		var i AdminListRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.EmailVerifiedAt,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DisplayName,
			&i.FullName,
			&i.Phone,
			&i.EmployeeCode,
			&i.HireDate,
			&i.Shift,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCount = `-- name: AdminListCount :one
SELECT COUNT(*)
FROM users u
LEFT JOIN customer_profiles cp ON cp.user_id = u.id
LEFT JOIN staff_profiles sp ON sp.user_id = u.id
LEFT JOIN admin_profiles ap ON ap.user_id = u.id
WHERE u.deleted_at IS NULL
  AND (
    $1::text = ''
    OR u.email ILIKE '%' || $1 || '%'
    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
  )
`

// AdminListCount
//
//	SELECT COUNT(*)
//	FROM users u
//	LEFT JOIN customer_profiles cp ON cp.user_id = u.id
//	LEFT JOIN staff_profiles sp ON sp.user_id = u.id
//	LEFT JOIN admin_profiles ap ON ap.user_id = u.id
//	WHERE u.deleted_at IS NULL
//	  AND (
//	    $1::text = ''
//	    OR u.email ILIKE '%' || $1 || '%'
//	    OR COALESCE(cp.display_name, sp.full_name, ap.full_name, '') ILIKE '%' || $1 || '%'
//	    OR COALESCE(sp.employee_code::text, '') ILIKE '%' || $1 || '%'
//	  )
func (q *Queries) AdminListCount(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminListCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clearMustChangePassword = `-- name: ClearMustChangePassword :execrows
UPDATE users
SET must_change_password = false,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// ClearMustChangePassword
//
//	UPDATE users
//	SET must_change_password = false,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) ClearMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearMustChangePassword, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, must_change_password)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email              string   `db:"email" json:"email"`
	PasswordHash       string   `db:"password_hash" json:"passwordHash"`
	Role               UserRole `db:"role" json:"role"`
	MustChangePassword bool     `db:"must_change_password" json:"mustChangePassword"`
}

// CreateUser
//
//	INSERT INTO users (email, password_hash, role, must_change_password)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

// GetUserByEmail
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
//	FROM users
//	WHERE email = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

// GetUserByID
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
//	FROM users
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

// GetUserByIDForUpdate
//
//	SELECT id, email, password_hash, role, email_verified_at, must_change_password, created_at, updated_at, deleted_at
//	FROM users
//	WHERE id = $1
//	  AND deleted_at IS NULL
//	FOR UPDATE
func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setMustChangePassword = `-- name: SetMustChangePassword :execrows
UPDATE users
SET must_change_password = true,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SetMustChangePassword
//
//	UPDATE users
//	SET must_change_password = true,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SetMustChangePassword(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMustChangePassword, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDelete = `-- name: SoftDelete :execrows
UPDATE users
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// SoftDelete
//
//	UPDATE users
//	SET deleted_at = now(),
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) SoftDelete(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE users
SET role = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateRoleParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Role UserRole  `db:"role" json:"role"`
}

// UpdateRole
//
//	UPDATE users
//	SET role = $2,
//	    updated_at = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRole, arg.ID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
}

// UpdateUserPassword
//
//	UPDATE users
//	SET password_hash = $2,
//	    updated_at    = now()
//	WHERE id = $1
//	  AND deleted_at IS NULL
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
